### ISSUE TITLE
[aes] Tracking requested changes and work items

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#1005]
The goal of this issue is to track requested changes to the AES module and associated work items. Note this is about mid-term changes only not about discussing the long-term strategy.

**Style**:
- [x] Change data type to packed array: #1027 (old PR: #471)
- [x] Rework X-assignments: #1182 
- [x] Rework SystemVerilog functions to use explicit return value.

**Software**:
- [x] Add software library and sanity check: #1129 (old PR: #627)

**Features**:
- [x] Add feature to clear input and initial key register using a bit in the TRIGGER register (similar to output and internal key registers): #1053 
- [x] Clear internal registers with random/pseudo-random data instead of 0: #1845 .
- [x] Change behavior to ignore key and config updates while the AES unit is busy (similar to the HMAC module #1014): #1053
- [x] Connect to entropy source/CSRNG/EDN to reseed LFSRs: #5427
- [x] Re-add reset to registers: #4761
- [x] Implement a first non-LUT-based S-Box: #1242
- [x] Add additional cipher modes
  - [x] CBC and CTR: #1676 
  - [x] CFB-128 and OFB: #2727 
  - ~[ ] GCM~: #3113 , we decided not to do this for now
- [x] Make sure key regs have been written at least once after reset or clear before starting. Currently, this is only needed to detect when to start the decryption key generation but it is not enforced e.g. for encryption: https://github.com/lowRISC/opentitan/issues/2382#issuecomment-644034090, #2645
- [x] Make `NumAlerts` a top-level parameter, use separate alert signals for minor/major alerts: https://github.com/lowRISC/opentitan/pull/2152#discussion_r461242201
- [x] Add a new bit in the STATUS register indicating if the the data output registers have been overwritten before being read by the processor in manual mode. The bit could be cleared to 0 by an additional bit in the trigger register or upon a write to the config register. The primary use of this bit is DV:  #4835
- [x] Simplify clearing of registers, reduce the number of separate trigger bits to facilitate DV: #4848
- ~[ ] Consider adding a cause register to give more information on fatal/recoverable alerts~: https://github.com/lowRISC/opentitan/pull/4781#discussion_r555242281, we decided not to do this for now
- [x] Move main controller FSM into terminal error state ~and potentially clear registers~ upon receiving life cycle escalation signal: https://github.com/lowRISC/opentitan/pull/4781#discussion_r554114581, https://github.com/lowRISC/opentitan/pull/4781#issuecomment-758128597, #5401
- [x] KeyMgr sideload interface #7835
- [x] CSR to configure LFSR reseed frequency #9299
- [x] Consider making the IV register readable, see #10532 , #10996
- ~[ ] Consider qualifying the IV register with `regren`,~ see #10532, decided not to do this for now
- [x] Revisit the `prim_buf` on the `op_i` input inside the cipher core. This seems to defeat constant propagation completely when the INV operation isn't needed and resulted in a gate count increase of CSRNG of 5 kGE. See https://github.com/lowRISC/opentitan/pull/10483#discussion_r799684844

**Security Hardening**:
- [x] Implement high-bandwidth, local PRNG for cipher core masking, use random data for masked S-Box implementations
- [x] First-order masked, 2-share implementation of the cipher core: #2938 
- ~[ ] Masking of the cipher feedback path through the IV register as well as the counter~: https://github.com/lowRISC/opentitan/pull/2938#discussion_r461171161 We decided not to mask the feedback path and instead invest the area/resources required for that into other parts of the design.
- [x] Provide key in two shares: #2933 
- [x] Protect round counter inside cipher core controller against fault injection: https://github.com/lowRISC/opentitan/pull/4492#discussion_r544626948, #4910
- [x] Sparse state encoding for FSMs: #4781
- [x] Sparse encoding for mux selector signals: #4851
- [x] Sparse encoding for handshake signals: #5171
- [x] Further signals to harden against FI:
  - ~[ ] Consider protecting the rcon register and corresponding write enable inside the key expand module against fault injection.~ This is more like data path protection thing, decided not to do this for now.
  - ~[ ] Consider propagating sparsely encoded handshake signals down to S-Box level.~ See https://github.com/lowRISC/opentitan/pull/5171#discussion_r580638570 , At the individual S-Box level, this is more like a data path protection thing, decided not to do this for now.
  - [x] Consider hardening of inputs to `data_out_d` and `output_read_d` signals, these signals ultimately depend on signals driven from the auto-generated register file, we might require to harden the register file, too. See comments in #5171, #10753
  - ~[ ] Consider hardening the write enable signal of the data input registers. These registers are completely embedded inside the register file (not `hwext` like other main registers).~ This is best covered by regtool and there have been many additions in the meantime (e.g. ECC), and some further changes are coming (e.g. blanking). Not doing for now.
  - [x] Use sparse encoding for `ciph_op_e` type: #10483 
- [x] Document security decisions.
- [x] Once security hardening has stabilized, we need to investigate the quality of entropy required for masking and clearing as well as the characteristic of the PRNGs (uniformity etc.): https://github.com/lowRISC/opentitan/pull/5427#discussion_r585769935
Note: @vrozic has done this analysis and we reworked the PRNGs accordingly, see #8842
- ~[ ] Consider moving MANUAL_OPERATION and FORCE_ZERO_MASKS (FPGA only) config bits to lockable AUX_CTRL register.~ This was discussed as part of the D2S review and we concluded not to do this as locking the MANUAL_OPERATION bit together with other bits in the AUX_CTRL register may be unsuitable.
- ~[ ] Set `round_key_sel_o` to `ROUND_KEY_MIXED` in case of invalid `op_i`~, see https://github.com/lowRISC/opentitan/pull/10483#discussion_r796834141 We decided not to move forward with this as it increases the cipher core area if only forward/inverse operation is needed for a particular instantiation, see e.g. inside CSRNG.
- [x] Combine cycle counter in cipher core controller with S-Box `req_o` signal to aggravate FI. #10849

**Comment by vogelpi** [comment]
@rasmus-madsen this may be of interest to you for planning DV.

**Comment by msfschaffner** [comment]
@vogelpi is this issue still up to date?

**Comment by vogelpi** [comment]
> @vogelpi is this issue still up to date?

Yes it is. Don''t be mistaken by the date of the issue/comments. I keep updating the first comment as the work on AES continues. For example, if during a review some other task comes up, I'll write that down here and link the comment.

**Comment by tjaychen** [comment]
@vogelpi is sideload still on the table?

**Comment by vogelpi** [comment]
Good point @tjaychen ! I definitely have that on my list, but forgot to add it here. Now it's added as well.

**Comment by msfschaffner** [comment]
Thanks @vogelpi, just wanted to double check.

**Comment by tjaychen** [comment]
@vogelpi there's one more item that i've talked briefly to @moidx about (it might already be here, but i can't quite make out which one it is).

To support software redundancy, we probably need some kind of hardware context save / restore for the cipher chain modes, is that something you guys are looking into also? Sorry in advance if this is something you guys have discussed already.

**Comment by vogelpi** [comment]
Thanks for bringing that up. I didn't have this on my list as I wasn't sure it was coming. We would mainly need to save/restore the IV and maybe another internal 128-bit register. But I would hope we can avoid this by other means. But let's discuss this next Tuesday.

**Comment by tjaychen** [comment]
sounds good, thanks Pirmin.

**Comment by rswarbrick** [comment]
@vogelpi: I think there are a couple of items on the list above that aren't ticked off. Are they still live? (Or is this done?)

**Comment by vogelpi** [comment]
Thanks for the reminder Rupert. I went through the list again and crossed those items we are not doing for ES (plus added an explanation). Also, after almost 2.5 years it's probably time to start a new tracking issue. This one got really crowded.
