### ISSUE TITLE
Entropy_Src D2S Review AIs

### ISSUE THREAD

**Issue by mwbranstad** [lowRISC/opentitan#10096]
Action Items:
- [x] [Martin] Close on chip-level test issue (V1?)
- [x] [Martin] Update testbench to include entropy dropping event due to health check failure
- [x] [Tim, msf] need to add new asset (RNG) and countermeasure names (REGWEN) -> #10070
- [x] [Tim, msf] File issue for potential FIFO enhancement: add prim_count for pointers -> #10069
- [x] [Mark] Remove qualification of FSM invalid state signals and prim_count -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Martin] File issue for future improvements: split out fatal error conditions into indication CSRs -> It was determined that the ERROR_CODE status register does this function, so no issue was opened.
- [x] [Mark] use >= instead of == for counters -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Martin] file issue to clean up recursively instantiated module #10160
- [x] [Chris/Mark] audit MUBIs -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [Mark] make LOGIC.INTEGRITY more specific by adding an instance name -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [Mark] document fatal FIFO alerts-> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] document why multiple parameters are not shadowed in the CSRs (maybe in a short security section) -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Chris/Mark] go through Hjson and update all CM/ASSET names according to feedback -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [Mark] add countermeasure names to RTL comments, format to be used  “// SEC_CM: [INSTANCE].ASSET.CM_TYPE”. See also https://github.com/lowRISC/opentitan/issues/10071, https://github.com/lowRISC/opentitan/pull/10118
- [x] [Msf] create an issue for the tooling extensions needed for checking the above annotations #10071
- [x] [Mark] exchange “entropy_src_cntr_reg” with “prim_count” and hook up to alerts, don’t forget to add labels -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] add sha3 CM labels -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] add mubi fields to prim_mubi4_sync, then fan out to consumers -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] complete PR for issue https://github.com/lowRISC/opentitan/issues/10388 -> https://github.com/lowRISC/opentitan/pull/10520

**Comment by mwbranstad** [comment]
@msfschaffner all the boxes are checked now. Should we close this issue, or are there some additional steps to do before that happens in the security review flow?

**Comment by msfschaffner** [comment]
@mwbranstad we can close it once the D2S prj.hjson has landed. You could even do this automatically by adding `Fixes #10096` to the commit message of the D2S prj.hjson commit.

**Comment by msfschaffner** [comment]
@mwbranstad, a few questions regarding the D2S opens:
1) Should #10388 be addressed before we declare D2S?
2) Can you add the link to the following issue? I don't seem to find that one `[Martin] File issue for future improvements: split out fatal error conditions into indication CSRs`
3) In general it would be good to indicate where things have been addressed if possible, either providing the link above per item, or grouping the items as for instance done in: https://github.com/lowRISC/opentitan/issues/10420. There are still a couple of items above without link, and since many changes are squashed into large commits it is hard to trace what exactly has been addressed where.

**Comment by mwbranstad** [comment]
> @mwbranstad, a few questions regarding the D2S opens:
> 
> 1. Should [[entropy_src] RFC: Programming Model for FW_OV_ENTROPY_INSERT #10388](https://github.com/lowRISC/opentitan/issues/10388) be addressed before we declare D2S?
> 2. Can you add the link to the following issue? I don't seem to find that one `[Martin] File issue for future improvements: split out fatal error conditions into indication CSRs`
> 3. In general it would be good to indicate where things have been addressed if possible, either providing the link above per item, or grouping the items as for instance done in: [[otp_ctrl] D2S review opens #10420](https://github.com/lowRISC/opentitan/issues/10420). There are still a couple of items above without link, and since many changes are squashed into large commits it is hard to trace what exactly has been addressed where.

A1: #10388 can be added to the list. It did not start out as a security topic, but morphed into one.
A2: It was determined that the ERROR_CODE status register does this function, so no issue was opened.
A3: Will review again, but thought every AI had either a link or some explanation.

**Comment by msfschaffner** [comment]
Thanks @mwbranstad. It looks like the only pending item is #10520 - after that EDN appears to be good to go.

**Comment by msfschaffner** [comment]
Ok #10520 has been merged, thanks to @tjaychen's help. 
There is one more minor RTL fix that has to go in (#10621) and then we should be g2g here.
