### ISSUE TITLE
[rom_ctrl] D2S action items

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#10156]
We held a D2S review meeting for rom_ctrl on 18th Jan 2022. For project members, notes are [here](https://docs.google.com/document/d/1tAKdZTk2KkIcAjMk-heE3E6pedUiV3TAPqenXO7uYrY).

The review generated the following action items:
- [x] (Rupert) Document which FSMs are protected by FSM.SPARSE in the hjson file (#10286)
- [x] (Rupert) Add a `prim_mubi4_sender` at the source of the "good" signal in `rom_ctrl_fsm.sv' to prevent a synthesis tool from collapsing the 4-wire signal entirely. (#10286)
- [x] (Eunchan) Update KMAC docs, adding information about the mode/prefix used for each application interface. (#10162)
- [x] (Rupert) Link to these updated docs to make it easy for a reader to see what mode/prefix we're using in rom_ctrl (#10286)
- [x] (Miguel) Update the countermeasure spreadsheet to match current reality
- [x] (Miguel) Open an issue against the ROM extension with a recommendation about adding a check for the digest value (#10323)
- [x] (Rupert) Make sure that the IP version number is 1.0 in the PR updating prj.hjson (#9986)

**Comment by msfschaffner** [comment]
Spreadsheet has been updated.
