### ISSUE TITLE
[lc_ctrl] V2 review meeting TODO list

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10260]
- [ ]  Nigel: add more coverpoints to LC_CTRL, for example: fsm transition groups.

- [ ] Msf: Provide more inputs regarding functional coverage for LC_CTRL in the PR.

- [ ] Nigel: add a test to cover toggle coverage: scan_rst_ni

- [ ] Nigel: add a test to cover toggle coverage: lc_otp_vendor_test_i.status. Randomize this input and read in CSRs. (In some certain lc states, it should be 0)

- [ ] Cindy: Generate UNR for LC_CTRL to boost coverage and review with Michael.

- [ ] Nigel: kmac_data_i.digest _share - need to XOR - discuss offline with Michael if needed.

- [ ] Nigel: Otp_ctrl_i.{count, state} - set values outside of ‘legal’ to prove LC ctrl escalates and puts the device in scrap. As such, these inputs should be 100% covered.

- [ ] Nigel: modify env code to cover toggle coverage: kmac_data_i
        Force error bit to cause kmac transaction failure, if failured, will not accept the kmac data and lc_ctrl might go into an escalation state.
       Ready bit seems to be fixed to value 1.

- [ ] Nigel: toggle coverage - rma_taken_valid, test_tokens_valid, secrets_valid, otp_lc_data_i.valid
       Miss the case where token is not valid, then lc goes to escalation state.
       secrets_valid modulates: lc_creator_seed_sw_rw_en, lc_seed_hw_rd_en

- [ ] Nigel: randomize input `otp_lc_data_i` to cover all the toggle coverage.
       The chip is expected to go to the scrap state.

- [ ] Nigel: `lc_clk_byp_req_o`, request should go high if corresponding CSR is set. This needs an acknowledgement. Program `transitoin_ctrl` to achieve the purpose.

- [ ] Nigel: `device_id` and `manuf_state_i`: randomize and readout from CSRs.

- [ ] Nigel: set unique diversification values that toggle all output bits:
       RndCnstLcKeymgrDivInvalid  = ‘0
      RndCnstLcKeymgrDivTestDevRma = ‘1 
     RndCnstLcKeymgrDivProduction = {128/8{A5}}

- [ ] FSM Coverage:
   Nigel: Dmi_jtag_tap coverage: blackbox this module.

- [ ] Sri and Anka: File an issue and see what we can do to fully verify dmi/jtag.
   Check with pulp (dmi_jtag_tap owner) and see what they have done for verification.

- [ ] Nigel: Lc_ctrl_security_escalation is failing. 

- [ ] Nigel: Code coverage needs to be 90%+

- [x]  Cindy: Paste all nightly regression warnings to an issue and assign to Nigel to take a look.
  Issue: https://github.com/lowRISC/opentitan/issues/10258

**Comment by msfschaffner** [comment]
@NigelScales @cindychip can you go over this list and check off what has been done so that we can resolve this issue?

**Comment by cindychip** [comment]
I think this is all done because lc_ctrl already declared V2.
