### ISSUE TITLE
[otp_ctrl] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10420]
Taken care of in #10435:

- [x] [msf] update docs, define DAI/KDI/LCI towards the top
- [x] [msf] highlight in the programmer’s model that SW is responsible for integrity handling in the SW partitions
- [x] [msf] extend lc_sender primitive to have non-flopped option and instantiate it here for the token valid signals
- [x] [msf] replace CSRNG with EDN in the docs
- [x] [msf] This section suggests the otp_lc_data_o is only valid once all the relevant partitions are initialized, but by design they are marked as individual valids. Probably good to update to ensure no software confusion
- [x] [msf] Minor point on the DAI FSM.  It might be better for the blue box to just say IDLE, initially I was getting really confused on how there could be so many start-up arcs.
- [x] [msf] update error code table and include some more details
- [x] [msf] fix bullet list in macro assumptions section

Taken care of in #10473:

- [x] [msf] add CM labels to RTL
- [x] [msf] update counter descriptions (cross count)
- [x] [msf] reword OTP_CTRL.MACRO.MEM.INTEGRITY
- [x] [msf] add catch-all for additional Vendor-specific defenses OTP_CTRL.MACRO.MEM.CM
- [x] [msf] List MUBI locking signals as a CM, add SEC_BUF to bury these signals
- [x] [msf] Add CM labels for SW_UNREADABLE / REGREN capabilities
- [x] [msf] Double check arbitration FIFO depth and whether the wready signal needs to be respected
  - The OTP wrappers should respect the maximum in-flight limit of 2 transactions - but it is better to stay on the safe side. The RTL is hence updated to respect the wready signal.
- [x] [msf] check how hard it would be to increase hamming distance in error code. Otherwise add to SW guidance (e.g. what has to happen if we get an IRQ but no cause)
  - Answer: this is going to be a bit difficult at this stage since the development of the closed source wrapper and the DV have progressed quite far. To address this, the SW guidance is expanded.
- [x] [msf] add partition access control MUBI label (done as part f an AI above)
- [x] [msf] add a label for MUBI valid signals
- [x] [msf] add config REGWEN labels

Fixed in other PRs / Issues:

- [x] [msf] add scrambling key unreadable label (also add it to consumers like SRAM, FLASH, OTBN) #10433
- [x] [msf] create an issue for future enhancement: device-specific scrambling key #10434

Misc:

- [x] [msf] Is there any reason to qualify error output with whether current fsm error is set, and not just constantly output? Check this in RTL.
  - Answer: when a partition FSM is in an error state, it can have one of several error codes, hence the qualification. 
- [x] [tim, msf] CONSTANT.LC_GATED, Remove link, we changed to netlist burying. Double check whether this needs to be removed from open source. -> this has been removed from the spreadsheet.
- [x] [msf/chris] align spreadsheet
- [x] [msf/tim] check how wrapper internals should be signed off -> spun into separate issue, since it is not gating the open-source controller sign-off: #10541

**Comment by msfschaffner** [comment]
The action items have all been addressed and the block has been moved to D2S.
