### ISSUE TITLE
[aes] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10422]
- [x] [vogelpi] move counter flops into multi-rail FSM, remove custom design counter. See #10511
- [x] [vogelpi] fix REGWEN in Hjson. See #10488
- [x] [vogelpi] Label IV as separate asset (IV.CONFIG.SW_UNREADABLE, and IV.CONFIG.SEC_WIPE). See #9961
- [x] [vogelpi] expand description of all FSM.LOCAL_ESC descriptions, link to individual triggers (e.g. CTRL.SPARSE). Note that some of the other non-FSM-specific LOCAL_ESC labels may not be needed anymore afterwards. See #9961
- [x] [vogelpi] Consider using separately buffered copies for each lc_escalate sink. See #10488
- [x] [vogelpi] Add GLOBAL_ESC to cipher FSM. See #10511
- [x] [vogelpi] Annotate the RTL code with SEC_CM labels. See #9961
- [x] [vogelpi] Make KEY.SCA more specific, e.g. DATA_REG.KEY.SCA? Also, add a reference in the description to KEY.SEC_WIPE. See #9961
- [x] [vogelpi] Add a MUBI label for the LC_ESCALATE_EN signal. See #9961
- [x] [vogelpi] Add another bit to cipher mode CSR to increase HD: See #10483
- [x] [vogelpi] Add worst-case entropy consumption rate estimates to docs. See #10620
- [x] [vogelpi] Add some more info to the docs pointing out that we have a triple rail implementation. See #10620
- [x] [vogelpi] Indicate in the docs that we share some entropy flops in order to reduce circuit area. See #10620
- [x] [vogelpi] Indicate in the docs that the AES locks up until reset - it has no ability to reset itself. See #10620
- [x] [vogelpi/tim] bury some signals selectively and create a CM label (need to double check with Tim). See #10753
- [x] [vogelpi/chris] Update spreadsheet

**Comment by msfschaffner** [comment]
@vogelpi is there anything else that is gating the AES to go to D2S?

**Comment by vogelpi** [comment]
Some time ago, someone also suggested to convert the `Masking` and `SBoxImpl` parameters to `Sec` parameters to prevent that the masking is accidentally switched off or a less secure S-Box implementation is selected for tapeout. We didn't explicitly discuss this during the D2S meeting but it can be considered a security feature as well. The corresponding PR is here: #10844

**Comment by vogelpi** [comment]
Ping! Everything has been addressed now. I think we can merge #10846 to move AES to D2S. Please let me know if something else is needed from my side.

**Comment by vogelpi** [comment]
Closing as all relevant PRs have been merged and AES has reached officially D2S.
