### ISSUE TITLE
[rv_core_ibex] D2S Review Opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10523]
- [x] #10914, #11076
- [x] [msf] Add MUBI ADD/OR functions for LC -> #10560
- [x] [greg] Add a multibit encoded fetch enable signal (see notes for details) -> https://github.com/lowRISC/ibex/pull/1538, #11076
- [x] [greg] Add prim_buf around bus integrity checkers as described in notes, correction (vogelpi): I meant we should add prim_bufs around the regfile integrity checkers for the main core (shadowed core is fine). -> https://github.com/lowRISC/ibex/pull/1541
- [x] [greg] Add a note to the docs that for entirely data-independent execution timing, the icache would have to be disabled (or at least taken into account in the analysis). -> https://github.com/lowRISC/ibex/pull/1542/pull/1542
- [x] [greg] PC.CTRL_FLOW.CONSISTENCY add prim_buf to prevent optimizations -> https://github.com/lowRISC/ibex/pull/1541
- [x] [greg] Rename EXCEPTION.CTRL_FLOW.GLOBAL_ESC -> LOCAL_ESC -> https://github.com/lowRISC/opentitan/pull/10341
- [x] [greg] Update behavior of EXCEPTION.CTRL_FLOW.LOCAL_ESC according to the description below. -> #11001 
- [x] [greg/chris] update/align the countermeasure spreadsheet
- [x] [miguel] update countermeasure labels in assembly level threat model
- [x] [greg] Add note about the SENSITIVE_DATA.INTEGRITY to the docs
- [x] [miguel/greg] Spin out an issue to track choice of PMP reset values
- [x] [miguel] Schedule a security meeting for ROM before M2 (similar to D2S)
- [x] [greg] Wire up icache ECC error to Ibex minor alert and confirm this is still the desired behaviour
- [x] [greg] Should integrity failure on memory read response generate a bus error? -> https://github.com/lowRISC/opentitan/issues/11336

**Comment by msfschaffner** [comment]
CC @tjaychen

**Comment by msfschaffner** [comment]
Are there any updates regarding these tasks? 
If yes, it would be good to link the corresponding PRs for reference.

**Comment by tjaychen** [comment]
i have a pending PR for the pmp reset value integration. I will hopefully clean that one up soon and have it pushed for review.

**Comment by tjaychen** [comment]
@GregAC regarding the double fault capturing both addresses for the dump, what did you have in mind?
Right now it looks like the dump is directly fed from `ibex` out, were you thinking on double fault we capture a second output and then feed it out?

**Comment by GregAC** [comment]
> Right now it looks like the dump is directly fed from ibex out, were you thinking on double fault we capture a second output and then feed it out?

Yes when the double fault signal is seen the `epc` in the output is the `epc` of the original exception so we'll save a copy, the following cycle the `epc` will be where we took the double fault from.

> Are there any updates regarding these tasks?

Not yet sorry, been busy with other things mostly OTBN RTL work for the new blanking features on the engineering side of things.

**Comment by tjaychen** [comment]
> > Right now it looks like the dump is directly fed from ibex out, were you thinking on double fault we capture a second output and then feed it out?
> 
> Yes when the double fault signal is seen the `epc` in the output is the `epc` of the original exception so we'll save a copy, the following cycle the `epc` will be where we took the double fault from.

hmmm... so do you think this means i should update the dump format going from cpu to pwrmgr? because technically we want two copies of `epc` now in addition to an indication of double fault right? (to know whether the second epc is valid)

> 
> > Are there any updates regarding these tasks?
> 
> Not yet sorry, been busy with other things mostly OTBN RTL work for the new blanking features on the engineering side of things.

**Comment by GregAC** [comment]
> hmmm... so do you think this means i should update the dump format going from cpu to pwrmgr? because technically we want two copies of epc now in addition to an indication of double fault right? (to know whether the second epc is valid)

Yes that's correct.

**Comment by tjaychen** [comment]
@matutem please see 

> > hmmm... so do you think this means i should update the dump format going from cpu to pwrmgr? because technically we want two copies of epc now in addition to an indication of double fault right? (to know whether the second epc is valid)
> 
> Yes that's correct.

@matutem please see this last part. Unfortunately this means a slight change to the cpu dump format (and thus the related tests).
I will have a look and get back to you.

**Comment by tjaychen** [comment]
The double fault stuff is ongoing here #10975.
I'm not sure what you guys decided on double fault behavior, but it doesn't make sense to have it locally escalate.
For critical software infrastructure i tend to veer towards being conservative.  You have the option of making things globally escalate already.

**Comment by GregAC** [comment]
> I'm not sure what you guys decided on double fault behavior, but it doesn't make sense to have it locally escalate.

I believe the plan was to have a local escalation path that would immediately shut off the fetch enable as well as send out an alert for a global escalation.

**Comment by tjaychen** [comment]
> > I'm not sure what you guys decided on double fault behavior, but it doesn't make sense to have it locally escalate.
> 
> I believe the plan was to have a local escalation path that would immediately shut off the fetch enable as well as send out an alert for a global escalation.

alright, up to you guys i guess. This is not my decision to make.
For the record I think this is a bad idea, but if it was decided already let's move on.

**Comment by msfschaffner** [comment]
If I recall correctly, adding the local escalation path for double faults has been suggested mainly for the following two reasons:
- there was a recently published attack that exploited double faults in the main processor (@GregAC can you maybe provide a reference for the paper?), and clamping down early would help defending against these.
- for the software side, double faults are a fatal error condition from which it is hard to recover (@moidx correct?)

That being said, @tjaychen does have a point that adding this local escalation path may be risky since this condition can be triggered by errors / bugs on the software infrastructure side. If the processor dies due to local escalation, there is no way to do any further debugging. Also, local escalation paths are baked into HW and cannot be configured (i.e. turned off), so making this alert recoverable may be more prudent (immediate global escalation would still be possible in that case, if needed).

@moidx @cdgori any thoughts (since you were on the security council for this)?

**Comment by tjaychen** [comment]
if we already made the decision (the notes and #8152 don't seem explicit about this, but I just don't remember), let's just move on.
I think we need to get in a habit of sticking to our decisions unless there is concrete evidence to dig it up again.  

The entire "well this is bad for software debug" principle I'm operating on has not been mandated as a project tenant, so it's difficult to use it now to subvert the decision.  If we did decide that double fault halting execution is the right way to deal with the mtvec attack, then let's just document it and stick with it.  It would be good to add a line to this in the documentation.

**Comment by GregAC** [comment]
@msfschaffner @tjaychen @cdgori @moidx  once the Ibex PR: https://github.com/lowRISC/ibex/pull/1515 is merged and we vendor across I believe all my actions for Ibex D2S will be complete. Let's aim to hit that early next week.

Note I've added a new minor alert, one that occurs in icache ECC errors. There was a TODO within the Ibex RTL that indicated this was desired (ICache just ditches and refetches the line, it never attempts to correct errors).

**Comment by msfschaffner** [comment]
Thanks @GregAC. Regarding the ECC error, does that have to be fatal? Just bringing this up since we treat ECC errors on the bus or coming from SRAM as fatal in other cases...

**Comment by msfschaffner** [comment]
I see - this is an option we've not considered before since other SRAMs in the system can't refetch the data in case of bad integrity.

I was mainly thinking that making it fatal would align the behavior with other integrity faults in the system, since they are all treated as fatal faults.

I would be interested in what others think.

**Comment by msfschaffner** [comment]
Unrelated: I just stumbled accross this issue here https://github.com/lowRISC/opentitan/issues/9528. @GregAC can you take a look? It sounds like that one should be addressed as part of D2S, too.

**Comment by tjaychen** [comment]
sorry just to chime in on icache. I think the main motivation of having an error there continue is mostly because... if the whole thing died, there would be no way for software to even handle an NMI type of behavior.

**Comment by moidx** [comment]
Added the mask ROM security review to the task plan.
