### ISSUE TITLE
[OTBN] V2 follow-ups

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#10705]
We had a V2 review meeting for OTBN on 4th February. For OpenTitan members, notes are [here](https://docs.google.com/document/d/1oxjd_Rf1mb3ki3Es0nRpZwUApq3KtuD497UVjb8I1uc).

Action items:
- [x] (Rupert) Test key rotation, which will address missing toggle coverage
- [x] (Rupert) Add a coverpoint for pairwise consecutive mnemonics (#11013)
- [x] (Rupert) Tweak key sideload agent to send all 384 bits (Actually, Canberk did it! #10850)
- [x] (Rupert) Fix the `otbn_escalate` test (#11339, #11350, #11351, #11353, #11371)
- [x] (Rupert) Increase the reseed count a bit for things with just 5 seeds to make it more robust against random "lucky" seeds (#11033)
- [x] (Sri) Tweak text for `sim_fw_simulated` in the checklist document - DONE: #10711 
- [x] (Rupert) Update hjson to add some comments justifying the recently added CSR exclusions (#11372)

**Comment by rswarbrick** [comment]
All tasks now done. There's still a bit of missing branch/cond coverage. I'll push up a PR to move to V2 once that's above 90% in the nightlies.
