### ISSUE TITLE
[bazel,ottf] Enable running OTTF-launched tests at various boot stages

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#10712]
# Overview
After the tasks in #10498 are completed, OTTF-launched tests (e.g., chip-level tests) will be able to run with either the test ROM or mask ROM. When they are run via the test ROM, said tests will run as the 2nd boot stage, i.e., after the test ROM finishes executing. However, when they are run via the mask ROM, there are two options:
1.  a test could run at the second (ROM_EXT equivalent) boot stage (as done when the test is run via the test ROM), or
2. or at the third (BL0) boot stage, if a valid ROM_EXT is also present. 

For pre-Si verification it is advantageous to run all tests at the second boot stage (option 1 above), to minimize the number of signature verifications that must be completed, and therefore simulation runtime. However, for post-silicon verification, it is advantageous to run tests at the third boot stage (option 2 above), for key management purposes. Therefore, it is desirable to be able to configure the test runners (e.g., opentitantool / bazel) to select the boot stage tests are run at.

Additionally, for mask ROM / ROM_EXT testing, is is desirable to test flash images (e.g., OTTF + a test) loaded in all slots (i.e., slots A, B, and virtual).

# Tasks
To do achieve this:
- [x] refactor OTTF linker scripts to enable building for any slot (A, B, virtual) at the silicon_creator (ROM_EXT) boot stage (#14190)
- [x] do the same as above for the silicon_owner (BL0) boot stage (#14916)
- [x] update bazel rules to build **signed** tests in the slots/stages configured (#14533)
    - [x] cleanup build targets / tests for rom_ext / BL0 stages to use same naming convention (#14522)
    - [x] add slot option (+ default) to `opentitan_functest` macro to instruct how to build test image for when the flash binary is built by the macro, defaulting to slot A (#14521)
    - [x] add address translation to test ROM and update default slot for tests to the virtual slot (#14890)
