### ISSUE TITLE
aes V2 action items

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#10757]
this is a list of action items in the V2 review, meeting notes can be found here:https://docs.google.com/document/d/1ylaS4mXN_Y70PbSSOGihweZlRVU90deqAKwG6fRZdj0/edit?usp=sharing

- [x] update description of back2back test. #10763 
- [x] Add testpoint for reseeding #10763 
- [x]  Remove force zero mask from testplan #10763 
- [x] remove regwen from testplan and coverplan ,  #10763 
        only the general regwen IP test is left
- [x] update section on functional coverage in dv documentation #10992 
- [x] Lc escalate #10806
- connect interface
- create test that verifies the dut goes into FATAL until reset is pulled
- create test and cover point in documentation

- [x] add check to confirm the idle_o matches the status #10780
- [x] get branch coverage above 90 #10826 
- [ ] add missing functional coverage points #11219

**Comment by rasmus-madsen** [comment]
@martin-lueker if you want to track the status
