### ISSUE TITLE
[kmac] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10823]
- [x] Align CFG_SHADOWED with CONFIG.SHADOW name
- [x] Add sparse FSM in kmac_core, which isn’t listed in the hjson
- [x] LFSR.REDUN Nit: The [countermeasure](https://github.com/lowRISC/opentitan/blob/master/hw/ip/aes/data/aes.hjson#L221) text says “prim_lfsr”, which needs fixing.
- [x] LFSR.REDUN Nit: The comment above the instantiation of u_lfsr has a note about the “FSM below” which probably needs updating. The signal doesn’t feed into an FSM at all: it is wired directly to the alert_fatal signal in the kmac module.
- [x] CTR.REDUN Nit: The countermeasure text says “prim_counter” but the primitive is called “prim_count”.
- [x] CTR.REDUN Nit^2: Typo in hjson text: redundancy has an “a” in it :-)
- [x] CTR.REDUN There are 2 more prim_count instances (u_key_index_count in kmac_core; u_sentmsg_count in sha3pad). These probably need declaring. https://github.com/lowRISC/opentitan/pull/10842
- [x] SW_KEY.KEY.MASKING: mask data using PRNG
- [x] SW_KEY.KEY.MASKING: apply random mask to padding
- [x] prim_dom_and_2share.sv: should we use prim_buf/prim_flop: #10999 
- [x] PRNG: Need to add label PRNG.LFSR.REDUN #10892
- [x] PRNG: reduce the mux from 3 to 2 input, default to EDN input instead of 0 #10893
- [x] PRNG: add a RndCnst for DefaultSeed #10894
- [x] Double check intg_error of tlul_adapter_msgfifo
- [x] Use lc_tx_or_hi function for ORing lc_tx signals https://github.com/lowRISC/opentitan/pull/10814
- [x] Check StAppMsg comment in the code, whether this is an open TODO or not #10934
- [x] Should document escalation countermeasure #10949 
    - LC escalate input is MUBI
- [x] Should edn timeout be documented as a countermeasure?
- [x] Should document regwen as countermeasure #10949
- [x] Make keccak_2share/sel_i a MUBI https://github.com/lowRISC/opentitan/pull/10819
- [x] App interface mux select (kmac_app/mux_sel) -> should this be mubi
- [x] Entropy_fast_process -> should be mubi
- [x] Make hash threshold a shadow reg https://github.com/lowRISC/opentitan/pull/11138
- [x] Make hash counter a prim_count https://github.com/lowRISC/opentitan/pull/10812
- [x] Tim to check whether we have to add a spurious valid detection to KEYMGR #11361 
- [x] Michael T to add reviewers (Chris, Tim) to look at state read portion https://github.com/lowRISC/opentitan/pull/10744
- [x] #11078 #11119
- [x] Add countermeasure labels to RTL 
- [x] Chris/Tim to align final list of CMs in spreadsheet https://github.com/lowRISC/opentitan/pull/11383
- [x] Investigate adding a 1600bit output permutation of the PRNG https://github.com/lowRISC/opentitan/pull/10925, https://github.com/lowRISC/opentitan/issues/10873

**Comment by m-temp** [comment]
- #10814 is merged.
- Chris and Tim were assigned to look at #10744
- #10880 and #10814 for LC escalate input is MUBI

**Comment by m-temp** [comment]
As I don't have commit rights, could someone merge:
 - #10812 
 - #10819

 - #10842 needs #10812 to be merged first in order to be addressed.

**Comment by eunchan** [comment]
For shuffling the storage, #10925

Issue: #10873

**Comment by eunchan** [comment]
> Double check intg_error of tlul_adapter_msgfifo
>
intg_errors of msgfifo *and staterd* are not used. the integrity error of the main TL-UL interface is being checked in `kmac_reg_top.sv`.

Please correct me if I am wrong.

**Comment by m-temp** [comment]
- #11138 for the hash shadow register

**Comment by eunchan** [comment]
Thanks @m-temp for taking care of this issue #11138. Looks like we completed the AIs. I will create a PR to move KMAC to D2S.

**Comment by msfschaffner** [comment]
@tjaychen there is one open tick here: `Tim to check whether we have to add a spurious valid detection to KEYMGR`

has that been addressed, or do we still need to look into that?

**Comment by tjaychen** [comment]
i checked and...we do not :)
This needs to be something where keymgr needs to be enhanced.

**Comment by tjaychen** [comment]
> i checked and...we do not :) This needs to be something where keymgr needs to be enhanced.

@msfschaffner 
@eunchan 
@cdgori 
i'm having some problems remembering, we were talking about valid detection from the `kmac` going back to the `keymgr` right?

**Comment by msfschaffner** [comment]
> > i checked and...we do not :) This needs to be something where keymgr needs to be enhanced.
> 
> @msfschaffner @eunchan @cdgori i'm having some problems remembering, we were talking about valid detection from the `kmac` going back to the `keymgr` right?
> 
> There are no spurious checks right now, but the "valid" can only happen at a very specific point in time. I'll add a spurious check.

yes that was regarding the valid bit that goes from `kmac` back to the `keymgr`. a spurious check sounds good!
