### ISSUE TITLE
[opentitantool] Persistent sessions

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#10889]
# Problem
OpenTitan tool allows for a variety of backend "Transports", some of which are drivers for hardware debuggers, others emulate OpenTitan or related chips.
By their nature, some of those drivers will maintain state in the Rust struct that implements the Transport trait, others may have USB connections to hardware, which gets disturbed if the USB connection is closed and restablished.
Rust programs which link directly with OpenTitan lib are able to keep the Transport object for a long as needed, making a sequence of method invocations to "stimulate" the device under test.  However, users of the command line OpenTitan tool does not have that ability, since each command line invocation generally results in the creation of a Transport object, and the one "useful" method invocation, before the Transport is closed as the process terminates.

# Proposal
We will add a new optional persistent “OpenTitan session proxy” process (a daemon).  When used, all communication with the Transport backend will go through this proxy process.  The proxy process will listen on a TCP socket and contain the "real" Transport implementation, maintaining emulator state or connection to USB hardware.  The command line OpenTitan tool will use a "stub" Transport implementation, which forwards all requests via a TCP connection to the proxy.

Design document: https://docs.google.com/document/d/18JIqdYcmJKDzANheNS9JI1rEre6-iXPZhjMjliAS0TE/edit#

## Tasks
- [x] Make sure all error return values from Transport methods can be serialized (with serde) (#10964)
- [x] Declare wire protocol by as a number of Rust structs/enums (#10994)
- [x] Implement "stub" Transport (using serde JSON text via TCP) (#11023)
- [x] Implement proxy server functionality (opentitansession binary) (#11054)
- [x] Ability for opentitansession to run in background (as daemon) (#11173)

This proposal has significant overlap with previous issue #10217, which proposed a JSON TCP protocol for communicating with an emulator running in a separate process.  With this proposal, the interface to the emulator would instead be the Transport trait itself, that is, the top-level process of the emulator would either be opentitansession, or would be another binary that links with a library containing most of the functionality of opentitansession (the listening on TCP socket, and translation of protocol into calls to Transport trait.)

**Comment by jesultra** [comment]
Final PR has merged a long time ago.
