### ISSUE TITLE
[clkmgr] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10926]
- [x] make MUBI / LC synchronizations more generic (multiple places).
- [x] Check whether jitter enable going to AST could be a MUBI. If not, it would be good to flop the signal before sending it to AST. 
- [x] Synchronize step_down_ack signals
- [x] Check whether hi_speed_sel_o can be made a MUBI
- [x] we should add a REGWEN to JITTER_ENABLE.
- [x] Look into whether we can add blanking based on address in reggen (reg_top). Consider putting the gating into the XBAR. Also need to think whether gating to zero is the right thing to do for all critical registers (e.g. invalid MUBI nibble pattern). Make a separate issue that tracks this (so that it does not gate clkmgr D2S). https://github.com/lowRISC/opentitan/issues/11036
- [x] Check whether the MUBI can be pulled down into the clock divider circuit. Assess design impact first.  This was not done in the end because the step down request is completely synchronous to the clock divider.  However, the synchronize has been switched to a mubi sync to make sure the multi-bit nature stays. 
- [x] Investigate whether the idle interface can be improved and add a handshake so that the signal is more difficult to glitch. May have to punt this to after ES (as a future enhancement), though since this touches so many interfaces.  #11157 
- [x] Chris to sync spreadsheet to CMs
- [x] Double check whether the behavior of the two hints sent to OTBN is still correct.  #11157 
- [x] Make sure there is an issue that tracks the clock-pollution cleanup.
- [x] Minor doc alignments

**Comment by tjaychen** [comment]
regarding this item `Check whether the MUBI can be pulled down into the clock divider circuit. Assess design impact first.` i ended up not doing it exactly.

Instead, i kept the `step_down_req` as multi-bit signals through the synchronizer and then did a strict check in front of the prim divider. This is mostly because once inside, it is a purely synchronous signal, so I didn't think there was a great advantage doing it outside vs in.  The synchronizers though I think definitely need to be the multi-bit type.

**Comment by msfschaffner** [comment]
> regarding this item `Check whether the MUBI can be pulled down into the clock divider circuit. Assess design impact first.` i ended up not doing it exactly.
> 
> Instead, i kept the `step_down_req` as multi-bit signals through the synchronizer and then did a strict check in front of the prim divider. This is mostly because once inside, it is a purely synchronous signal, so I didn't think there was a great advantage doing it outside vs in. The synchronizers though I think definitely need to be the multi-bit type.

I think that should be ok. As you say, the important part is to make sure the MUBI is pulled through the synchronizer.

**Comment by tjaychen** [comment]
i finally syncd' the spreadsheet! also noticed a few things were missing from the doc / hjson...(siiigh)...
