### ISSUE TITLE
[kmac] V2 TODO lists

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#10927]
- [x] File an issue to discuss entropy related error on app interface, 
       and add a TODO to update the test based on new design D2S behavior
     Done: https://github.com/lowRISC/opentitan/issues/10933
     TODO added here: https://github.com/lowRISC/opentitan/pull/10940

- [x] Toggle coverage: Strobe can be fully randomized at any cycles
   DONE: https://github.com/lowRISC/opentitan/pull/10967

- [x] Update new UNR
  DONE: https://github.com/lowRISC/opentitan/pull/10940

- [x] #10804 is a V2 issue, need to address
   DONE: moved to V2S, and the fixing PR is out, just pending merge.

- [x] CSR exclusion:
   CFG_SHADOWED.err_processed - Check if excl is needed
   CFG_SHADOWED - Probably don’t need exclusion in register level
   ERR_CODE - Change to WriteCheck instead of ExclCheck, which excludes init check as well.
  DONE: https://github.com/lowRISC/opentitan/pull/10941

- [x] Fix doc tetstplan linking.
   DONE: https://github.com/lowRISC/opentitan/pull/10969

FYI:
@weicaiyang @eunchan @sriyerg
