### ISSUE TITLE
[otbn] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#11019]
Pre D2S review known actions:
- [x] Finish blanking implementation - #10824
- [x] Implement ECC integrity for ISPRs, including end to end integrity (keep existing ECC from ISPR/Reg when copying to/from register file) - #11973 
- [x] Loop stack integrity (see actions below and meeting notes for more details)

From 1st session:

- [x] Add CM labels to RTL https://github.com/lowRISC/opentitan/pull/12986
- [x] Make sure all sparse FSMs have an error state. See #11843
- [x] Make multiple copies of lc_escalate_en using prim_lc_sync, see #11864
- [x] @GregAC  to review again all paths going from bignum to base side and note them on the blanking issue so that we can decide whether more is needed here.
- [x] @johannheyszl to check RE SW hardening for the zero point detection path: It was found that any implementation would react to a failed check (zero flag set) with something that is much more visible in SCA than the flag itself (by executing the "else" branch). Therefore further hardening doesn't seem necessary.
- [x] add prim_and cells for blanking. Pirmin can help to create these cells. Michael to add the closed source version. See #11084
- [x]  check FIPS bit of EDN it and make it a recoverable alert, see #11914
- [x] Add repetition check for EDN data inside prim_edn_req. Make the error a recoverable alert. See #11914
- [x] Document type of PRNG used, See #12199
- [x] Switch on secure wipe feature, see #11842
- [x] @rswarbrick  to create an issue to track secure wipe bug: https://github.com/lowRISC/opentitan/issues/11091
- [x] @vogelpi  to review memory subsystem (see associated items in the notes)
- [x] Add prim_count for loop stack, use cross count if possible otherwise redundant count https://github.com/lowRISC/opentitan/pull/12485
- [x] Trigger fatal alert if OTBN imem/dmem access not granted (currently a [TODO in otbn.sv](https://github.com/lowRISC/opentitan/blob/f3ff88a9d3df10aa2aef2db208065bbfdb8acdb3/hw/ip/otbn/rtl/otbn.sv#L307-L308)) - #12229

From offline memory scrambling review:

- [x] Add prim_bufs around register-file entities, note this will come for free on the read side with the blanking (assuming we have prim_and inside the one-hot muxes)
- [x] Dmem window: add a SEC_CM label for that e.g. MEM.SW_UNREADABLE?
- [x] dmem/imem_rdata_bus signals are blanked to 0 whenever OTBN is busy to not leak instructions and data through bus - #12256
- [x] dmem/imem_rdata_bus signal blanking: Should probably use a prim_buf to not make synthesis optimize away the blanking - #12256
- [x] dmem/imem_rdata_bus signal blanking: Should probably add a SEC_CM label for that https://github.com/lowRISC/opentitan/pull/12986

From 2nd session: 

- [x] Program counter: we should add counter duplication here. 
- [x] Program counter: Investigate whether it makes sense to reuse the Ibex PC countermeasure for the OTBN PC as well.
- [x] Loop stack: ECC on addresses, we are adding cross/duplicate counters per loop. https://github.com/lowRISC/opentitan/pull/12485 https://github.com/lowRISC/opentitan/pull/12660
- [x] Call stack: use redundant counters for the r/w pointers. https://github.com/lowRISC/opentitan/pull/12467
- [x] Call stack: investigate whether it makes sense to add a depth crosscheck or an increment size check. https://github.com/lowRISC/opentitan/pull/12467
- [x] Call stack: add a check for push/pop signals (decode these in two different ways, and crosscheck them at the call stack). https://github.com/lowRISC/opentitan/pull/12467
- [x] URND: modify the reseed request signal in the internal FSM so that it is not being pulsed, but held high as long as the request is pending. Also check for spurious acks on that interface. - https://github.com/lowRISC/opentitan/pull/12474
  - [x] Add spurious ack check https://github.com/lowRISC/opentitan/pull/12669
- [x] URND: create an issue for examination of all req/ack interfaces, need to check whether additional check for spurious acks is needed on a per case basis. #11172
- [x] we should document that the narrow regfile is not protected with blanking.
- [x] zero the flags once op completes.
- [x] make sure that the OTP scrambling key holding register is reset to a RndCnst instead of all-zero. #11175
- [x] create an issue that captures the “memory window isolation via different scrambling keys” feature (future enhancement). #11171
- [x] Chris to sync spreadsheet to CMs

Other D2S requirements:
- [x] A couple of final decisions to make on the blanking implementation (https://github.com/lowRISC/opentitan/issues/12224)
- [x] BN.LID hardening (https://github.com/lowRISC/opentitan/issues/7888)
- [x] remove critical GPR and WDR registers from reset (https://github.com/lowRISC/opentitan/pull/13321, https://github.com/lowRISC/opentitan/pull/13192, https://github.com/lowRISC/opentitan/pull/13724)
- [x] Shrink scratchpad memory https://github.com/lowRISC/opentitan/pull/11026, work complete but PR needs rebasing.

**Comment by GregAC** [comment]
Regarding the PC hardening, @andreaskurth has implemented something here: https://github.com/lowRISC/opentitan/pull/12518 however we don't think it adds any attack resistance over just checking the prefetched instruction matches the instruction requested by the execute stage. I have introduced a new fatal error for a mismatch here in: https://github.com/lowRISC/opentitan/pull/12734

The prefetch stage and the execute stage each have their own flops for the PC and both calculate the increments separately, so this already gives you a duplicated counter and increment check.

I've had a couple of other ideas for further hardening around control flow, I'll open an issue/draft PR to discuss though they're not strictly D2S tasks as they weren't required actions.

**Comment by rswarbrick** [comment]
Since this issue has slightly become a burn-down list of "stuff to do before D2S", I've added a couple of extra items at the bottom of the list, based on looking at the M2 list in the rather slick OpenTitan project view (https://github.com/orgs/lowRISC/projects/13/views/9).

**Comment by GregAC** [comment]
> zero the flags once op completes.

Turns out I was mistaken and this is already happening as part of the secure wipe.

**Comment by GregAC** [comment]
> Dmem window: add a SEC_CM label for that e.g. MEM.SW_UNREADABLE?

We're not adding SEC_CM labels for such 'functional' features. This isn't an inherent hardware security feature protecting some hardware asset but rather architectural functionality that can be used for security purposes by software.

**Comment by msfschaffner** [comment]
I have aligned the spreadsheet accordingly, so that part should be good now.

The only parts that remain are the reset removal (and related patches).

**Comment by GregAC** [comment]
Just realised there's another outstanding task, https://github.com/lowRISC/opentitan/pull/11026 needs rebasing and merging

**Comment by johngt** [comment]
For the final remaining issue (if scratchpad memory is closed off) 'remove critical GPR and WDR registers from reset', believe from internal meeting notes that @andreaskurth has done the following:
#13719 merged
#13321 merged
#13192 was reviewed and merged in yesterday by @vogelpi 
#13724 was reviewed and merged in however #13908 mentioning this PR is still open.
If #13908 de-linked then this sub task might be completed. @andreaskurth should be able to comment on Monday if there is  any outstanding work for this subtask.

**Comment by GregAC** [comment]
> Also tagging @GregAC in case he is aware of something that means that subtask cannot be closed off.

I believe we're good to go

**Comment by msfschaffner** [comment]
I merged https://github.com/lowRISC/opentitan/pull/13908 also since it LGTM.
I agree, we're ready to go.
