### ISSUE TITLE
[sram_ctrl] V2S review action items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11039]
- [x] Talk with Michael offline to discuss otp/sram key interface in top-level test. (Done @msfschaffner commented at https://github.com/lowRISC/opentitan/pull/10490#discussion_r812544527) (Done #11105 )
- [x] Resolve issue https://github.com/lowRISC/opentitan/issues/10909 and make necessary DV update
- [x] Complete FPV_SEC_CM_VERIFIED (Done @cindychip added #11030)

V2S process related AIs
- [x] Update the first checklist item to remind people to import common tests and testplan. （#11053）
- [x] Add SIM_COVERAGE_REVIEWED in V2S checklist （#11053）

**Comment by msfschaffner** [comment]
@weicaiyang can this be closed?

**Comment by weicaiyang** [comment]
> @weicaiyang can this be closed?

Yes, thanks for reminding me
