### ISSUE TITLE
[entropy_src/dv] V2 review checklist

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#11315]
[V2 Review notes](https://docs.google.com/document/d/1x_GSqiDBBCVHr0n3agOP58X0iKuDQLhnGuliA7PB0WU)

- [x] Add a test to check hardware mediated REGWEN locking (SWREGUPD and auto-lock)
- [x] ~~File issue regarding rendering problem~~ Done: #11313
- [x] Implement new functional coverage testpoints from #11244
- [x] Understand and fix lack of toggle coverage for `cs_aes_halt_req`, `cs_aes_halt_ack`
- [x] Specify and implement covergroup for all possible configurations (including fips bit)
- [x] Document that `entropy_src_xht_o/i` are not a tested feature and add coverage exclusions
    - Pending #16308 
- [x] Mention in the checklist that the `FpvSecCm*` assertions are not covered at V2
   - Pending #16308 
- [x] Need to double check that all V2 tests pass with at least one seed
- [x] Expression and branch coverage need to be brought up to 90%
- [x] Model OTP switches in scoreboard
- [x] Resolve high priority issue #11144
- Root cause low priority issues: 
    - [x] #2111, moved to D3/M3
    - [x] #5630 
- [x] Cleanup unneeded CSR exclusions
    - Watermark CSRs - Removed many exclusions ->https://github.com/lowRISC/opentitan/pull/11322
    - Debug Status CSR - removed here, and removed from MAIN_SM_STATE ->https://github.com/lowRISC/opentitan/pull/11322
    - Try to use `CsrNonInitTests` instead of `CsrAllTests` -> Converted many, but not all -> https://github.com/lowRISC/opentitan/pull/11322

**Comment by johngt** [comment]
Just a gentle nudge / reminder @martin-lueker / @mwbranstad on the final issues here.
There is a review meeting scheduled for Entropy_src V2S on 14 November and one of the things that will be checked is if overall V2 has been signed off. Thanks!

**Comment by vogelpi** [comment]
Closing as entropy_src is now V2.
