### ISSUE TITLE
[keymgr] D2S review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#11387]
- [x] [tim] make usage of keymgr state CSR clear in the programming model. #11393
- [x] [tim] add assertion ASSERT_INIT(LfsrWidth_A, LfsrWidth == 64) #11393
- [x] [tim] add assertion ASSERT_INIT(StageCheck_A, KeyMgrStages == (Owner+1)) #11393
- [x] [tim] use a sec_anchor_buf to bury RndCnstNoneSeed #11393
- [x] [tim] add dest_sel / op value crosscheck #11424 
- [x] [tim] swap alert indexes #11393
- [x] [tim] make op fsm sparse, probably needs to be a synchronous alert condition. #11393
- [x] [tim] double check async / sync behavior of alerts, i.e. do async (fatal) alerts wipe immediately or not? They should technically wipe immediately since the faults are fatal. Figure out what the timing for these should be. #11392 
- [x] [tim] make sure HW.KEY.SW_NOACCESS is checked with FPV (file issue for this and tag Cindy) #6543 
- [x] [tim] estimate what the probability of these checks evaluating to true is (without FI). need to evaluate whether these probabilities are statistically of concern.
- [x] [tim] check whether repeated block checks are needed at EDN input (may not be needed if it is not FIPS grade) Issue #11477 
- [x] [tim] protect working key register at rest with ECC #11428 
- [x] [tim] remove the comment regarding explicit reset from docs and RTL #11393
- [x] [tim] clean up RTL and doc according to comments above #11479 #11495
- [x] [tim] latch root keys coming from OTP constantly, when valid #11459

**Comment by msfschaffner** [comment]
Hey @tjaychen, is there still something that we need to do there? Looks like there are still two items unchecked above, while the keymgr has already been moved to D2S...

**Comment by tjaychen** [comment]
yeah all the items that required a change are done.
The remaining one is the probability check (which is something insane like 4 / 2^256), and i have to dig up the other issue that talks about FPV. Once I do that we can close this.

**Comment by tjaychen** [comment]
For the probability of calculating a bad value that keymgr flags.. there are only 4 combinations total, so `4 / 2^256`.

Assuming we have 100M+ devices in service, with a 10 year lifespan, where keymgr does an operation once per millisecond (this is an extremely aggressive assumption), we would still only encounter a failure with ~`1/2^190` .  So I think it is safe to assume it is rather unlikely. 

I'm making an assumption that KMAC basically has an equal chance of spitting out all 0's / all 1's given arbitrary input.  As far as I can tell this seems to be an reasonable assumption to start.
