### ISSUE TITLE
[pwrmgr] Missing items from d2s / v2s

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#11452]
- [x] This particular feature is missing from the current `pwrmgr` test plan. #11773 
       https://docs.opentitan.org/hw/ip/pwrmgr/doc/index.html#rom-integrity-checks
- [x] Check that pwrmgr clock turn off is correctly emulated at block level #11812 
- [x] Improve documentation on escalation timeout #11455 
- [x] improve documentation on fsm sparse errors #11455 
- [x] Add the global_esc countermeasure label to the ports

**Comment by jdonjdon** [comment]
item1 is done #11773

**Comment by jdonjdon** [comment]
item 2 is done  #11812

**Comment by tjaychen** [comment]
@jdonjdon can you confirm the clock turn off is also handled now? if yes we can close this issue.
