### ISSUE TITLE
[flash_ctrl] D2S action items

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#11675]
- [x] Need to double check whether the prim integrity error are wired into the alerts sent over to ast
- [x] Update to lc_tx_test_true_strict/loose #11687
- [x] widen the disable signal, and feed LC_ESCALATE input to all sparse FSMs. #11687
- [x] Expand the usage of disable into more places #11687
- [x] Document the rationale for standard fault / fault status: some of these errors are handled on transactional boundaries since the electrical behavior on abrupt abort is not well known. Add this to the docs. #11687
- [x] Rename CTR.SHADOW to CTR.REDUN for consistency #11687
- [x] Double check if the other counters in this lcmgr module should also be hardened  #11687
- [x] Apply the PHY.FSM.SPARSE label in the RTL #11687
- [x] Clarify the assumptions about 1-bit error vs 2-bit error in flash, and why that has caused the separation between standard faults and custom faults #11687
- [x] Use prim_mubi_sync for flash_disable buffering instead of prim_buf #11687
- [x] Place tl_lc_gate in front of tlul_adapater_sram #11687
- [x] Add a function to convert between lc and mubi without needing a single point of failure. 
   - [x] Need to add assertions to check the assumptions needed to allow this type of conversion back and forth.
- [x] Add more description to FLASH_CTRL.MEM_EN.CONFIG.REDUN, specifically which register it impacts #11687
- [x] Add more description to the scramble countermeasure, such as what cipher is used, what overall scheme is used. #11687
- [x] update description for FLASH_CTRL.LC_CTRL.INTERSIG.MUBI #11896
- [x] update description for FLASH_CTRL.CTRL.CONFIG.REGWEN #11896
- [x] make the fields of FLASH_CTRL.INFO_REGIONS.CONFIG.SHADOW into MUBI #11907 
- [x] update description for FLASH_CTRL.BANK.CONFIG.SHADOW #11896
- [x] update label name for FLASH_CTRL.MEM_EN.CONFIG.REDUN to MEM_EN -> EXEC #11896
- [x] add more description to FLASH_CTRL.MEM.SCRAMBLE / FLASH_CTRL.MEM.INTEGRITY to clarify the different kinds of integrity #11896
- [x] update documentation on flash buffer to clarify what integrity protection is used #11896
- [x] look into hardening ctrl vs host arbitration to add protection against glitch attacks targeting the programming process (substitution attacks). Dual prim_arb would be a solution, different scrambling keys for different partitions would be another solution. #12217
- [x] look into detecting spurious ACKs in the arbitration mechanism.
- [x] other documentation clean-up, see [here] (https://docs.google.com/document/d/1m_45zzdrfS9eX9l9TIUTBtiS0kYJZbl92W5JVj1qSAY/edit?usp=sharing) #11896

**Comment by tjaychen** [comment]
@msfschaffner 
@cdgori 
@alphan 
@weicaiyang 
@moidx

**Comment by msfschaffner** [comment]
All items have been addressed. I also updated the spreadsheet accordingly.
