### ISSUE TITLE
[adc_ctrl] V2 review checklist

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#11744]
- [ ]  [Nigel]: update the doc, there are some templated text: https://docs.opentitan.org/hw/ip/adc_ctrl/doc/dv/index.html

- [x] [TimC]: Move fsm state enum to adc_crtrl_pkg for DV reuse.

Nigel: Covergroup related tasks:
- [ ] Consider adding covergoup to sample switching ADC back and forth between oneshot and continuous modes.
- [ ] Move the coverpoint sampling to scoreboard. Then maybe consider crossing adc_ctrl configuration coverpoints with interrupt status.
- [ ] Sample adc_ctrl power register mode in the scoreboard.
- [ ] Detect the interrupt + wakeup triggering while the fast clock was turned off
- [ ] Add coverbins for clock gating enabled conditions

- [ ]  [Nigel]: (could be post V2) Consider moving assertions to RTL or interface for reusability. 

- [x] [Cindy] check FSM csr assertion issue
   https://github.com/lowRISC/opentitan/pull/11783 
- [ ] [Nigel] Fix max outstanding low covergroup

- [x] [TimC] Gating V2 status. https://github.com/lowRISC/opentitan/issues/11354 
   - moved to future release

**Comment by NigelScales** [comment]
> Detect the interrupt + wakeup triggering while the fast clock was turned off
Currently only wakeup can occur when the clock is gated.

**Comment by NigelScales** [comment]
> [Nigel]: (could be post V2) Consider moving assertions to RTL or interface for reusability.

These are not amenable to incorporation in an interface in the current form so I think best to leave for later.

**Comment by cindychip** [comment]
Reached V2. Close this issue.
