### ISSUE TITLE
[bazel] support airgapped bazel builds

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#12090]
To facilitate building SW artifacts in airgapped environments (needed for nightly DV regressions) several external dependencies must be prepared offline, including:

- bazel and it's immediate dependencies (in a bazel `distdir`)
- all external bazel repos (fetched into the bazel `repository_cache`)
- all python wheels needed to generate bazel python rules with

To accomplish this, the following tasks must be completed:

- [x] a shell script should be developed to build the `distdir` and cache external repos into a provided directory (#11961)
- [x] all `git_repository` rules must be removed from the WORKSPACE, and replaced by their relative `http_archive` as these are not cached into the `repository_cache` (#11996)
- [x] all `git_repository` rules must be removed from any repositories we depend on, i.e., the `bazel_embedded` repository (luckily we already maintain a fork of this) ([lowRISC/bazel-embedded:#4](https://github.com/lowRISC/bazel-embedded/pull/4))
- [x] bazel `rules_python` must be forked and patched to support passing the `--find-links` flag with a specified path to the underlying `pip wheel` invocation ([lowRISC/rules_python:#1](https://github.com/lowRISC/rules_python/pull/1))
- [x] custom bazel repository rules must be written to pre-download / build all python requirements into wheels, and generate a hidden python-requirements.txt file on the fly that does not contain any VCS URLs so that this wheel cache can be directly consumed by invocations of the `pip_install` bazel rule (and transferred to an airgapped machine) (#12091)
