### ISSUE TITLE
[pattgen] V2 review checklist 

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#12117]
- [x] Break up the bins for the length and data covergroups.  (Create a localparam in the cov_if class to define how many mid-range bins should be created for the various cg types) 

- [x] Modify pattgen_op_cg coverpoints

- [x] Implement missing coverpoints

- [x] Make sure coverpoint names match the testplan name

- [ ] Roll-over test: set one of the counter configs to max value, then make sure the roll-over happens correctly. In the meantime, constraints other values to smaller values so the tests won’t run too long.
Please refer to issue: https://github.com/lowRISC/opentitan/issues/11791

- [x] Toggle coverage exclusion needed for cio_XYZ_tx_en_o lines (not V2 blocking)
        Hard coded and assertion constrained.

- [ ] Confirm RTL line coverage >90%. Check why Xcelium includes DV coverages.

**Comment by patel-madhuri** [comment]
@cindychip Can you please confirm with rasmus why xcelium includes DV coverages for pattgen? As I am not fully aware how the coverage is setup in regression

**Comment by cindychip** [comment]
Thanks @patel-madhuri, weicai has already followed up with Rasmus here: https://github.com/lowRISC/opentitan/issues/12292

**Comment by cindychip** [comment]
Hi @patel-madhuri thanks for the hardwork, here is the missing coverage item:
https://reports.opentitan.org/hw/ip/pattgen/dv/latest/results.html

1). Toggle coverage: 76.95% -> Could you help generate an xcelium coverage exclusion file to exclude the toggle coverage for this fixed I/O? https://github.com/lowRISC/opentitan/blob/master/hw/ip/pattgen/rtl/pattgen.sv#L71-L74

2). Expression coverage 85.17% -> seems like most of the failures coming from `u_pattgen_cov_if`. Looks like a DV component. Let check if we can do something to exclude that from coverage collection.
2).

**Comment by patel-madhuri** [comment]
Thank you Cindy for generating the exclusion file.

**Comment by patel-madhuri** [comment]
> * [x]  Break up the bins for the length and data covergroups.  (Create a localparam in the cov_if class to define how many mid-range bins should be created for the various cg types)
> * [x]  Modify pattgen_op_cg coverpoints
> * [x]  Implement missing coverpoints
> * [x]  Make sure coverpoint names match the testplan name
> * [x]  Roll-over test: set one of the counter configs to max value, then make sure the roll-over happens correctly. In the meantime, constraints other values to smaller values so the tests won’t run too long.
>   Please refer to issue: [Clarification regarding pattgen count rollover test #11791](https://github.com/lowRISC/opentitan/issues/11791)
> * [x]  Toggle coverage exclusion needed for cio_XYZ_tx_en_o lines (not V2 blocking)
>   Hard coded and assertion constrained.
> * [x]  Confirm RTL line coverage >90%. Check why Xcelium includes DV coverages.

**Comment by msfschaffner** [comment]
Closing since pattgen is at V2S now.
