### ISSUE TITLE
[spi_host] V2 review items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12130]
AIs from V2 review [notes](https://docs.google.com/document/d/1tY50_TgaGq6MQu0QH-By4DlHUC1fH4koxX0YTpRzK3o/edit#)

- [x] Viswa: Finalize decision on Winbond. Proposal: Change this to a V3.  Make a note on relevant issue: https://github.com/lowRISC/opentitan/issues/11292
- [x] Weicai/Dom: Can Winbond just contribute their BFM? -> Moved to https://github.com/lowRISC/opentitan/issues/13582
- [x] Viswa: Document changes to some structs in the DV document. 
- [x] Viswa: Update SPI_AGENT documentation to reflect changes to monitor, as needed.
- [x] Viswa/Martin/Weicai: Confirm that implemented covergroups match the intent of the testplan.  Update the testplan to reflect implementation
- [x] Viswa: Remove alert_cg (only one alert, integrity test, which is covered by toggle coverage)
- [x] Viswa: Identify with passthrough pins are not being exercised in toggle coverage (waiting for pending PR, confirm after landing).
- [x] Viswa: Create assertion check to confirm passthrough mode is functioning.
- [x] Martin/Weicai: Find a solution to #9932
- [x] Viswa: #7553: Document unused parameters in DV Doc
- [x] Martin/Viswa: resolve #5158
- [x] Viswa: Fix regression failures
- [x] Viswa: make all the code coverages are over 90%

**Comment by weicaiyang** [comment]
@visbaz LMK which items are done. I can check off them

**Comment by visbaz** [comment]
Viswa: Finalize decision on Winbond. Proposal: Change this to a V3. Make a note on relevant issue: SPI_HOST: winbond flash spi model  #11292
 Weicai/Dom: Can Winbond just contribute their BFM?
 Viswa: Document changes to some structs in the DV document.
 Viswa: Update SPI_AGENT documentation to reflect changes to monitor, as needed.
 Viswa/Martin/Weicai: Confirm that implemented covergroups match the intent of the testplan. Update the testplan to reflect implementation
 Viswa: Remove alert_cg (only one alert, integrity test, which is covered by toggle coverage)
 Viswa: Identify with passthrough pins are not being exercised in toggle coverage (waiting for pending PR, confirm after landing).

 Martin/Weicai: Find a solution to https://github.com/lowRISC/opentitan/issues/9932
 Viswa: https://github.com/lowRISC/opentitan/issues/7553: Document unused parameters in DV Doc

@weicaiyang Please cross check these items

**Comment by weicaiyang** [comment]
> Viswa: Finalize decision on Winbond. Proposal: Change this to a V3. Make a note on relevant issue: SPI_HOST: winbond flash spi model #11292 Weicai/Dom: Can Winbond just contribute their BFM? Viswa: Document changes to some structs in the DV document. Viswa: Update SPI_AGENT documentation to reflect changes to monitor, as needed. Viswa/Martin/Weicai: Confirm that implemented covergroups match the intent of the testplan. Update the testplan to reflect implementation Viswa: Remove alert_cg (only one alert, integrity test, which is covered by toggle coverage) Viswa: Identify with passthrough pins are not being exercised in toggle coverage (waiting for pending PR, confirm after landing).
> 
> Martin/Weicai: Find a solution to #9932 Viswa: #7553: Document unused parameters in DV Doc
> 
> @weicaiyang Please cross check these items

Done.

**Comment by visbaz** [comment]
@weicaiyang 
AI's 
Fix regression failures - done
https://github.com/lowRISC/opentitan/issues/5158 - As discussed over call and we understand that monitor and scoreboard will need fixes for this including development of new test for checking randon spien. 
I understand that this would further need  effort significantly and would require Ensilica management approval.

**Comment by weicaiyang** [comment]
all issues are addressed except this one. We do want to integrate winbond model into our TB. Let's implement this when someone takes over this block for V3.
  - Weicai/Dom: Can Winbond just contribute their BFM?
