### ISSUE TITLE
[SPI Device] Verification for the design changes

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12181]
We should verify these design changes.

- [x] Queue SW req of clr BUSY when active #11456
- [x] Add payload overflow interrupt #12086
- [x] Write enable (WREN) and write disable (WRDI) should be handled in hardware #11869

cc: @eunchan @domrizz0 

EDIT: all these features are verified and listed in coverage plan

**Comment by weicaiyang** [comment]
These bugs are found in pre_dv by @eunchan 
We should ensure the UVM test sequences can catch them

- [ ] #12382
- [ ] #12386
- [ ] #12388

**Comment by weicaiyang** [comment]
Done and updated the checklist
