### ISSUE TITLE
[fpga] Remove Nexysvideo files and update FPGA documentation

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12221]
It has been decide to deprecate the Nexysvideo board and drop support for it here #12212.

CI checks have already been removed in #12212, but there are still several files and documentation pages in the tree that refer to the Nexysvideo board. While not all of the files can be removed right away (e.g. Englishbreakfast still uses some software targets from nexysvideo), we should strive to clean this up soon-ish:

- [x] Remove hardware targets and SystemVerilog files related to NexysVideo, see #12821
- [ ] Remove software targets related to NexysVideo (SW targets that are reused for the CW305 should probably be renamed appropriately), see also #13008
- [x] Remove/rename OpenOCD configuration files (there appears to be no config for the CW310 at the moment under `util/openocd/board/`), see #10625
- [x] Update the FPGA documentation here https://docs.opentitan.org/doc/getting_started/setup_fpga/ , see #12821
- [x] Update info about how to get a CW310 board (https://github.com/lowRISC/opentitan/issues/12185), see #12821

**Comment by jprendes** [comment]
I'll take a look into this issue.

**Comment by vogelpi** [comment]
Hi @jprendes ,
I've just opened PR #12821 which addresses most of the items listed above. What's missing is:
- Remove software targets related to NexysVideo (SW targets that are reused for the CW305 should probably be renamed appropriately)

As briefly discussed today, it would be great if you could take care of this at some point. Thanks!
