### ISSUE TITLE
[lc_ctrl] D3 Review Opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12822]
- [x] Move the lc_tx_t / mubi4 assertions to the package. #12823
- [x] update docs to make clear a read will return all 0s if the interface is not successfully claimed #12823
- [x] Fix “before proceeding with step 6.” -> “before proceeding with step 7.” #12823
- [x] https://github.com/lowRISC/opentitan/issues/12232, @matutem Do we still need this? -> it has been determined that the issue will be resolved at V3, possibly by adding an appropriate assertion to OTP. Hence no further changes are needed for LC.
- [x] update the OTP vendor DIFs to return kDifUnavaible is interface not claimed (#12843)
- [x] Split up dif_lc_ctrl_transition() into “configure” and “initiate transition” DIFs to give programmer a chance to read back configurations before initiating the transition (#12879)
