### ISSUE TITLE
[adc_ctrl] D3 Opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12954]
- [x] Return from continuous scan to periodic scan can be emulated by SW, but it would be better to handle this in HW -> open an issue to track this as a future enhancement. Also remove this code section here #13725 : https://github.com/lowRISC/opentitan/blob/bb1701c2872d1ee23e0b41a3e27d0a3c08174559/hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv#L152-L160
- [x] Ideally we should split the WE check error condition from bus integrity and create a separate CM label for it. Open an issue to track this #13726.
- [x] Fix a couple of documentation nits: https://github.com/lowRISC/opentitan/pull/12949, including the redundant bit slices in register descriptions: https://github.com/lowRISC/opentitan/blob/bb1701c2872d1ee23e0b41a3e27d0a3c08174559/hw/ip/adc_ctrl/data/adc_ctrl.hjson#L154-L158
- [x] Add a documentation section that explains the ADC_CTRL <-> ADC interface (wavehjson diagram) #13765
- [x] Make [adc_intr_status](https://docs.opentitan.org/hw/ip/adc_ctrl/doc/index.html#Reg_adc_intr_status) field names more generic #13765
- [x] rename “debug_cable” interrupt to something more generic #13765
- [x] ~Highlight in the docs that matches are 2D and filter hit conditions from both channels are ANDed together~ For this one, fix the RTL such that a 2D hit is not always required.  It is required only if both filters are enabled, otherwise, only the enabled filter takes effect. #13765
- [x] Reorganize programmer’s guide section #13765
- [x] Add a use-case section that uses the debug cable detection (IRQ names above, plus the 2D diagram) as a specific use case for ADC_CTRL #13765
