### ISSUE TITLE
[tool] Add support for Verible open source verilog style linting

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#1342]
This issue tracks the addition of [Verible style-lint](https://github.com/google/verible) to our utility tools and CI. Verible style lint is an open-source style linter which implements rules that are very close to the [lowRISC coding style guide](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md).

- [x] add build script. note: this requires the bazel build system and GCC7, so it is not planned to make this a mandatory tool requirement for the project.
- [x] add run script, potentially with file exclusions to work around current tool issues.
- [x] integrate with edalize: https://github.com/olofk/edalize/pull/100
- [x] resolve blocking issues from Verible: https://github.com/google/verible/issues/128, to a lesser extent also https://github.com/google/verible/issues/133
- [x] integrate into existing makefile-based lint flow (#1906)
- [x] integrate into DVSIM (#1727)
- [x] add configuration file option to FuseSoC / Edalize (https://github.com/google/verible/issues/133)
- [x] find a waiver solution that works for our flow: https://github.com/google/verible/issues/105
- [x] ~~decide what to do with lint errors in generated files~~ -> we have a way to waive them now, if needed
- [x] remove experimental shell scripts related to Verible in `util/`
- [x] update documentation and explain how Verible can be installed as part of the OT tooling
- [x] integrate into CI
- [ ] extend DVSIM to support structured output from Verible (#1727, https://github.com/google/verible/issues/257)

Also look at the related Ibex issue https://github.com/lowRISC/ibex/issues/579 which is a good testbed for this change, since the codebase is much smaller.

**Comment by msfschaffner** [comment]
@fangism for visibility

**Comment by sjgitty** [comment]
Related to #56

**Comment by imphil** [comment]
@msfschaffner can you update this issue description which verible issues which are blocking us making progress?

**Comment by msfschaffner** [comment]
Updated. The main two blockers are google/verible#105 and google/verible#128, the rest should be relatively straightforward once those features are in.

**Comment by msfschaffner** [comment]
Forgot to add this one here to the list of potentially blocking issues due to style discrepancies:

https://github.com/google/verible/issues/133

The rules affected are few, for instance the style of `localparam` / `parameter` is slightly different from the OT style. There are ways around this by completely disabling the rules, but configurable rules would of course be more user friendly.

**Comment by imphil** [comment]
Verible lint is now enforced in Ibex, all blockers have been removed; the ot branch in lowrisc/edalize (which we use in OT as well) has necessary patches to enable waivers (https://github.com/olofk/edalize/pull/178).

**Comment by msfschaffner** [comment]
It looks like we are close to being able to enforce this on the master branch of opentitan as well:
https://reports.opentitan.org/hw/top_earlgrey/lint/veriblelint/summary.html
I'll take a crack at things on the opentitan side later this week.

**Comment by imphil** [comment]
@msfschaffner We probably can consider that done? The structured output isn't a blocker.

**Comment by msfschaffner** [comment]
Yeah let's close this issue down. I think the structured output is mentioned in the dvsim issue as well, so we still have it tracked somewhere.
