### ISSUE TITLE
[pwm] V2 TODO lists

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#13476]
Based on the V2 review, here are the missing items from pwm V2 checklist:

- [x] Dhara: please check why pwm_env_pkg functional coverage is low. For example, it only covers channel0.
      - Moved to post v2 item: https://github.com/lowRISC/opentitan/issues/13588   
- [x] Cindy: fix max_outstanding tlul coverage.
- [x] Martin: please help check output `cio_pwm_en_o` is tied to certain value, as it shows 0% in toggle coverage.
- [x] Regarding cio_pwm_en_o: Write toggle coverage exception for the cio_pwm_en_o port. 
      - Moved to post v2 item: https://github.com/lowRISC/opentitan/issues/13588
- [x] Cindy: review and check CI failure for this PR: https://github.com/lowRISC/opentitan/pull/13439
- [x] Martin: help check issue: https://github.com/lowRISC/opentitan/issues/9999
      - Moved to post v2 item: https://github.com/lowRISC/opentitan/issues/13588   
- [x] Dhara: check if we can reproduce this issue: https://github.com/lowRISC/opentitan/issues/9830
- [x] Muqing: help fix this issue: https://github.com/lowRISC/opentitan/issues/13434
- [x] Dhara: help add a functional coverage for this issue: https://github.com/lowRISC/opentitan/issues/13434
- [x] Cindy: fix nightly regression dashboard unmapped tests.

Thanks everyone for joining the meeting.
@sriyerg @jdonjdon @weicaiyang

**Comment by martin-lueker** [comment]
Re:  "check output cio_pwm_en_o is tied to certain value, as it shows 0% in toggle coverage."  

This is confirmed [see here](https://github.com/lowRISC/opentitan/blob/9c280944cd69aa74e2b98c0d572e232582bcbf87/hw/ip/pwm/rtl/pwm.sv#L67)

@dharanendrak, or @cindychip could you please write an exception here?

**Comment by dharanendrak** [comment]
@cindychip 
" please check why pwm_env_pkg functional coverage is low. For example, it only covers channel0."
I have updated these changes. I hope these changes will pick in next regressions.

https://github.com/lowRISC/opentitan/pull/13512

**Comment by cindychip** [comment]
> > Re: "check output cio_pwm_en_o is tied to certain value, as it shows 0% in toggle coverage."
> > This is confirmed [see here](https://github.com/lowRISC/opentitan/blob/9c280944cd69aa74e2b98c0d572e232582bcbf87/hw/ip/pwm/rtl/pwm.sv#L67)
> > @dharanendrak, or @cindychip could you please write an exception here?
> 
> Strange - VCS reports tie-offs as unreachable. See `cio_tx_en_o` in case of UART: https://reports.opentitan.org/hw/ip/uart/dv/latest/cov_report/mod42.html#Toggle
> 
> I would hope Xcelium could also do this level of analysis. Could we be missing a switch to get tie-offs automatically reported as unreachable? There could be an arbitrarily large number of cases like these (across all IPs verified with Xcelium) which may increase our coverage review overhead.

Thanks Sri, let me file an issue and ask if Xcelium AE can help take a look at it.
