### ISSUE TITLE
[bazel] Add support for assembling images at different offsets

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#13511]
`opentitantool` already supports image assembly as a standalone operation or as a part of the `bootstrap` command.

We need to enhance our bazel macros and rules for test cases like
- Valid ROM\_EXT at slot b, i.e. the ROM\_EXT image should be at offset `flash_size / 2` in the binary file, or
- Valid ROM\_EXT at slot a and valid owner image at slot b.

@cfrantz @arunthomas

**Comment by timothytrippel** [comment]
# Tasks

- [ ] Add Bazel rules/macros for creating a single flash binary / VMEM with multiple slots / stages filled 
- [ ] cleanup existing [bare metal boot test](https://github.com/lowRISC/opentitan/blob/543297d5de3a8275040112fde97241651f3aec7d/sw/device/silicon_owner/bare_metal/BUILD#L107)
- [ ] Update above Bazel rules/macros for creating single DV sim SW logging database from multiple files
- [ ] Update DV testbench to be able to backdoor load both flash banks from one VMEM file

**Comment by timothytrippel** [comment]
> * pdate above Bazel rules/macros for creating single DV sim SW logging database from multiple files
> * [ ]  Update DV testbench to be able to backdoor load both flash banks from one VMEM file

I have split off the last two tasks into a separate issue, and will close this.
