### ISSUE TITLE
[alert_handler] D3 review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#13576]
- [x] Check whether we can remove the TODO item [here](https://github.com/lowRISC/opentitan/blob/564f8fe63ef37bbed2ce91c0485d9bebdd9a8196/hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv#L61-L71). If not, make it an icebox. #13593
- [x] Some lint issues due to common prims, Michael is fixing this now
- [x] Create an issue to discuss options for downcount with duplication count #13578 #13591.
- [x] Figure out what needs to be done to close https://github.com/lowRISC/opentitan/issues/6675 -> pending items are either SW documentation items, or backend constraints. they should not gate D3 signoff.
