### ISSUE TITLE
[alert_handler] V2S TODO lists

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#13589]
- [x] [Cindy] Create PR for V2S status update.
- [x] [Cindy] clean up manually added regwen covergroup
- [x] [Cindy] update testplan for sec_cm_esc_rx_intersig_bkgn_chk, and mention that it’s not applicable as it’s tested in chip-level
- [x] [Weicai] https://github.com/lowRISC/opentitan/issues/47 Please check if we can close this.
- [x] [Cindy] wait for this issue to close: https://github.com/lowRISC/opentitan/issues/13578 
- [x] [Cindy] Add exclusions for FSM states to invalid error states (they are covered in FPV)

**Comment by cindychip** [comment]
All TODOs are implemented.
