### ISSUE TITLE
[sram_ctrl] D3 review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#13676]
- [x] Review tlul_adapater_sram parameters (msf / tim) #7462, #13771
- [x] Style nit: sram_ctrl.sv: 146, input port with direct logic expression instead put combinational logic elsewhere with a new signal name to feed into the input port #13677
- [x] Style nit: sram_ctrl.sv: 187: Enclose unary OR in parentheses (more import when change to bitwise OR from above it applied) #13677
- [x] Style nit: Sram_ctrl.sv: 179, 185: Use of || logic OR where style guide states bitwise | OR should be used. #13677
- [x] Doc: the programmer’s guide should probably recommend spinning on STATUS.SCR_KEY_VALID when requesting a new key, since the PC value on a watchdog crash will likely be the only clue about what happened if it makes no progress (if someone forgets to initialize the CSRNG and EDN). #13677
- [x] Review rom for usage of sram clearing / init: [main sram](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/mask_rom/mask_rom_start.S#L235) and [retention sram](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/lib/drivers/retention_sram.c#L46)

**Comment by a-will** [comment]
The ROM chooses to block on the SRAM accesses instead of checking STATUS.SCR_KEY_VALID. This is okay, since we know for sure that we set up the CSRNG and EDN before changing keys. It's a recommendation for more debuggable user code, not a "should" or "must" ;)

**Comment by msfschaffner** [comment]
Cool, thanks for checking.
