### ISSUE TITLE
[Tracking][DIF] UART

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#1386]
This issue is intended to track the development of the UART Device Interface Functions (DIF) library.

- [x] DIF library landed  (#1111)
- [x] In-tree "driver" uses DIF library (#1111)
- [x] Unit tests (#1477)
- [x] DV extensions (no longer relevant)

The UART DIF library is being implemented by @silvestrst 

The UART DIF library was landed in #1111 (which included changes to the in-tree uart "driver"), and unit tests were landed in #1477, but it is not yet used by DV.

**Comment by silvestrst** [comment]
@lenary could you please mark unit tests as done and also remove "(no PR yet)". Not sure in what state DV is. Thanks.

**Comment by silvestrst** [comment]
It is used in DV testing, I guess this can be closed?
