### ISSUE TITLE
[Tracking][DIF] PLIC

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#1387]
This issue is intended to track the development of the PLIC Device Interface Functions (DIF) library.

- [x] DIF library landed (#1282)
- [x] In-tree "driver" uses DIF library (no in-tree driver)
- [x] Unit tests (#1641)
- [x] DV extensions (no longer relevant)

The PLIC DIF library is being implemented by @silvestrst

**Comment by silvestrst** [comment]
@lenary I can't seem to edit the issue description, but there are some PLIC RTL changes coming, see #1491 , so the corresponding DIF will have to be refactored accordingly.

**Comment by silvestrst** [comment]
In-tree "driver" uses DIF library - not relevant, we won't have PLIC driver in OT proper, it will be Tock driver based on DIF PLIC.

Unittests are merged, DIF is merged, DV uses DIF PLIC in uart test. Please update this issue.

**Comment by lenary** [comment]
Issue updated, but I think as soon as we start doing signoff meetings, we'll move to the checklist files instead. I'll keep this open until we have a DIF checklist for PLIC.
