### ISSUE TITLE
[Tracking][DIF] SPI

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#1388]
This issue is intended to track the development of the SPI Device Interface Functions (DIF) library.

- [ ] DIF library landed (#1135)
- [ ] In-tree "driver" uses DIF library (#1135)
- [ ] Unit tests (no PR yet)
- [ ] DV extensions (no PR yet)

The SPI DIF library is being implemented by @mcy

**Comment by tjaychen** [comment]
should we just...close this? 
all the tasks are done arent they?

**Comment by a-will** [comment]
The initial tasks might be, but I'm doing the DIF for the TPM and flash/pass-through modes.

**Comment by tjaychen** [comment]
o that's right...i kind of forgot how diverse the feature set is...

**Comment by moidx** [comment]
Closing as obsolete
