### ISSUE TITLE
[Tracking][DIF] GPIO

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#1389]
This issue is intended to track the development of the GPIO Device Interface Functions (DIF) library.

- [x] DIF library landed (#1254)
- [x] ~~In-tree "driver" uses DIF library~~ All in-tree code uses DIF library (#1254)
- [x] Unit tests (#1966) 
- [ ] DV extensions (no PR yet)

The GPIO DIF library is being implemented by @alphan

**Comment by alphan** [comment]
@lenary Thank you for creating this issue!

**Comment by lenary** [comment]
The GPIO DIF landed yesterday, in (#1254).

**Comment by alphan** [comment]
PR for tests: #1966 (using a comment because cannot edit the issue).

**Comment by tjaychen** [comment]
should we just close this? all the tasks are done arent they?
