### ISSUE TITLE
[Tracking][DIF] HMAC

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#1390]
This issue is intended to track the development of the HMAC Device Interface Functions (DIF) library.

- [ ] DIF library landed (#1320)
- [ ] In-tree "driver" uses DIF library (potentially in #1320)
- [ ] Unit tests (no PR yet)
- [ ] DV extensions (no PR yet)

The HMAC DIF library is being implemented by @jon-flatley

**Comment by moidx** [comment]
Closing as obsolete
