### ISSUE TITLE
[sensor_ctrl] D3 review opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14369]
- [x] Remove unnecessary portions of the documentation #14723
- [x] Block D3 on #13366, #14721
- [x] Naming inconsistencies between sensor_ctrl and sensor ctrl #14723
- [x] Uses bit_toggle_t as a boolean #14723

**Comment by msfschaffner** [comment]
@tjaychen are there any other pending `sensor_ctrl` changes that should be linked here? otherwise I think we are good to merge https://github.com/lowRISC/opentitan/pull/14725.

**Comment by tjaychen** [comment]
so jacob's change on ast_init_done will have a small change on d3. 
do you want to wait for that? so that technically we can say no more change after d3?

**Comment by msfschaffner** [comment]
this is going to be a port change, right? 
from a checklist point of view, it is fine to fix bugs after D3 - but port changes for features / enhancements we already know of prior to D3 should probably also be merged before D3.
so I would say let's wait for that one before we move to D3, since it will probably be landing soon.

**Comment by msfschaffner** [comment]
This can now closed, since the ast_init_done alignment in https://github.com/lowRISC/opentitan/pull/14798 has been merged.
