### ISSUE TITLE
[flash_ctrl] V2 review checklist

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#14527]
[Review notes](https://docs.google.com/document/d/1jBv_oWz51irjAF5LuISyY3nII_5QDxtquh0UMnSgeHg/edit)

- [x] Add covergroup for new design delta changes
- [x] Clean up Xcelium stuff inside flash_ctrl directory
- [x] #14433
- [x] [Tim] Update the naming from ECC to ICV in doc
- [x] Update coverage sample point to capture rd_err right
- [x] Add a test to cover lc_escalate_en_i
- [x] Add a link to a note to list all modules that are commonly excluded (Updated at the[ V2 note template](https://docs.google.com/document/d/1_y2g5hrqNgUxZy_pH8X9x1rgsIZYHjYhBt_38nm5EUU/edit))

**Comment by jdonjdon** [comment]
@tjaychen Can you update item#4?
Regarding item#3, do you want me to overwrite from TB using defparam?

**Comment by tjaychen** [comment]
ah i think if you tried that, our style lint will immediately block you from merging the PR...
if you want, you could try to push a PR that adds a plusarg for that, what do you think? You might see a lot of test fall out once you flip the feature on.

**Comment by jdonjdon** [comment]
item1:  #14641 
item2:  #14672 
item3:  #14745 
item5:  #14641 
item6: #14740

**Comment by tjaychen** [comment]
sorry let me look at the documentation stuff today.

**Comment by weicaiyang** [comment]
@jdonjdon looks like we can sign off the V2 now. Please make a PR to update 2 files like this one https://github.com/lowRISC/opentitan/pull/9925

**Comment by jdonjdon** [comment]
> @jdonjdon looks like we can sign off the V2 now. Please make a PR to update 2 files like this one #9925

Thanks @weicaiyang, PR is created here #14915
