### ISSUE TITLE
[rom-e2e] add selected V2 ROM E2E tests to DV sim nightly regression 

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#14634]
We want to run some (as many as possible?) ROM E2E tests in DV sim nightly regressions. Since these tests take a long time to run in sim ([1hr+](https://github.com/lowRISC/opentitan/pull/14535#discussion_r953323544)) we need to:

- [x] decide which tests from the [ROM E2E testplan](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/data/rom_testplan.hjson?q=rom_testplan&ss=opentitan%2Fopentitan) we want to run in DV sim
    - we have decided to **_definitely_** run all [P1 tests](https://github.com/orgs/lowRISC/projects/13/views/20), and
    - run all P2 tests in a best effort manner 
- [x] update the test point tags in the [ROM E2E testplan](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/data/rom_testplan.hjson?q=rom_testplan&ss=opentitan%2Fopentitan) to indicate so
- [x] enable passing OTP seeds to Bazel on command line (to support dvsim building OTP images with Bazel with different seeds; #16052)
- [x] enable passing custom OTP image (built by bazel) to DV testbench (instead of using just the 5 prebuilt ones; #16053)
- [x] enable bypassing loading of SW logging database files in DV testbenchfor tests that do not produce such, e.g., tests that load corrupted images (#16347)
- [x] update dvsim's `sim.mk` file to only copy over a test image's ELF file if one exists, as some tests that load corrupted VMEM's do not have a matching ELF (#16347)
- [x] update the Bazel BUILD targets and DV sim nightly regression [configuration file](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/dv/chip_sim_cfg.hjson?q=chip_sim_cfg.hjson&ss=opentitan%2Fopentitan), and potentially write an SV sequence, for each test below to enable building and running said test in DV
    - [x] Tests that must work in DV for V2:
        - [x] #14274 (added in #16096)
        - [x] #14270 (added in #16054)
        - [x] #14474 (added in #16348 and #16396)
        - [x] #14477 (added in #16335)
        - [x] #14493 (adding #16451)
    - [x] Additional tests we have gotten running in DV as well:
        - [x] rom_e2e_smoke
        - [x] rom_e2e_static_critical 
        - [x] #14501 

Note, to accomplish the above assumes all ROM tests have already been developed for some target other than DV sim (e.g., FPGA).

**Comment by alphan** [comment]
@moidx @alphan We should go through the regular bootstrap path instead of backdoor loading for at least one test to cover spi/pinmux/pins/flash/etc.

**Comment by timothytrippel** [comment]
> @moidx @alphan We should go through the regular bootstrap path instead of backdoor loading for at least one test to cover spi/pinmux/pins/flash/etc.

we will probably need to address #11678 to do so.

**Comment by timothytrippel** [comment]
CC: @a-will
