### ISSUE TITLE
[chip-test] chip_sw_power_max_load

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14814]
### Test point name

[chip_sw_power_max_load](https://github.com/lowRISC/opentitan/blob/954f0de3bef19ee3080e9dd71dfc647a9c93c779/hw/top_earlgrey/data/chip_testplan.hjson#L3003)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@tjaychen @msf for HW, @timothytrippel @sriyer for DV and concurrency framework

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by timothytrippel** [comment]
See #14095 for more details.

**Comment by timothytrippel** [comment]
# Test Checklist (WIP):

## (Task 0) Main:
- [x] configure GPIO pin (mapped to IOA2 pad) as output (#15717)
- [x] configure adc_ctrl to continuously sample (but do not enable) (#15717)
- [ ] configure entropy complex (beyond what test ROM does) to:
    - [ ] enable all entropy_src health tests (but keep IRQs disabled)
    - [ ] configure both EDNs (0 and 1) in auto request mode with appropriate MAX_NUM_REQS_BETWEEN_RESEEDS parameter to keep CSRNG always active
- [ ] configure crypto blocks (but do not start operations)
    - [ ] AES
         - CTR or CBC mode
         - 256-bit key
         - manual operation (should allow easier alignment of power-hungry operations)
         - set static key
         - max prng reseed rate
    - [ ] HMAC
         - HMAC+SHA mode
         - set static key
    - [ ] KMAC
         - configure in KMAC+cSHAKE256 mode
         - set static prefix and key
- [ ] configure digital communication blocks
    - [ ] configure all 3 UARTs but do not enable
         - in TX mode with system loopback enabled
         - with parity enabled
         - with max buadrate
    - [ ] configure all 3 I2Cs but do not enable
         - in host/TX mode
         - max data rate
    - [ ] configure spi_device and spi_host0 in passthrough mode
    - [ ] configure USB device
- [ ] configure flash scrambling
 
 ## (Task 1) Ongoing Entropy Complex Operations:
- [ ] keep both EDN reseed command FIFOs full
- [ ] keep both EDN generate command FIFOs full
- [ ] continuously send reseed/generate/update commands to CSRNG SW application interface

## (Task 2) Block Loading Operations:
- [ ] write data to AES FIFO
- [ ] write data to HMAC FIFO
- [ ] write data to KMAC FIFO
- [ ] write program/data to OTBN IMEM/DMEM
- [ ] write data to all three UART FIFOs
- [ ] write data to all three I2C FIFOs

## (Task 3) Activate All Blocks
- [ ] start OTBN operations
- [ ] start KMAC operations
- [ ] start AES operations
- [ ] start HMAC operations
- [ ] start I2C operations
- [ ] start UART operations
- [ ] set GPIO 0 high (to indicate max power state)
- [ ] wait until complete
- [ ] set GPIO 0 lot (to indicate out of max power state)

## Internal Test Parameters:
- adc_ctrl power-up time
- internal vs. external clock source

## OTP Test Parameters:
- turn on icache

## (External) Host Side Test Component:
- [ ] drive spi_device during time of max power consumption

**Comment by tjaychen** [comment]
@timothytrippel @arunthomas based on what we discussed, we're going to lower the priority of this test to M3 and also V3 (so it doesn't pop up on the dashboard).

Let me know if you disagree.

**Comment by timothytrippel** [comment]
Making note here of potential future optimizations / areas of investigation. These are not immediately required for this test, but may be revisited in later on.

- [ ] driving usbdev
- [ ] explore clock gating effects on power swings
- [ ] triggering other memory controller operations?  (OTP / SRAM operations)
