### ISSUE TITLE
flash TODO

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15]
- [x] make a prim_arb_priority module and replace flash_mp region matching logic
- [x] move hello_flash to flash_sanity, refactor the test to be more modular
- [x] sync the flash drivers between boot_rom and lib
- [x] change interrupts to edge detection
- [x] update region registers to be lockable
