### ISSUE TITLE
[i2c] remaining DV tasks

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15170]
This issue tracks the various i2c dv related issues as well as some of the milestone items yet to be completed

Outstanding DV items for i2c_host
- [x] Fix test bench connection setup discovered in #15066 
- [x] ensure there are test vectors available #14961 
- [x] clean-up i2c host mode regressions and fix existing failures #16889
- [ ] review current testing for scl / sda interference, instability and clock stretching 
- [ ] test i2c loopback mode
- [ ] complete verification of i2c host mode
- [ ] Add custom verbosity controls #15129 
- [ ] address i2c agent issues discovered in #14825 
- [ ] ensure there are test vectors available #15131

Outstanding DV items for i2c target
- [x] Create test vectors for #14949 
- [x] add basic verification for read / write #16189
- [x] add verification for write stretch #16304 
- [x] add verification for read stretch #16304 
- [x] add verification for mixed stretching #16304 
- [x] add verification for tx_empty / acq_full interrupts #16304
- [x] add verification for transaction complete interrupts #16399 
- [x] add verification for other interrupts #16399 #16470
- [x] add verification for fifo reset #16803 #16826 
- [ ] add verification for unconditional software stretch

**Comment by tjaychen** [comment]
@drewmacrae 
@a-will 
was there anything else you guys noticed that i've missed? 
I'll have to file a separate design tracking one.

**Comment by drewmacrae** [comment]
I think this covers all the issues we talked about that are important to the I2C block as specified. There are a number of corner cases that could become important in multihost systems where OpenTitan's I2C is acting as a host, but given that's not supported, I'll try to remember that they're moot.

**Comment by a-will** [comment]
There aren't any other DV-related ones I'm aware of. Thanks for putting together the list!

**Comment by tjaychen** [comment]
@jdonjdon we might need to split this issue up a bit for what makes sense for M2 and what makes sense for M3.

**Comment by jdonjdon** [comment]
Let me review and add comment here

**Comment by tjaychen** [comment]
@jdonjdon but does that mean verification of target mode is not included? 
I think we are planning basic verification of target mode right + maybe clock stretching?

**Comment by tjaychen** [comment]
for target verification, i think after smoke, it's probably good to verify the basic operational interrupts + stretching.  They basically come together. Let me double check if the spec has laid this out clearly, if not we can quickly discuss.

**Comment by tjaychen** [comment]
@jdonjdon this all sounds good to me.
I think we should move this item to M3. Most of the items are not meant to be completed by M2.

Let me do that for now, please let me know if you object.

**Comment by crteja** [comment]
Estimate for M2.5
> estimate 16

**Comment by a-will** [comment]
@GregAC I believe that concept no longer applies. Likely removed in a subsequent PR: https://github.com/lowRISC/opentitan/pull/16647/files#diff-7eec485beab9f6c3633e4b003f66adc7b1da48e7ac12c903fc782fc23277af09L795-L807

**Comment by marnovandermaas** [comment]
I am going to close this issue noting the reasons why each open point is no longer relevant below.

> This issue tracks the various i2c dv related issues as well as some of the milestone items yet to be completed
> 
> Outstanding DV items for i2c_host
> 
>     * [x]  Fix test bench connection setup discovered in [[i2c/dv] Incorrect values presented on cio_sda_i and cio_sda_o #15066](https://github.com/lowRISC/opentitan/issues/15066)
> 
>     * [x]  ensure there are test vectors available [[i2c] scl glitch on start #14961](https://github.com/lowRISC/opentitan/issues/14961)
> 
>     * [x]  clean-up i2c host mode regressions and fix existing failures [[i2c,dv] various minor regression fix #16889](https://github.com/lowRISC/opentitan/pull/16889)
> 
>     * [ ]  review current testing for scl / sda interference, instability and clock stretching
Split out into another issue: https://github.com/lowRISC/opentitan/issues/17835
> 
>     * [ ]  test i2c loopback mode
Not necessary as per this comment: https://github.com/lowRISC/opentitan/issues/17458#issuecomment-1481313016
> 
>     * [ ]  complete verification of i2c host mode
This is tracked in various other issues including: https://github.com/lowRISC/opentitan/issues/17890
> 
>     * [ ]  Add custom verbosity controls [[i2c/dv] Add option to control i2c agent verbosity #15129](https://github.com/lowRISC/opentitan/issues/15129)
This has another issue assigned to it and is labeled as backlog for M2.5
> 
>     * [ ]  address i2c agent issues discovered in [[i2c/dv] issues with i2c_agent #14825](https://github.com/lowRISC/opentitan/issues/14825)
Another issue assigned and is labeled as backlog for M2.5
> 
>     * [ ]  ensure there are test vectors available [[i2c] sda interference during host enable #15131](https://github.com/lowRISC/opentitan/issues/15131)
Another issue assigned and is labeled as backlog for M2.5
> 
> 
> Outstanding DV items for i2c target
> 
>     * [x]  Create test vectors for [I2C may not respond properly to a repeated start condition #14949](https://github.com/lowRISC/opentitan/issues/14949)
> 
>     * [x]  add basic verification for read / write [[i2c,dv] target smoke test #16189](https://github.com/lowRISC/opentitan/pull/16189)
> 
>     * [x]  add verification for write stretch [[i2c,dv] target mode clock stretch tests #16304](https://github.com/lowRISC/opentitan/pull/16304)
> 
>     * [x]  add verification for read stretch [[i2c,dv] target mode clock stretch tests #16304](https://github.com/lowRISC/opentitan/pull/16304)
> 
>     * [x]  add verification for mixed stretching [[i2c,dv] target mode clock stretch tests #16304](https://github.com/lowRISC/opentitan/pull/16304)
> 
>     * [x]  add verification for tx_empty / acq_full interrupts [[i2c,dv] target mode clock stretch tests #16304](https://github.com/lowRISC/opentitan/pull/16304)
> 
>     * [x]  add verification for transaction complete interrupts [[dv,i2c] interrupt test part1 #16399](https://github.com/lowRISC/opentitan/pull/16399)
> 
>     * [x]  add verification for other interrupts [[dv,i2c] interrupt test part1 #16399](https://github.com/lowRISC/opentitan/pull/16399) [[i2c,dv] interrupt test part2 #16470](https://github.com/lowRISC/opentitan/pull/16470)
> 
>     * [x]  add verification for fifo reset [[i2c,dv] target_acq_fifo_reset #16803](https://github.com/lowRISC/opentitan/pull/16803) [[i2c,dv] tx fifo reset test #16826](https://github.com/lowRISC/opentitan/pull/16826)
> 
>     * [ ]  add verification for unconditional software stretch
Not necessary as per this comment: https://github.com/lowRISC/opentitan/issues/15170#issuecomment-1498072696
