### ISSUE TITLE
[dv/kmac] V2S TODO items

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#15207]
- [x] [Cindy] Rerun UNR:
       PR: https://github.com/lowRISC/opentitan/pull/15228
       https://github.com/lowRISC/opentitan/pull/15265
- [x] [Cindy] Re-visit coverage results
- [x] [Cindy] Address the unmapped test
https://github.com/lowRISC/opentitan/pull/15311

Resolve issues:

- [x] [cindy] [[kmac] Entropy ready bit error](https://github.com/lowRISC/opentitan/issues/15140) and [[kmac] Report entropy error on app interface](https://github.com/lowRISC/opentitan/issues/10933)
- [x] [cindy] [[dv/kmac] Make sure kmac does not hang when sideload key valid bit is dropped](https://github.com/lowRISC/opentitan/issues/14596)
Change this issue to M3 because if the sideload key dropped during operation, keymgr will trigger escalation in system level.
- [x] [Eli] follow up [[kmac] SCA hardening follow-up tasks](https://github.com/lowRISC/opentitan/issues/12323) 
- [x] [cindy] follow up [[hw/kmac] key integrity checks](https://github.com/lowRISC/opentitan/issues/6546), it seems not necessary to be a M2 issue

**Comment by eunchan** [comment]
Reviewfs the KMAC SCA issue. No need to update the design (not a must item).

**Comment by cindychip** [comment]
> Reviewed the KMAC SCA issue. No need to update the design (not a must item).

Thanks Eli for the update

**Comment by cindychip** [comment]
Unmasked coverage:
https://reports.opentitan.org/hw/ip/kmac_unmasked/dv/latest/report.html
![image](https://user-images.githubusercontent.com/11466553/194677311-1734199a-3fab-4b41-8a7c-0172c733f7ba.png)

Masked coverage:
![image](https://user-images.githubusercontent.com/11466553/194731304-dfb127f7-a77a-400a-875b-b6a8495c6c8f.png)

https://reports.opentitan.org/hw/ip/kmac_masked/dv/latest/report.html
