### ISSUE TITLE
[flash_ctrl] V2S review checklist

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#15340]
- [x] Add designated test for flash_ctrl.CTRL_REGWEN (#15348)
- [x] Check macro_error is covered in closed source test
- [x] [Tim] Check rma process doesn't violate closed source endurance time limit (#15633)
- [x] Add functional coverage for std_fault (#15448)
- [x] Add functional coverage and test for fault_status (not triggered by sw transaction) (#15498 )
- [x] Add a test to create rma wipe process failure (#15391)
- [x] [Tim] Check whether chip escalation process is not affected by any flash's catastrophic failure (#15635)
- [x] Improve group coverage 90%+

**Comment by jdonjdon** [comment]
FPV_SEC_CM is clean with #15416

**Comment by jdonjdon** [comment]
item2: macro_error  is used in the closed source. There might be more updated based on closed source implementations.

**Comment by jdonjdon** [comment]
![image](https://user-images.githubusercontent.com/99843637/198900993-edaa6899-9896-4c89-966f-d4f96843a7af.png)
With the PR TBD, this is the latest numbers.
