### ISSUE TITLE
[otbn,dv] V2S Review Checklist

### ISSUE THREAD

**Issue by ctopal** [lowRISC/opentitan#15408]
- [x] Documentation update for testplan points (@ctopal) Fixed by #15440
- [x] Fix description of sec_cm_key_sideload (@ctopal) Fixed by #15440
- [x] Add assumption bounding the URND handshake in FPV (@GregAC). FPV issues fixed by #15611
- [x] Create issue for reseeding URND in background for post-M2 (@vogelpi). See #15473
- [x] FSM coverage exclusion for improving FSM coverage (@ctopal) FSM transition hole is fixed by #14999

**Comment by ctopal** [comment]
Opened up https://github.com/lowRISC/opentitan/pull/15440 for testplan description updates

**Comment by weicaiyang** [comment]
Since all items are addressed, can we close this?
