### ISSUE TITLE
Tracking Yosys build flow progress

### ISSUE THREAD

**Issue by nmoroze** [lowRISC/opentitan#1550]
I've been working on a project that requires me to synthesize OpenTitan in Yosys, and I've spent a bit of time now working with [sv2v](https://github.com/zachjs/sv2v) to try and get OpenTitan converted to Verilog successfully. It seems to me that I'm not the only one working on this, so I was thinking it may be useful to have a central issue to track progress and prevent duplicated work.

I noticed there's a script that's supposed to automate this flow in `util/syn_yosys.sh`, although it seems broken at this point. I've got my own build setup that successfully converts the OpenTitan (with some patches to the source to get around sv2v issues), but I think it has some undiagnosed bugs and it's not quite polished enough for release. However, if anyone needs something like this, let me know and I can send you what I have so far. I'd also be open to helping update/overhaul the existing script to get a bit more robust support for this flow upstream. 

Here's a list of sv2v issues that are blocking a successful clean build of OpenTitan (along with the relevant OpenTitan source lines as of 3d93afbe25200089f60e6e6c0ff2a315a882c97e): 
- [x] Parse error when using $operator() to define signal width: zachjs/sv2v#69
  - `hw/ip/pinmux/pinmux/rtl/pinmux.sv:47,62-63`
  - `hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv:60`
- [x] Enums not converted correctly when used inside generator if statement: zachjs/sv2v#70
  - `hw/ip/prim/rtl/prim_diff_decode.sv:45`
- [x] "-:" part select on multi-bit struct fields expands into invalid indexing: zachjs/sv2v#71
  - `hw/ip/tlul/rtl/tlul_socket_m1.sv:103`
- [x] Parentheses stripped from chained unary operators: zachjs/sv2v#72
  - `hw/ip/alert_handler/rtl/alert_handler_accu.sv:30`
- [x] Struct assign not converted inside ternary expression: zachjs/sv2v#73
  - `hw/ip/hmac/hmac_core/rtl/hmac_core.sv:114`
  - `hw/ip/hmac/hmac_core/rtl/hmac.sv:242`
- [x] Parameter integer array isn't converted with explicit widths: zachjs/sv2v#74
  - `hw/ip/alert_handler/rtl/alert_handler_ping_timer.sv:49`

I've got a few more issues on deck that I need to properly write up. I will update this list as those get filed.

Finally, it's worth noting that I've eliminated the PULP RISCV debug module from my build, although I'd like to get it working in the future as well. 

I'd love to hear if anyone has made progress on this themselves or found issues I've missed! I'm also curious if anyone has thoughts on good ways to update this build flow in OpenTitan upstream to be a bit more robust (or if maintainers have thoughts on whether this should even be included)? 

cc @NilsGraf since it seems like you were working on this a bit ago. 
cc  @zachjs since this might give you a bit more context for where all the issues I'm opening came from. Thanks so much for writing sv2v and for being super responsive with maintenance!

**Comment by GregAC** [comment]
I would note we've got an experimental yosys flow in Ibex, https://github.com/lowRISC/ibex/tree/master/syn

Haven't encountered any sv2v issues on Ibex alone (though I admit I haven't spent much time looking at the generated source, it goes through yosys OK and produces plausible looking implementation results at least).

One difficulty you will encounter with OpenTitan is the need for memories, have you had any thoughts on how to generate them? I guess yosys will attempt to implement them but probably won't give good results.

**Comment by nmoroze** [comment]
> I would note we've got an experimental yosys flow in Ibex

I did do some work with Ibex before this, writing my own Yosys flow before noticing the included one! It did require some fixes to sv2v to handle some edge cases, but it wasn't too bad. 

> One difficulty you will encounter with OpenTitan is the need for memories, have you had any thoughts on how to generate them? I guess yosys will attempt to implement them but probably won't give good results.

I don't think this will be a big deal for me at least, I'm not trying to synthesize to an actual implementation target using Yosys, but rather use the [SMTlib backend](http://www.clifford.at/yosys/cmd_write_smt2.html) for a verification project. I think in this case, Yosys will just dump memories as arrays of bitvectors, and that should work fine for my purposes.

**Comment by nilswiersma** [comment]
Hey @nmoroze, did you end up getting the sv2v and yosys output you were looking for?

**Comment by nmoroze** [comment]
I got it working well enough for me for now, although I'm not sure how useful it would be for others/I don't think it's in a good state for it to be incorporated upstream. 

In particular, I only know my flow works for most of the OpenTitan as of 3d93afb, which is pretty old at this point. I'll probably try to upgrade to be up-to-date with master at some point, but not for the time being. 

Are you interested in using this build flow for something? I could perhaps host my work so far in a separate repo, if you'd like to use what I've got/build off of it for something you're working on.

**Comment by nilswiersma** [comment]
Yeah, I was looking into getting this build flow working as well and stumbled across your issue. If you have the time to share that in a separate repo that would be awesome!

**Comment by nmoroze** [comment]
@nilswiersma Just put it up: https://github.com/nmoroze/opentitan-sv2v

I also found out someone else's flow for the same thing got posted just today: https://github.com/hardenedlinux/embedded-iot_profile/blob/master/docs/opentitan/opentitan-rtl-synthesis-with-yosys.md, which appears to support a newer version. 

Curious to hear if you have any luck when you get the chance!

**Comment by zachjs** [comment]
I have also taken a pass at [updating the syn_yosys script](https://github.com/zachjs/opentitan) based on the two posted above. I hope to verify the conversions in the near future, but I don’t yet have access to a commercial LEC.

I fixed a couple issues in sv2v, and one in Yosys to significantly reduce the necessary edits to the source to get it to convert and synthesize. I would like some guidance on how we can best eliminate the two remaining manual changes.

First, the strengths used in https://github.com/lowRISC/opentitan/blob/master/hw/ip/prim_generic/rtl/prim_generic_pad_wrapper.sv are not supported by Yosys. We could use a flag, as is done for Verilator, but I’m not sure if that would work as intended.

Second, sv2v doesn’t handle the string size casts used in https://github.com/lowRISC/opentitan/blob/master/hw/ip/prim/rtl/prim_lfsr.sv. These casts were discussed extensively in https://github.com/lowRISC/opentitan/pull/1126. I’m hesitant to drop them in sv2v, as that may not be an accurate conversion. sv2v could pass string size casts through unchanged, but Yosys does not support them, as far as I can tell.

**Comment by nmoroze** [comment]
Going to close this issue now since I've finished the relevant project! (and am quite a bit behind OpenTitan top-of-tree in terms of what I've worked with anyways)
