### ISSUE TITLE
[spi_device] V2 review items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15539]
AIs from the meeting [notes](https://docs.google.com/document/d/1_1_hiygzH0JsaxDCWX5LNHDX3G7twTwKOOtXRIv6DVI/edit)

- [x] [Weicai] Implement 2 new planned tests #[15485](https://github.com/lowRISC/opentitan/pull/15485)
- [x] [Weicai] Create an issue and test incomplete command invalid host transaction - Host will send a few transactions and deselect the chip_select line. Make sure this won’t lock up the DUT. #15637, #15517
- [x] [Weicai] complete functional coverage: Flash/passthrough and make sure fcov > 90%
- [x] [Weicai] Follow up to check if close source AST covers ram_cfg (Added an item in internal [OT tracking sheet](https://docs.google.com/spreadsheets/d/1rffD9w6Ybihh93cVlOKGWLksf2PHeXTl-dwqeCoLNOU/edit?resourcekey=0-oUo-NeK_N858vkhCjT99iw#gid=0))
- [x] [weicai] Add a connectivity test at the block level to make sure the ram_cfg_i is connected correctly. #15694
- [x] [Joshua] Check CDC issues and see if we can close them.
- [x] [weicai] Add a test to verify memory parity error. https://github.com/lowRISC/opentitan/issues/9613

- [x] [Other unaddressed spi_device M2 issues](https://github.com/lowRISC/opentitan/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+spi_device+milestone%3A%22Project%3A+M2%22+-label%3AComponent%3AChipLevelTest+) (all addressed except one document related issue)

cc: @eunchan @cindychip @sriyerg

**Comment by jeoongp** [comment]
CDC pending issues were all closed.

**Comment by weicaiyang** [comment]
> CDC pending issues were all closed.

Thanks @jeoongp
