### ISSUE TITLE
[Formal] prim_assert macros TODO

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#160]
In rtl/prim_assert.sv, need to explore these items:

- [x]  check if ASSERT_FINAL needs an `ifndef SYNTHESIS

- [x] should we add ASSERT_INIT_DISABLE?

- [x] can we remove pragma translate_off and ifndef VERILATOR?

In assertion tcl file: 

- [x] eventually remove the assert disable lines

**Comment by sjgitty** [comment]
@cindychip any update on this one?

**Comment by cindychip** [comment]
I just started to work on FPV tooling this week. I will probably have a conclusion for item 1,2,3 by the end of next week. For item 4, this is an enhancement item, I will evaluate if it is worth the change.

**Comment by cindychip** [comment]
For item 4, an alternative is to change them from disable assert to assumptions, which requires less effort.
