### ISSUE TITLE
[Tracking][DIF] USBDEV

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#1601]
* [x]  DIF library landed (lowRISC/opentitan#2093).
* [x]  Expose buffer entries to clients (lowRISC/opentitan#3011).
* [ ] If a user has attempted to send a packet, and got a SETUP, we should give the buffer back to them.
* [ ]  Remove deprecated `mmio` functions.
* [ ]  Unit tests.
* [ ]  In-tree "driver" uses DIF library.
* [ ]  DV extensions.

**Comment by moidx** [comment]
Closing as obsolete
