### ISSUE TITLE
[keymgr] V2S review items

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#16183]
From [notes](https://docs.google.com/document/d/1GDUpGAcLPJnLGNMlHED5HtbXUpEQx9M3oWbef8P_bdo/edit#)

- [x] [weicai] improve FSM coverage to 90%+ #16222
- [x] [weicai] Some test (keymgr_regwen_test) passing rate is 80%+, please take a look. #16241
- [x] [weicai] Update sec_cm testplan “sw_binding_config_regwen” #16188
- [x] [weicai] Update sec_cm testplan “sec_cm_hw_key_sw_noaccess” #16188
- [x] [weicai] Add a test for “sec_cm_output_keys_ctrl_redun” #16288
- [x] [weicai] clarify this and the following items:  [sec_cm_kmac_if_cmd_ctrl_consistency](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/keymgr/data/keymgr_sec_cm_testplan.hjson;l=165 ) #16188 
- [x] [Tim] Parameterize the design to get rid of this unreachable transition (StIdle->StTxLast) 
- [x] [Tim] fix assertion places for mubi output

**Comment by weicaiyang** [comment]
All AIs are addressed
