### ISSUE TITLE
[csrng] V2S review action items

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#16402]
We just had the V2S review meeting for CSRNG today. The notes can be found [here](https://docs.google.com/document/d/1ydyVdA8c1CFU32qeYkVot03r2pWYqGNiJCBRovtD5vc/edit). The following action items have been identified:
- [x] AES CM verification: Extend the existing test (which forces one of the three FSM copies into an illegal state) to trigger the alert for each of the five remaining CMs. The idea is that of an integration test: AES V2S has verified that the CMs trigger an alert within AES, so what remains to be verified for CSRNG is that the AES alert propagates to the fatal alert output of CSRNG. --> @vogelpi
- [x] AES coverage exclusion: Exclude the AES instance from coverage (except toggle), since it is a pre-verified block. The ports that are constant (and thus unreachable for toggle by tests) shall be excluded by UNR. --> @ctopal
- [x] Create a PR to handle escalation and disablement in _one_ code block for each FSM (analogous to how #16307 changed EDN). This change shall include the fix in  #16379 and thus supersede that PR: https://github.com/lowRISC/opentitan/pull/16397 --> @marnovandermaas
- [x] Waive the transitions to the _Error_ state from all states except _Idle_ after the PR in the previous item is merged. The rationale is that a single piece of code now takes care of these transactions, so if the transition works from one state it will by induction also work for the other states. Since the _Error_ state is terminal and fatal, we don't care whatever may be happening in the state from which the transition happens. --> @ctopal
- [x] Complete the AIs defined in #16355 so that the disable and enable sequences of the entropy complex are clearly specified. Use dynamic disables for the `req`/`ack` assertions. --> @andreaskurth
- [x] Test disabling and re-enabling functionality: tracked in #16430. --> @andreaskurth 
- [x] Extend existing tests to hit the remaining bins of `csrng_recov_alert_sts_cg`: tracked in #15743. --> @marnovandermaas 
- [x] Complete coverage of the stage FIFOs: #16390. --> @ctopal 
- [x] Clarify and close FIFO error testing: #16326. --> @ctopal

**Comment by ctopal** [comment]
>Waive the transitions to the Error state from all states except Idle after the PR in the previous item is merged.

I don't think this is needed now since the change in the RTL resulted with Error state transition not getting reported in the FSM coverage at all (it lives under Expression coverage I think). I'm ticking it off as done but please let me know if you think something else can be done for it.

**Comment by marnovandermaas** [comment]
After having merged this PR: https://github.com/lowRISC/opentitan/issues/16430
I think we can close this issue. Closing V2S is now tracked here: https://github.com/lowRISC/opentitan/pull/16517
