### ISSUE TITLE
[cryptolib] KMAC driver progress tracking

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#16410]
With #16180, KMAC driver implements SHA-3/SHAKE/cSHAKE/KMAC, however there is still a list of improvements to be done. The idea is to keep track of these small issues and address them in follow-up PRs. 

Non-exhaustive list, in an arbitrary order:

- [ ] Revisit default configuration. In particular check that internal timer values are working. https://github.com/lowRISC/opentitan/pull/16180#discussion_r1022532627
- [ ] Address memory aliasing violations (when writing key, msg, and prefix blocks to registers). https://github.com/lowRISC/opentitan/pull/16180#discussion_r1022593434
- [ ] Verify that entropy mode is correctly configured and `entropy_ready` is correctly set. Since `entropy_ready` triggers the internal FSM of kmac_entropy, it needs to be set in a timely fashion.
- [ ] Move towards high-level crypto API (e.g. provide one-shot `kmac()`, `shake()` calls, accept keys in masked/blinded form etc.).
- [ ] Revisit error checks in the driver, provide functions to clear errors and flush out KMAC.

**Comment by nasahlpa** [comment]
I've closed the following items:
- Sideloading is implemented
- Testing is extensive due to cryptotest integration
- MSG_FIFO write is something we want to keep as it is (SCA hardening is applied)
- Error handling as there is currently on indication that we need to do more on this side.

Point 1 and 3 are still open.
