### ISSUE TITLE
[alert_handler] escalation pair issue tracking

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1648]
In alert_handler tb, my regression includes an agent to drive escalation receiver pairs. I found the issue as following:
If escalation phase cycle is set to an odd number, my escalation receiver (resp signal) will drive one more cycle, which on the escalation sender side, was caught as a signal integrity error.
Tracking from the escalation receiver design side, I confirmed with Michael and found the same issue in his RTL code.
The side-effect of this issue is: if escalation phase cycle is set to an odd number, every time the alert_handler will detect an extra escalation response signal, and fire an integrity fail alert.

Since the escalation pair is planned to fully verify in FPV, we found following action items:

- [x] For cindy (@cindychip) add back the assertion to check integrity fail in this scenario.

- [x] For michael (@msfschaffner) once assertion checked in, please support the fix in RTL, and update the spec accordingly.

- [ ] Future item: discuss if FPV fully verified the model. If needed, do we need to support the pairs in simulation, or is top-level sufficient.

**Comment by msfschaffner** [comment]
@cindychip is this something we should keep open, or can we close this issue?

**Comment by cindychip** [comment]
I think we are good to close this. I think current FPV and DV are fine.
