### ISSUE TITLE
[crypto] Implement hardening for ECDSA scalars.

### ISSUE THREAD

**Issue by jadephilipoom** [lowRISC/opentitan#16952]
## Summary

After quite a bit of thought, discussion, and deliberation, we have a plan for how to harden ECDSA scalars. We will use additive shares that are not fully reduced mod n. For instance, we will represent a 256-bit scalar `d` with two 320-bit values `d0`, `d1` such that `(d0 + d1) mod n = d`. The 64 redundant bits ensure that a side-channel attack would need to recover many bits of the scalar value `d0 + d1` in order to get any useful information.

The number of extra bits is adjustable, but should be at least 64 for a good level of protection, and at most the length of `n` - 64 so that the modular inversion and scalar-field multiplication algorithms will work with a standard-size reduction routine.

## Task List
This will be a large change, so here's a big-picture list for tracking:
- [x] Adjust existing P-256 implementation to use extra-long scalars for signing.
- [x] Implement P-256 random key generation.
- [x] Implement P-256 keymgr key generation.
- [x] Adjust existing P-384 implementation to use extra-long scalars for signing.
- [x] Implement P-384 random key generation.
- [x] Implement P-384 keymgr key generation.

## Methodology/Techniques
This is a personal cheatsheet for how I plan to implement each subroutine that handles secret scalars, mostly for my own reference but included here anyway for archival purposes and in case others are interested.

| Operation | Method |
| --- | --- |
| Generate random secret key d | Choose the specific algorithm from FIPS 186-4 that uses an extra-long seed, and do not reduce the value. Run this twice and interpret the results as additive shares. Check for zero by either multiplying with a non-secret random scalar and checking the result is nonzero or performing point-scalar multiplication and checking that the result is not the origin point (this is slower, but the computation is also part of keygen so ultimately faster if combined). |
| Generate random secret scalar k | Same procedure as `d`, including check for zero (`k` is multiplied by a point during signing). |
| Generate keymgr-derived secret key | Masked modular reduction: first use Goubin's method to convert the boolean shares into additive shares modulo `2^(L+1)` where `L` is the seed length, then use the highest bit to correct for overflow if needed. Reduce each share modulo `n << # extra bits` using conditional subtractions. Check for zero as with random `d`. |
| Multiply with a non-secret scalar | Generate a random scalar `a` (at least 64 bits, and at most `<length of n - #extra bits> `bits). Multiply `a` with each share mod `n`. The products are at most the same size as the products of fully reduced operands, so we can use the same modular reduction routine for both. Now compute `a^-1`, the inverse of `a` mod `n`, and multiply each share with `a^-1` times the non-secret scalar. |
| Compute modular inverse of scalar| Generate a random scalar `a` (at least 64 bits). Multiply `a` with each share and add these together to get `(a * k) mod n`. Compute the inverse to get `(a * k)^-1`; multiply by the original `a` to get `k^-1`. Choose a short enough random scalar so that a normal-sized modular reduce can be used (the same technique as for multiplying with a non-secret scalar). |
| Multiply a point with a scalar | Use Shamir’s trick to multiply by the sum of the shares (existing implementation); just do extra iterations equivalent to the number of extra bits. |

## Alternatives considered:
- Additive shares without extra bits
  - Represent a 256-bit secret `d` as two 256-bit shares such that `(d0 + d1) mod n = d`
  - Not as secure as using redundant bits; an attacker could get one bit from each share and effectively get a bit of the secret, which is dangerous for `k` especially
- Multiplicative shares
  - Represent a 256-bit secret `d` as two 256-bit shares such that `(d0 * d1) mod n = d`
  - Significantly slower and more complex than additive shares

**Comment by jadephilipoom** [comment]
Now complete for P-256; moving this to P2 for P-384.

**Comment by johannheyszl** [comment]
Linking #19692 since it is relevant

**Comment by jadephilipoom** [comment]
Actually, I think all this work is now done; @wettermo completed all the tasks for P-384 with e.g. https://github.com/lowRISC/opentitan/pull/19290 and https://github.com/lowRISC/opentitan/pull/23301
