### ISSUE TITLE
[otbn, pre_sca] Roadmap for COCO-OTBN work

### ISSUE THREAD

**Issue by abdullahvarici** [lowRISC/opentitan#17213]
### Description

With the PRs #17100 and #17211, COCO-ALMA framework is ported to the OTBN core. In this issue, we want to create a roadmap to use the framework with the OTBN core and list some points that we need to investigate. Following [GDoc](https://docs.google.com/document/d/11eBtSkNZ1pujm3_D96aeTvr-IeDKOVsyj4bp4f0noPc/edit?usp=sharing) will have intermediate results and discussions.

- [x] Be sure the tool is working with the OTBN correctly. See expected leakage as a result.
- [x] Find out the source code which is causing leakage in bignum register file. (More information is on [GDoc](https://docs.google.com/document/d/11eBtSkNZ1pujm3_D96aeTvr-IeDKOVsyj4bp4f0noPc/edit?usp=sharing). If needed update the RTL and run the analysis again, compare results. 
- [x] Run and see isw_and algorithm do not cause any leakage.
- [ ] Adapt the framework to use arithmetic masking. Read [this paper](https://eprint.iacr.org/2022/849.pdf) for this reason.
- [x] Run the analysis with the ECC algorithm code snippets and verify formally the OTBN is secure.

**Comment by vogelpi** [comment]
Futher tasks that come to my mind:
- [ ] Add cycle counter in testbench to easily inspect waves and associate those waves with tool output. The counter has to be reset with the start pulse being sent.
- [ ] Feed URND/RND signals (actual data only, not the handshake) out such that we can place a `volatile_random` label on these inputs. This will become very relevant for analyzing code snippets using URND and RND.

**Comment by moidx** [comment]
Moving to cryptolib milestone as this enables development in pre-silicon stages.

**Comment by vogelpi** [comment]
@abdullahvarici , please update this issue to:
1. Reflect the progress over the last couple of months including references to relevant PRs.
2. Document what the current status is, also in terms of potential support for analyzing arithmetic masking.
Thanks!

**Comment by jadephilipoom** [comment]
I think this is done? We've added the findings to the OTBN style guide: https://opentitan.org/book/doc/contributing/style_guides/otbn_style_guide.html?highlight=secure%20coding#secure-coding-for-cryptography

I created https://github.com/lowRISC/opentitan/issues/24056 to track actually making the existing code follow these rules, but I think that's separate from this issue about actually doing the work to find the rules, so it's probably safe to close this now. Please feel free to reopen if I'm wrong here.

**Comment by vogelpi** [comment]
This sounds good to me, thanks @jadephilipoom .
