### ISSUE TITLE
[dvsim] Feature tracker

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#1727]
Here's the list of dvsim work items that are planned. Considering working on this tool is more like a 20% project for the most of us, the roll out is expected to be slow. Please 

General:

- [ ] Exit with error on failure - PR #1697 

- [ ] Add detailed documentation (user guide and ref manual)

- [ ] Deploy on GCP

- [ ] Add support for selecting individual targets from a cfgs list 

- [ ] Email flow results 

- [ ] Graceful exit on CTRL-C support

- [ ] Spin out as a separate pip package so that it can be using in other lowrisc repos - PR #1634

DV / FPV: 
- [ ] Auto rerun failing tests with debug switches

- [ ] Add support for FPV (testplan annotation, publishing results, COI coverage etc)

- [ ] Add support for coverage reporting with Xcelium

Lint:
- [ ] Add support for lint - PR #1596 

- [ ] Add support for Verible and other lint tools

Synthesis:
- [ ] Add support for synthesis with DC, generate reports

**Comment by sriyerg** [comment]
Bug: some keys need to be [needlessly set](https://github.com/lowRISC/opentitan/pull/1749/files#r401307251).

**Comment by weicaiyang** [comment]
Just edited this issue to add an item under DV - https://github.com/lowRISC/opentitan/issues/16988

**Comment by rswarbrick** [comment]
I don't think this feature tracker issue is really live any more. Closing (since we'll track dvsim development in a different way).
