### ISSUE TITLE
[sysrst_ctrl] Verification planning

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#17278]
In this issue we track what still needs to be done to verify the system reset control block.

In terms of improving coverage, most metrics are above 95% except for the `u_sysrst_ctrl_detect_pre`:
- [x] Add a new test to randomize the combo precondition: https://github.com/lowRISC/opentitan/pull/17318
- [x] Improve current coverage of the FSM in the detect logic: https://github.com/lowRISC/opentitan/issues/12673 https://github.com/lowRISC/opentitan/pull/17371
- [x] Sample wakeup in testbench: https://github.com/lowRISC/opentitan/issues/14041 https://github.com/lowRISC/opentitan/pull/17374
- [x] Improve ultra-low-power test: https://github.com/lowRISC/opentitan/pull/17247 and https://github.com/lowRISC/opentitan/pull/17315
- Add a waiver for the `u_prim_sync_reqack` conditions coverage. **Optional** unless we want to get 100% coverage.

Cleanup based on TODOs in codebase and existing issues:
- [x] Enable linting: [TODO in `sysrst_ctrl_sim.core`](https://github.com/lowRISC/opentitan/blob/70b1e3d936504a765390f682a12a53bfbf8df0ce/hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim.core/#L29) https://github.com/lowRISC/opentitan/pull/17322
- [x] Remove this because it is already done: [TODO in environment package](https://github.com/lowRISC/opentitan/blob/70b1e3d936504a765390f682a12a53bfbf8df0ce/hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_pkg.sv/#L22) https://github.com/lowRISC/opentitan/pull/17322
- [x] Enable alert checking: [TODO in scoreboard](https://github.com/lowRISC/opentitan/blob/70b1e3d936504a765390f682a12a53bfbf8df0ce/hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv/#L32) https://github.com/lowRISC/opentitan/pull/17322
- [x] Implement TL interface for interrupt enable: [TODO in scoreboard](https://github.com/lowRISC/opentitan/blob/70b1e3d936504a765390f682a12a53bfbf8df0ce/hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv/#L114) https://github.com/lowRISC/opentitan/pull/17322
- Check any outstanding interrupts etc after tests finish: [TODO in base sequence](https://github.com/lowRISC/opentitan/blob/70b1e3d936504a765390f682a12a53bfbf8df0ce/hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv/#L71) **Optional** because the current tests do not adhere to this standard and it is unlikely this will improve the quality of the block.
- [x] Investiage `pwrb_in_i` transition detection: https://github.com/lowRISC/opentitan/issues/17238
- [x] Do a full OpenTitan reset during the power on reset block level test: https://github.com/marnovandermaas/opentitan/blob/47eff2793614d9169b56f40b3161b595e9c1853f/hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ec_pwr_on_rst_vseq.sv#L48 Removing this todo: https://github.com/lowRISC/opentitan/pull/17767

Testing failures that need resolving:
- [x] Chip level test that is failing: https://github.com/lowRISC/opentitan/issues/15679 https://github.com/lowRISC/opentitan/issues/17741 -> this issue is moved to after M2.5

## Optional tasks
We can create more thorough coverage by adding the following new cross points derived from [this sheet](https://docs.google.com/spreadsheets/d/1A6VE5XRmSn8KbDPZ_UFLUzp0G-ZuyPC1Xy9gNI1sni0):
- Combo detection and auto block key output
- Combo detection and key/input triggered interrupt
- Combo detection and ultra-low-power wakeup
- Combo detection and hardware reset stretch
- Combo detection and output inversion control
- Output inversion control and auto block key output
- Output inversion control and key/input triggered interrupt
- Output inversion control and ultra-low-power wakeup
- Output inversion control and key/input triggered interrupt
- Output inversion control and hardware reset stretch
- Auto block and input value accessibility

For all these crosses, we should add them to the test plan and the UVM environment.
- Add cross points to test plan: https://github.com/lowRISC/opentitan/pull/17291

This list is based on scoping work done together with @andreaskurth, @crteja and @cindychip. 

## Effort estimation
Most effort estimation are done in the individual issues but there are a couple of things that fall outside this:
- ULP test: 32
- Examining coverage: 16
- Resolving todos: 16

> estimate 64
> remaining 2023-03-16 8

**Comment by johngt** [comment]
@marnovandermaas / @crteja - are the checkbox items above in the original issue now completed?

**Comment by crteja** [comment]
@johngt , two PRs are still open https://github.com/lowRISC/opentitan/pull/17423 and https://github.com/lowRISC/opentitan/pull/17371

**Comment by marnovandermaas** [comment]
All the work that I foresee for M2.5 in system reset control should be done now. I'll close this tracking issue for now.
