### ISSUE TITLE
[bazel,opentitantool] enable cw310+hyperdebug test platform

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17381]
## Background / Problem

Some top-level tests require a host-component to interact with the OT, e.g., a test drives I2C transaction requires an external device to ACK the transactions to proceed. Currently we run said tests in DV sim only, where long sim times slow development.

## Solution

Enable tests to run on CW310+HyperDebug platform to meet pre-Si test requirements  by slighltly modifying Bazel / OpenTitanTool test infrastructure.

## Tasks
- [x] make opentitantool `--interface` parameter overrideable  in `opentitan_functest` `cw310_params` (#16763)
- [x] enable opentitantool to load a bitstream over the same USB interface used when `--interface=cw310`, when the `--interface=hyperdebug` is set (i.e., make opentitantool talk directly to the CW310 to load bitstreams / perform any `fpga` subcommands, otherwise talk directly to the `hyperdebug` interface)
- [x] provide example CW310+HyperDebug test in repository (#16763)

**Comment by cfrantz** [comment]
https://github.com/lowRISC/opentitan/pull/17386 adds bitstream loading.

**Comment by cfrantz** [comment]
https://github.com/lowRISC/opentitan/pull/17409 refactors the `cw310_params` to specify hyperdebug as the debugger.
- Create bazel labels for cw310+hyperdebug specific bitstreams.
- Set the `interface` to `hyper310` for tests which should use hyperdebug.

**Comment by timothytrippel** [comment]
can probably close this now?

@cfrantz feel free to re-open if not done yet
