### ISSUE TITLE
[i2c] Outstanding TODOs for verification

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#17458]
### Description

This issue collects some open TODOs, which need to be investigated before M2.5. We can tick off an item if we know that it has already been done, if they can be deferred or if we create another issue to track them:

- [x] Implement i2c_host_fifo_watermark #17566 
- [x] host_perf_test/target_perf_test - Should be checking performance is as expected: https://github.com/lowRISC/opentitan/pull/17675
Now tracked in issue: https://github.com/lowRISC/opentitan/issues/17938
  - Clarify what timing parameters we need
- [x] host_smoke/target_smoke - No checking of interrupts specified on testplan, should be included #17930
- [x] Stretch handling in host mode - No explicit mention of this in testplan, i2c target agent may be doing stretching, need to investigate
- [x] List various bad behaviours/protocol violations we could see in host and target modes, ensure they are tested appropriately https://github.com/lowRISC/opentitan/issues/17835
- [x] Add verification for unconditional software stretch may be missing testplan item: not necessary https://github.com/lowRISC/opentitan/issues/15170#issuecomment-1498072696
- ~~Loopback mode test in PR, but not well documented what loopback mode does~~ - https://github.com/lowRISC/opentitan/pull/17091
- [x] This issue https://github.com/lowRISC/opentitan/issues/15226 is closed as done but it may not be fully resolved. It may still need some kind of done/level/watermark interrupt for acq FIFO rather than just a full interrupt.

This PR was created mainly from input by @GregAC.

Old estimate before 2023-04-12: 64
> estimate 20
> remaining 2023-04-04 4
> remaining 2023-04-11 0

**Comment by crteja** [comment]
Effort estimate for M2.5
> estimate 50
> remaining 2023-03-22 1

**Comment by marnovandermaas** [comment]
@crteja would you mind capturing the effort for the following PR here?
https://github.com/lowRISC/opentitan/pull/17675

**Comment by crteja** [comment]
> remaining 2023-03-28 56

**Comment by crteja** [comment]
> remaining 2023-04-03 52

**Comment by crteja** [comment]
>     Stretch handling in host mode - No explicit mention of this in testplan, i2c target agent may be doing stretching, need to investigate
Host mode stretching is exercised in [i2c_host_stretch_timeout](https://github.com/lowRISC/opentitan/blob/22d6779d33da10a54f042145595ecf9ef925dc64/hw/ip/i2c/dv/env/seq_lib/i2c_host_stretch_timeout_vseq.sv#L8) test and `stretch_timeout` interrupt is checked in test. This item can be marked as closed

**Comment by GregAC** [comment]
Thanks @crteja does this have any effect on your 'remaining' estimate?

**Comment by crteja** [comment]
Yes, we can remove the estimate(4) for the marked item. Updated remaining estimate
> remaining 2023-04-04 48

**Comment by crteja** [comment]
> Implement i2c_host_fifo_watermark

There is already a test `i2c_host_fifo_threshold` which covers the watermark interrupts with different FIFO levels. It is currently not mapped to any verification stage. Mapped it to V2 and renamed it to `i2c_host_fifo_watermark` to reflect the naming used in interrupts and a minor change in sequence to do front door access of registers(#17789 )

**Comment by crteja** [comment]
>  Add verification for unconditional software stretch may be missing testplan item

@marnovandermaas , we can mark this item as done based on https://github.com/lowRISC/opentitan/issues/15170#issuecomment-1498072696

**Comment by crteja** [comment]
> remaining 2023-04-11 44

**Comment by marnovandermaas** [comment]
The individual tasks of this issue are now tracked separately, so closing this issue for now.

**Comment by johngt** [comment]
Thanks @marnovandermaas - do you mind editing the estimates/rem from 
```
> estimate xyz
> remaining xyz
```
to
```
> !_estimate xyz
> !_remaining xyz
```
in the main issue? TIA
