### ISSUE TITLE
[fpga] connect external clk to pin

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17492]
_**Related to #17491.**_

# Background

For [manufacturing tests](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson), we need to be able to drive LC transitions via the LC JTAG TAP, which requires driving the external clk.

# Problem

On CW310 FPGA, the external clk is [tied off to 0](https://github.com/lowRISC/opentitan/blob/060354c410761db905f385909c2b163b0076258d/hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv#L792), so we currently cannot develop said [manufacturing tests](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson) on the FPGA. 

# Tasks

- [ ] Investigate what frequency to drive an "external clk" FPGA pin such that another PLL can drive another 48 or 96 MHz clk, as this is what is [required](https://opentitan.org/book/hw/ip/clkmgr/index.html#software-requested-external-clocks)?
- [x] Investigate what pin the external clk can be routed too such that it can reach the HyperDebug PWM pin through the swizzle board (if #17491 is feasible); (ideally `IOC6` as this is the [pin used for the external clk on the ASIC]) - IOC6 should work
- [ ] Modify FPGA RTL / XDC file to drive external clock pin with another PLL.

**Comment by timothytrippel** [comment]
CC: @a-will

**Comment by a-will** [comment]
From current discussions, we're looking to model an observable change from an "internal" oscillator to external clocks. For this, we would look to connect the raw output from the IOC6 pad to a PLL in the FPGA, then either (1) choose an output that matches the main PLL's CW310-provided input and mux them or (2) choose outputs that match the main PLL's outputs and mux those.

(1) may only allow for emulating the `all_clocks_byp_req`, whereas (2) could handle doing the feature where it is just the I/O clocks. (2) may use BUFGMUX instances we don't have, though.

We would need to remap the IOC6 function at USERIOA-18 to a clock-capable pin and respin the hyperdebug's swizzle board. Candidates:
- USERIOA-32 (currently unmapped)
- USERIOA-11 (currently IOB5 - UART)
- USERIOA-33 (currently IOR9 - FLASH WP)
- USERIOB-14 (currently IOC0 - SW STRAP0)
- USERIOB-26 (currently unmapped)
- USERIOB-30 (currently unmapped)
- USERIOB-32 (currently unmapped)

**Comment by timothytrippel** [comment]
At the most basic level, we really just want the FPGA OT instance not to freeze up when we select `ext_clk`, since right now its just tied off to 0.

This will allow us to develop manufacturing tests on the FPGA.

I could see a potential case where we want to use hyp + ASIC together and drive ext_clk, but in that case, might be better to have ext_clk driven by something other than hyp, e.g. something with tigher tolerances like a function generator?

So maybe in the interim it might be better to just tie the `ext_clk` in the CW310 top-level to the same (or a similar) PLL that drives the main clk? This would then render #17491 un-needed.

Thoughts?
CC: @msfschaffner

**Comment by a-will** [comment]
> At the most basic level, we really just want the FPGA OT instance not to freeze up when we select `ext_clk`, since right now its just tied off to 0.
> 
> This will allow us to develop manufacturing tests on the FPGA.
> 
> I could see a potential case where we want to use hyp + ASIC together and drive ext_clk, but in that case, might be better to have ext_clk driven by something other than hyp, e.g. something with tigher tolerances like a function generator?
> 
> So maybe in the interim it might be better to just tie the `ext_clk` in the CW310 top-level to the same (or a similar) PLL that drives the main clk? This would then render #17491 un-needed.
> 
> Thoughts? CC: @msfschaffner

It turns out I goofed and got the hierarchy wrong, but yeah, from a high level, that makes sense. It actually would be something like a modification in `ast_clks_byp.sv` to funnel the clk_osc group through if AST_BYPASS_CLK is defined.

**Comment by a-will** [comment]
The AST files claim to be auto-generated, though. Is there a proper way to go about editing them?

**Comment by timothytrippel** [comment]
@a-will has found a working solution in #17553, but since the AST RTL model in the open source is autogenerated, we have contacted @Jacob-Levy about integrating these changes into the AST RTL model template and regenerating the RTL.

**Comment by meisnere** [comment]
We have a way to control ast clocks from external source, did you try to use it instead?

Drive the following 3 ast ports:
clk_ast_ext_i
ext_freq_is_96m_i
all_clk_byp_req_i

**Comment by timothytrippel** [comment]
If you read the issue, the problem is that `clk_ast_ext_i` is currently tied off to zero on the FPGA toplevel. We don't want to tie this to an actual external FPGA pin and drive it externally say with a function generator because that would entail more infrastructure to add to CI. @a-will was trying to tie the external clk to the same clocks generated within the FPGA in #17553, so that when our tests switch to the ext clock the FPGA doesn't die. Does that make sense?

**Comment by arnonsha** [comment]
@timothytrippel  
I understand why using a real ext clock would impose difficulties on CI.
Can you explain why @a-will solution is easier than connecting the internal FPGA PLL output to `clk_ast_ext_i` and use the existing clock bypass dividers ?

thanks

**Comment by a-will** [comment]
@arnonsha
Those dividers would yield clocks that are too fast for the FPGA, and it is simply more complex for timing analysis to have a separate input path. The dividers are also a very poor implementation on the FPGA, adding yet more LUT logic on the clock paths.

On top of that, the ratios between clocks _must_ be different vs. the ASIC. USB must continue to be fed 48 MHz and the AON clock must still be around 200-250 kHz, but the main and I/O clocks must be significantly less than 96 MHz / 24 MHz to meet timing.

For these reasons, it is sensible to bypass the clock generation from clk_ast_ext_i.

**Comment by arnonsha** [comment]
Thanks @a-will . That makes sense.
We will fix in the AST template accordingly.

**Comment by timothytrippel** [comment]
thanks @arnonsha ! Please close this issue when it is complete.
