### ISSUE TITLE
[rom] Update e2e key_validity tests

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#17594]
### Description

- [x]  update key_validity and key_type tests #17346 
- [x] agree and document the earlgrey keyset #17474 
- [x] add the required keys as agreed above #17484

**Comment by moidx** [comment]
Hi @cfrantz, what should be the next steps for this issue after the refactoring applied to add the prod keys?

**Comment by cfrantz** [comment]
I merged #17474 as the documentation matches the committed key slots.

**Comment by cfrantz** [comment]
For both the fake and real keys, we have host-based unit tests which check that each key can be used to verify a test message.

**Comment by moidx** [comment]
Fixed by: https://github.com/lowRISC/opentitan/pull/23246
