### ISSUE TITLE
[aes] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17901]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @vogelpi

**Comment by johngt** [comment]
Efforts tracked in respective issues
- [ ] Complete TODOs in DV code (3 d .. 8.5 d) → 2d → May 8, 2023 (8d) - none of the issues above are prioritised [#18425](https://github.com/lowRISC/opentitan/issues/18425)
- [ ] Complete V2.5 checklist items not captured elsewhere (3 d .. 3 d) → 2.5d [#18428](https://github.com/lowRISC/opentitan/issues/18428)
- [ ] V2+ 2.5  tests [#18427](https://github.com/lowRISC/opentitan/issues/18427) → backlog
  - [ ] [[aes, dv] Fix reseed rate test](https://github.com/lowRISC/opentitan/issues/17357) (1 d .. 2 d) → 0d → Post M2.5.1

**Comment by vogelpi** [comment]
Closing, AES V2.5 has been signed off.
