### ISSUE TITLE
[rv_core_ibex] Verification sign-off for M2.5

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#17916]
### Description

This tracks open verification tasks for M2.5.
See effort estimation docs for details.

CC @GregAC

**Comment by johngt** [comment]
- [ ] Bring existing V2(S) tests to 90% pass rate (3d .. 6d) [#18421](https://github.com/lowRISC/opentitan/issues/18421)
- [ ] Complete TODOs in DV code (0.5d .. 1d) [#18422](https://github.com/lowRISC/opentitan/issues/18422)
- [ ] Ibex V2.5 checklist items (simplified) (0.5d) [#18424](https://github.com/lowRISC/opentitan/issues/18424)
- [ ] Ibex Project P2s [#18423](https://github.com/lowRISC/opentitan/issues/18423) (4d)
- [ ] [16838](https://github.com/lowRISC/opentitan/issues/16838) unless simplified - see effort est doc (4d)
- [ ] Formal verification PMP improvement / Post Shuttle for prod [#1963](https://github.com/lowRISC/ibex/issues/1963) (4d .. 8d)

**Comment by GregAC** [comment]
Complete for rv_core_ibex V2.5, #14436 does not need to be closed for this.
