### ISSUE TITLE
[kmac] V2.5 Todos

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18368]
### Description

- [x] ./dv/env/seq_lib/kmac_app_with_partial_data_vseq.sv:5:// TODO(#10996): Based on kmac_app sequence, drive partial data by sending `strb` value that is not -> seems to be stale, based on the issue, [0d] @cindychip 
- [ ] ./dv/env/seq_lib/kmac_lc_escalation_vseq.sv:63:  	// TODO: Add checking for kmac app request., [0.5d]
- [ ] ./dv/env/seq_lib/kmac_lc_escalation_vseq.sv:77:	// TODO(#10804): confirm with designer if we need an error code here. -> seems to be stale based on the issue, [0d] @cindychip
- [x] ./dv/env/seq_lib/kmac_base_vseq.sv:289:	// TODO, boilerplate and looks like this is not needed and can be removed, [0d]
- [x] ./dv/env/seq_lib/kmac_base_vseq.sv:523:  	// TODO - Xcelium currently does not support `with` operator, current tool workaround, nothing to be done, [0d]
- [ ] ./dv/env/seq_lib/kmac_base_vseq.sv:692:  	// TODO: randomize non/blocking? 
Check if this can be done easily, otherwise leave as is [0.5d]
- [x] ./dv/env/seq_lib/kmac_key_error_vseq.sv:6:// TODO(#10704): current RTL only supports this error in app mode. -> this has been moved to M2.5 backlog, [0d]
- [x] ./dv/env/seq_lib/kmac_key_error_vseq.sv:57:  	// TODO(#10835): Check with designer if sha3_idle should be set to 0. -> seems to be stale based on issue, [0d]
- [ ] ./dv/env/seq_lib/kmac_key_error_vseq.sv:63:	// TODO: enable scb and run normal sequence, then add this sequence to stress_all sequence., [0.5d]  --> Post M2.5, will file an issue
- [ ] ./dv/env/seq_lib/kmac_edn_timeout_error_vseq.sv:47:	// TODO: enable scb and run normal sequence, then add this sequence to stress_all sequence. [0.5d]  --> Should be post M2.5 enhancement
- [ ] ./dv/cov/kmac_cov_if.sv:39:	// TODO: check with designer, this might be unreachable., 
There are other covergroups here that do not seem to show up in the coverage report. 
Add them and check coverage, remove if unreachable (check with designer) [1d]
- [x] ./kmac.core:95:	# TODO: set default to DC once -> stale can be removed, [0d]
- [ ] ~~./data/kmac_testplan.hjson:165:        	// TODO: Not all of these errors have been supported yet, and more errors might be~~

Clean up scoreboard: 4d → [2d]
- [ ] ./dv/env/kmac_scoreboard.sv:235:  // TODO: use this for error case instead
- [ ] ./dv/env/kmac_scoreboard.sv:667:      	// TODO: check below
- [ ] ./dv/env/kmac_scoreboard.sv:757:    	// TODO - handle error cases
- [ ] ./dv/env/kmac_scoreboard.sv:972:    	// TODO need to do error checking
- [ ] ./dv/env/kmac_scoreboard.sv:985:        	// TODO: add some direct sequence to check this error information.
- [ ] ./dv/env/kmac_scoreboard.sv:1061:      	// TODO

7d total from MSF
>estimate 28

**Comment by msfschaffner** [comment]
@moidx

**Comment by moidx** [comment]
Closing as obsolete as kmac has already being signed off for V2.5
