### ISSUE TITLE
[rv_core_ibex] Ibex Project P1s and P2s

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18423]
### Description

Tracking here so that they are not forgotten about.
Investigate over all issues in the Milestone and triage to P3 or lower if not going in for sprint 2.

- [x] [[dv] Implement testing and coverage for various mstatus states](https://github.com/lowRISC/ibex/issues/1825) [1d]
- [x] [[dv] PMP Coverage Holes](https://github.com/lowRISC/ibex/issues/1944) [1d]
- [x] [PMP Coverage Holes](https://github.com/lowRISC/ibex/issues/1869) (likely a duplicate of 1944) --> Can be closed
- [x] [[dv] Rip out old checking where needed in test suite](https://github.com/lowRISC/ibex/issues/2005) [2d]

>estimate 16
