### ISSUE TITLE
[rv_core_ibex] V2.5 checklist

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18424]
### Description

- [x] DESIGN_DELTAS_CAPTURED_V2.5 [0.5d]
- [x] SIM_NIGHTLY_REGRESSION_AT_V2.5 [6d] covered in [#18421](https://github.com/lowRISC/opentitan/issues/18421)
- [x] ALL_TODOS_RESOLVED [1d] covered in [#18422](https://github.com/lowRISC/opentitan/issues/18422)

>estimate 2
