### ISSUE TITLE
[aes] V2.5 checklist

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18428]
### Description

- [x] DESIGN_DELTAS_CAPTURED_V2.5 [2d]
- [x] ALL_TODOS_RESOLVED [captured in [#18425](https://github.com/lowRISC/opentitan/issues/18425) 8d]
- [x] ALL_TOOL_WARNINGS_ARE_REVIEWED [0.5d], see https://github.com/lowRISC/opentitan/pull/18972

>estimate 10 
>2023-06-16 remaining 8
>2023-06-19 remaining 6

**Comment by vogelpi** [comment]
I am closing this. All points have been addressed.
