### ISSUE TITLE
[clkmgr] V2.5 Checklist items

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18430]
### Description

- [x] DESIGN_DELTAS_CAPTURED_V2.5 [0.25d]
- [x] X_PROP_ANALYSIS_COMPLETED [0.25d]
- [ ] ALL_TOOL_WARNINGS_ARE_REVIEWED [0.5d]

>estimate 4

**Comment by matutem** [comment]
@johngt I thought we had finished all 2.5 items in https://github.com/lowRISC/opentitan/pull/18380, but I realized there were some compilation warnings. They are fixed in https://github.com/lowRISC/opentitan/pull/18449, so once that is merged we will be M2.5 ready with clkmgr.
