### ISSUE TITLE
 [I2C Host] I2C test plan

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18639]
### Description

This issue details what has been tested as part of the I2C Host test plan.

 - [x] The following I2C features
   - [x] Speeds
     - [x] Standard-mode (100 kbaud)
   - [x] irqs
     - [x] stretch_timeout
   - [x] Clock stretching.
     - [x] Timeout.
     - [x] During write.
     - [x] During read.
 - [x] Read and write all registers of the sensors:
     - [x] Power/current monitor https://github.com/lowRISC/ot-discrete-eg/issues/12
       - [x] Driver written
       - [x] Tested manually
       - [x] Integrated into testing
     - [x] Temperature/humidity sensor https://github.com/lowRISC/ot-discrete-eg/issues/13
       - [x] Driver written
       - [x] Tested manually
     - [x] Compass https://github.com/lowRISC/ot-discrete-eg/issues/14
        - [x] Driver written
       - [x] Tested manually
     - [x] Accelerometer https://github.com/lowRISC/ot-discrete-eg/issues/15
       - [x] Tested manually
     - [x] Ambient light detector https://github.com/lowRISC/ot-discrete-eg/issues/16
       - [x] Tested manually
     - [x] Gas sensor https://github.com/lowRISC/ot-discrete-eg/issues/17
       - [x] Tested manually

Note that due to part numbers being sensitive - that the specific details are kept in an embargoed repo.
