### ISSUE TITLE
[I2C HOST] Test plan - remaining items

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#18711]
## Description

This issue details what needs to be tested for the next milestone for the I2C Host and complements the previous [test plan](https://github.com/lowRISC/opentitan/issues/18639).

 - [x] I2C features
   - [x] NAK detection.
   - [x] Host irqs
     - [x] cmd_complete
     - [x] nak
     - [x] rx_overflow
     - [x] fmt_overflow
     - [x] rx_threshold
     - [x] fmt_threshold
   - [x] Reset via Reset manager.
   - [x] Disable NAK irq (FDATA.NAKOK).
 - [x] Read and write all registers of the sensors:
     - [x] Power/current monitor https://github.com/lowRISC/ot-discrete-eg/issues/12
       - [x] In CI
     - [x] Temperature/humidity sensor https://github.com/lowRISC/ot-discrete-eg/issues/13
       - [x] Integrated into testing
       - [x] In CI
     - [x] Compass https://github.com/lowRISC/ot-discrete-eg/issues/14
       - [x] Integrated into testing
       - [x] In CI
     - [x] Accelerometer https://github.com/lowRISC/ot-discrete-eg/issues/15
       - [x] Driver written
       - [x] Integrated into testing
       - [x] In CI
     - [x] Ambient light detector https://github.com/lowRISC/ot-discrete-eg/issues/16
       - [x] Driver written
       - [x] Integrated into testing
       - [x] In CI
     - [x] Gas sensor https://github.com/lowRISC/ot-discrete-eg/issues/17
       - [x] Driver written
       - [x] Integrated into testing
       - [x] In CI
     - [x] FRAM https://github.com/lowRISC/ot-discrete-eg/issues/18
       - [x] Driver written
       - [x] Tested manually
       - [x] Integrated into testing
       - [x] In CI
     - [x] EEPROM https://github.com/lowRISC/ot-discrete-eg/issues/19
       - [x] Driver written
       - [x] Tested manually
       - [x] Integrated into testing
       - [x] In CI

Note that due to part numbers being sensitive - that the specific details are kept in an embargoed repo.

**Comment by johngt** [comment]
@engdoreis - could you see what should still be done for the next milestone and highlight it as a response to this message

**Comment by engdoreis** [comment]
I've updated the ckecklist.
So all the devices in the BoB have a test written on Master.
I'm working on this [PR](https://github.com/lowRISC/opentitan/pull/18799) that will run this tests on CI in a nightly job.

**Comment by engdoreis** [comment]
With the PR that Hugo and I are filing today, most of the items above will be finished.
The remaining one are:
- Device IRQs
- Speed modes other than `Standard`.
