### ISSUE TITLE
[i2c] V2 review checklist

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#18741]
### Description

This issue is a result of the I2C V2 review meeting that happened on 24 May 2023. The document capturing the full notes is [here](https://docs.google.com/document/d/1gTxRUPEclOT0ONaNbkUafR11FwuGGy4cOvJ4tU4zx74/edit#) (restricted access). From the meeting the following action items have come out, which need to be resolved before V2 sign-off can be done:

- [x] File an issue to track that loopback mode was never fully implemented but still lives in the RTL [#18742](https://github.com/lowRISC/opentitan/issues/18742).
- [x] Add documentation on how to calculate bus clock speed based on timing parameters. Also, note that sampling speed must be 5-10 times higher than the bus speed: https://github.com/lowRISC/opentitan/issues/18492
- [x] Make sure that the FSM in `i2c_protocol_cov` is not counted in the RTL metrics. This FSM is only used for DV so it should be added to the waiver file. This action is part of issue: https://github.com/lowRISC/opentitan/issues/18651
- [x] Add assertion for SDA and SCL not changing at the same time to partially resolve issue: https://github.com/lowRISC/opentitan/issues/18722. Pending merge of: https://github.com/lowRISC/opentitan/pull/18729
- [x] Wait for resolution of ECO issue where timing of restarts can cause them to be interpreted as a stop and then a start: https://github.com/lowRISC/opentitan/issues/18721
- [x] Resolve ECO issue where and SCL glitch happened when the FMT FIFO empties mid-transaction https://github.com/lowRISC/opentitan/pull/18810
- [x] Check that new functional coverage implementation is above 90% coverage in nightlies.
- [x] Update documentation to resolve NAK issue [#18764](https://github.com/lowRISC/opentitan/issues/18764). First, `t_low` and `t_high` must be larger than 2 so that acknowledgements are detected correctly. Second, one is described in the following bullet.
- [x] Update documentation to clarify that when a NAK is received, the IP will still process the rest of the FMT FIFO. There is currently no way for the software to interpose this until this issue is resolved: [#18917](https://github.com/lowRISC/opentitan/issues/18917). This documentation change has been captured in this PR: https://github.com/lowRISC/opentitan/pull/18915

Once all of these tasks are done, we should update the V2 PR that can be found here: https://github.com/lowRISC/opentitan/pull/18211

For visibility here are the people that were involved in the review: @crteja, @hcallahan-lowrisc, @GregAC, @jdonjdon and @msfschaffner.

**Comment by marnovandermaas** [comment]
Added checklist item to wait for ECO issue [#18721](https://github.com/lowRISC/opentitan/issues/18721) to be resolved.

**Comment by marnovandermaas** [comment]
Created an issue to track removing loopback mode from the RTL: https://github.com/lowRISC/opentitan/issues/18742

**Comment by msfschaffner** [comment]
I have checked off the SVA and ECO related items above, since these fixes have been merged.

**Comment by marnovandermaas** [comment]
I added a sub-task to track a new potential RTL issue https://github.com/lowRISC/opentitan/issues/18764

**Comment by marnovandermaas** [comment]
> Added checklist item to check that functional coverage shows up in nightlies and it stays above 90%. The first nightly is in, timestamped at Wednesday May 24 2023 07:09:34 UTC with hash [26b0ee226](https://github.com/lowrisc/opentitan/tree/26b0ee226f4263e31403e9873d1d4e2e999658be). Functional coverage is at 93.24% for this seed. Let's wait for more than one random seed to pass before checking this off.

A week later, timestamped at Wednesday May 31 2023 07:05:13 UTC and hash [0aa089865](https://github.com/lowrisc/opentitan/tree/0aa08986509c76f7d56e9a4d409d65f655d501b1) functional coverage is still above 90%, clocking in at 93.49%. I will check off the corresponding sub-task based on that.

**Comment by marnovandermaas** [comment]
> I added a sub-task to track a new potential RTL issue #18764

I've updated the sub-task to make an update to the documentation as described in this comment: https://github.com/lowRISC/opentitan/issues/18764#issuecomment-1572338226

**Comment by johngt** [comment]
@engdoreis - is writing up SW workaround for I2C NAK. FYI @marnovandermaas 
Captured in #18764

**Comment by marnovandermaas** [comment]
Split the NAK documentation sub-task into two based on the information given in this issue: https://github.com/lowRISC/opentitan/issues/18917 and the following documentation PR: https://github.com/lowRISC/opentitan/pull/18915

**Comment by marnovandermaas** [comment]
Added reference to SCL glitch ECO when FMT FIFO is emptied mid-transaction: https://github.com/lowRISC/opentitan/pull/18810

**Comment by marnovandermaas** [comment]
Checking off last two sub-tasks because of the merging of this documentation PR: https://github.com/lowRISC/opentitan/pull/18964
