### ISSUE TITLE
[spi_host,dv] Capture outstanding DV TODOs for M2.5 milestone

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#18886]
### Description

The PR https://github.com/lowRISC/opentitan/pull/18887 captures the outstanding TODOs against this issue.

- [ ] https://github.com/lowRISC/opentitan/pull/18887/commits/68220c1a7c6698f584b28c06a54664ea3cfb3bef#diff-6b99091a0adff92907312eede55ddee498e4c65c3a113783dab57328f489fc2fR10 : Captures the fact that we currently only perform verification against NUM_CS=1 (single CSB).
- [ ] https://github.com/lowRISC/opentitan/pull/18887/commits/68220c1a7c6698f584b28c06a54664ea3cfb3bef#diff-efe52f816c8593e255e91c8bbf9ae1f0fd702d5927d037e9ef93d008328ef1c9R36 : Captures that the stress_tests.hjson generic testcases have not yet been enabled, but this is a V3 task.
- [ ] All other items constitute testbench improvements that are nice-to-have.

**Comment by msfschaffner** [comment]
Closing since SPI_HOST has been signed off.
Please re-open if that is not accurate.

**Comment by msfschaffner** [comment]
SG - thanks @andreaskurth!

**Comment by moidx** [comment]
Only `NUM_CS=1` is supported in the version of the block integrated into `Earlgrey-PROD`. 

@hcallahan-lowrisc to align documentation.
