### ISSUE TITLE
[pwrmgr/sram_ctrl] Use synchronizers on all LC signals

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#19051]
### Description

As part of the audit in #19044, we identified that the following life cycle signals are not properly synchronized with `prim_lc_sync`:
- [x] `lc_dft_en_i` in `pwrmgr` #19120
- [x] `lc_hw_debug_en_i` in `pwrmgr` #19120
- [x] `lc_hw_debug_en_i` in `sram_ctrl` #19120
- [x] `otp_en_sram_ifetch_i` in `sram_ctrl` #19120

For Earlgrey ES, this is not critical since:
- `pwrmgr` has the same clock root as `lc_ctrl`, and hence the signals are synchronous
- `sram_ctrl` is not used while `lc_ctrl` and `otp_ctrl` are initialized, and hence there is enough time for the signals to stabilize after initialization.

For PROD and other integrations, though, this should be cleaned up.

CC @moidx
