### ISSUE TITLE
[sw/silicon_creator] Boot services infra

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#19130]
[OpenTitan Boot Services: Intro and Data Structures](https://docs.google.com/document/d/1TxTa_htOGDr3MVyW-Sz2jGgEWArnbLxBJHKpz7qQ3KY/edit)

  - [x] Common message header (#19135, #19137)
  - [x] Empty message (#19142)
  - [x] `boot_svc_header_check()` (#19193)
  - [x] Retention SRAM field (#19185)
