### ISSUE TITLE
[chip-test,si-val] chip_sw_edn_sw_mode

### ISSUE THREAD

**Issue by h-filali** [lowRISC/opentitan#20021]
### Test point name

[chip_sw_edn_sw_mode](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_edn_testplan.hjson)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

@vogelpi @h-filali

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes): **no existing test covers this testpoint**
- [ ] Device-side (C) component developed: **in PR #20022**
- [ ] Bazel build rules developed: **in PR #20022**
- [x] Host-side component developed: **none required**
- [x] HJSON test plan updated with test name (so it shows up in the dashboard): **testpoint exists in testplan**
- [ ] Test added to dvsim nightly regression (and passing at time of checking): **in PR #20022**
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression: **to be checked in PR #20022**

**Comment by andreaskurth** [comment]
@h-filali Can you please edit the checklist items in the description to say "in PR #20022" instead of "in upcoming PR"?

**Comment by h-filali** [comment]
@andreaskurth sure!
