### ISSUE TITLE
[top_darjeeling] watch dog reset should be mapped to bit 0

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#20415]
### desc

Earlgrey uses bit 1 of [pwrmgr.reset_en](https://opentitan.org/book/hw/top_earlgrey/ip_autogen/pwrmgr/doc/registers.html#reset_en), while Darjeeling uses bit 0 for watch dog reset enable.
All legacy tests use `dif_pwrmgr_set_request_source` should uses `kDifPwrmgrResetRequestSourceOne` instead of
`kDifPwrmgrResetRequestSourceTwo`. By grepping sw/device/tests*, following tests have this issue.

- [x] sw/device/tests/aon_timer_sleep_wdog_sleep_pause_test.c -- chip_sim_cfg target doesn't exist. 
- [x] sw/device/tests/aon_timer_wdog_bite_reset_test.c -- fixed by #20447 
- [x] sw/device/tests/clkmgr_off_peri_test.c -- fixed by #20429 
- [x] sw/device/tests/clkmgr_off_trans_impl.c -- fixed by #20429 
- [x] sw/device/tests/flash_ctrl_idle_low_power_test.c -- chip_sim_cfg target doesn't exist. 
- [x] sw/device/tests/pwrmgr_wdog_reset_reqs_test.c -- fixed by #20483 
- [x] sw/device/tests/rstmgr_alert_info_test.c -- fixed by #20429 
- [x] sw/device/tests/rstmgr_cpu_info_test.c -- fixed by #20416 
- [x] sw/device/tests/sim_dv/pwrmgr_random_sleep_all_reset_reqs_test.c -- chip_sim_cfg target doesn't exist. 
- [x] sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c -- fixed by #20483 
- [x] sw/device/tests/sim_dv/pwrmgr_deep_sleep_all_reset_reqs_test.c -- chip_sim_cfg target doesn't exist. 
- [x] sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c -- chip_sim_cfg target doesn't exist. 
- [x] sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test.c -- fixed by #20447

**Comment by matutem** [comment]
@jdonjdon all boxes are checked-off above. Should we close this issue?
