### ISSUE TITLE
[sw, tock] Tock downstream (strategy, todo, issues)

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#2139]
**INTRODUCTION**

Upstream OpenTitan implementation is not using [C DIFs](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/README.md). This means that we cannot develop the peripheral drivers directly in upstream. The idea is to maintain our own downstream board, chip and any additional crates.

The intention is, **where possible**, to use all main Tock OS crates from the upstream as they are.

**STRATEGY**

- It has been decided to change the directory layout to better represent the OpenTitan components, as well as some changes to allow for simpler downstream/upstream integration (all upstream dependencies should be split out in their own crate). However, major components are still under top level `boards` and `chips` directories (consistent with the upstream).

- We already have `boards/opentitan` in the source control, which is out of date with the upstream (earlier revision), so the `ibex` and `lowrisc` crates of the same revision were taken.

- We are taking `/src` from `ibex` and `lowrisc` crates almost entirely as they are, with minor modifications where necessary to work with the new directory layout and crate split (`use ...` in source files). The idea is to refactor and tidy up any source files as we refactor the corresponding source files to use DIFs. It is impractical to do it the other way around as it would result in too much redundant work.

**ISSUES**

- [x]  `OT_SPLASH` in `main.rs` is not printed out (existing issue on HEAD, **only tested on verilator**) @jon-flatley , could you please have a look?

- [ ] We need to think about how we handle failures in a driver. For example, it used to be that functions like `disable_tx_interrupt` couldn't fault. With calls to `dif_uart_irq_enable` and `dif_uart_irq_state_clear` inside this function, it is no longer the case (#2211 ).

- [ ] Building Tock by default **(no conclusion, open topic)**.

- [ ] How to handle tock in CI, and automated updates with the upstream **(no conclusion, open topic)**.

**TODO FIRST STAGE**

- [x] Extend downstream Tock development infrastructure, and new layout (#2119).

- [x] Create DIF C bindings (#2129).

- [x] Link against DIF libraries (#2129).

- [x] Refactor/implement UART driver to use DIFs (#2154).

- [x] Unforeseen necessary changes (None so far).

**TODO SECOND STAGE**

- [ ] Make sure that the follow-up comments from #2154 are addressed.

- [ ] Improve DIF C bindings generation:

- Split DIF bindings each into their own .rs file (currently all in `dif_bindings.rs`).

- Generate bindings for `mmio`.

- Generate bindings for `hw/top_earlgrey/sw/autogen/top_earlgrey.{c,h}` and link against the library. Possibly split out/rename `dif` crate, if it does more than just DIF bindings.

- General improvements to the quality and ease of use.

- [ ] Refactor/implement other drivers to use DIFs (please see review comments from @mcy in #2129 . They will come in useful).

- [ ] Sync up with upstream HEAD for the Tock dependencies.

- [ ] Drop explicit revision for Tock dependencies in `Cargo.toml` **(potentially, no conclusion yet)**.

- [ ] Use a single `.rs` for peripheral driver instantiation instead of using a `.rs` for each peripheral. I don't see much point in having a separate source file for every chip peripheral in `chip/earlgrey` just to instantiate this peripheral. I think it makes sense have the instantiations under a single source file, like `chips/earlgrey/peripherals.rs` **(potential, no conclusion, minor importance)**.

**Comment by silvestrst** [comment]
@gkelly @lenary

**Comment by silvestrst** [comment]
Please let me know if you guys think something needs adding/removing, and in general your opinion on this.

**Comment by lenary** [comment]
Thanks for writing this up! This largely matches my understanding of the next few steps, and I do agree that most things in Step 1 are blocking almost all other downstream tock work, so are our priority at the moment.

I think "Sync up with upstream HEAD for the Tock dependencies." and "Drop explicit revision for Tock dependencies in Cargo.toml." could be the same item? I'm not sure, given we may want to keep an explicit revision around.

**Comment by silvestrst** [comment]
> I think "Sync up with upstream HEAD for the Tock dependencies." and "Drop explicit revision for Tock dependencies in Cargo.toml." could be the same item?

We can merge them, I don't mind either way.

> I'm not sure, given we may want to keep an explicit revision around.

I think @jon-flatley is suggesting to use `.lock` file for that - if I understand correctly that is a common practice when working with cargo and tock.

**Comment by lenary** [comment]
Ok, that makes sense as a plan of action for Syncing with HEAD / Cargo.lock.

One task we haven't yet looked at but need to put on the roadmap: building tock in CI, and building it by default. These are probably two different issues, and do not block anything in the list you've prepared so far.

**Comment by silvestrst** [comment]
> building tock in CI, and building it by default.

Good point! I think we probably should add it here for good measure maybe as `TODO THIRD STAGE`?

**Comment by gkelly** [comment]
Thanks for writing this out @silvestrst! In the second stage, are the first and last item at odds with each other? @jon-flatley and I discussed this earlier, but we had also considered some form of CI to bump the upstream version reference. If we directly track HEAD it's possible that we get presubmit breakages for unrelated changes and then have to chase them down. If we bump only when our tests pass then we won't have unrelated breakages in our master and can chase the tock breakage independently.

**Comment by silvestrst** [comment]
> In the second stage, are the first and last item at odds with each other?

I think I just didn't explain well enough what I meant:

The first item - concerns the `dif` crate. Split out generated dif bindings into their own `.rs` files, instead of one large `.rs` containing DIF bindings for all DIFs.

The last item - concerns `earlgrey` crate, more specifically there are `.rs` files for every peripheral. They take the corresponding peripheral from `opentitan_common` crate and crate an instance of a peripheral `UART0`, ... Basically at this point we feed in frequency and base address. I just thought that there is not much point of having instantiation for the chip peripherals in separate `.rs` files.

That was just my thinking, but I might be missing something, in which case we can keep instantiation in for peripherals in separate files.

> If we directly track HEAD it's possible that we get presubmit breakages for unrelated changes and then have to chase them down.

Doesn't keeping `.lock` under the source control solve this problem? I guess maybe there is slight misunderstanding? By `Drop explicit revision for Tock dependencies in Cargo.toml.` I meant, remove explicit `rev=` and instead start tracking `.lock` file.

**Comment by jon-flatley** [comment]
> I think @jon-flatley is suggesting to use .lock file for that - if I understand correctly that is a common practice when working with cargo and tock.

I think this is the preferred way to pin to upstream revisions on binary targets since for moving to new versions we can just use `cargo update`. That said, I don't think it's as clear cut for us since this requires meson shuffling around two `Cargo.lock` files, one for upstream tock and one for local builds.

The more I think about it the more I think it may be best to leave the `rev =` in `Cargo.toml`. The reason for this? Cargo allows for specifying which `Cargo.toml` to build from, but offers no such solution for `Cargo.lock` files. You can see the `--manifest-path` flag in the [`cargo build` command line documentation](https://doc.rust-lang.org/cargo/commands/cargo-build.html). If we want to move away from the clunky symlink gymnastics we could take this route, but that means ditching the `Cargo.lock` solution. I don't think that would be a big deal; probably just slightly more work for CI automation down the road.

> Drop explicit revision for Tock dependencies in Cargo.toml.

By the explanation above, maybe this isn't needed.

**Comment by jon-flatley** [comment]
> If we directly track HEAD it's possible that we get presubmit breakages for unrelated changes and then have to chase them down. If we bump only when our tests pass then we won't have unrelated breakages in our master and can chase the tock breakage independently.

IIUC this can be done in two ways:

1. Keep a `Cargo.lock` file tracked by git and update this in CI with `cargo update`. Do this regularly, and only if the rev bump still allows for a successful build with tests passing.
2. Keep no `Cargo.lock` files in source control, just let cargo generate them and we `.gitignore` them. Use `rev =` in the `Cargo.toml` to pin the tock version and have a tool in CI to parse the toml and do the rev bump.

I don't think 2 is too much more complicated, and it gives us the ability to leverage `--manifest-path`.

> Doesn't keeping .lock under the source control solve this problem? I guess maybe there is slight misunderstanding? By Drop explicit revision for Tock dependencies in Cargo.toml. I meant, remove explicit rev= and instead start tracking .lock file.

The `.lock` file in this situation doesn't provide any additional utility afaict. The only benefit is that it is autogenerated and easy to update to the new HEAD.

**Comment by silvestrst** [comment]
I think I understand where my confusion was coming in, thanks @lenary . If I understand correctly, you were thinking of extending CI capabilities beyond what they are now - from simply building the changes, to also updating the tock revision automatically?

Would you guys like me to edit some of the tasks? Feel free to edit them yourselves, just drop a note in a comment if you do.

Maybe you guys could open another issue describing the planned CI work, and steps?

**Comment by imphil** [comment]
You could have a look at dependabot, which can do Cargo.lock updates.

**Comment by alphan** [comment]
> OT_SPLASH in main.rs is not printed out (existing issue on HEAD, only tested on verilator) @jon-flatley , could you please have a look?

@silvestrst, did you change the chip frequency and baud rate to match what verilator expects?

**Comment by alphan** [comment]
> We need to think about how we handle failures in a driver. For example, it used to be that functions like disable_tx_interrupt couldn't fault. With calls to dif_uart_irq_enable and dif_uart_irq_state_clear inside this function, it is no longer the case.

I think it would depend on a number of factors such as
* the type of the peripheral: is it stateless (besides some trivial configuration) or does it have some sort of a state?
* is the failure something that can be reasonably expected and handled during normal operation, e.g. due to noise/interference, or is it indicative of a hw/sw issue (which should probably be logged and addressed) or a security issue?
* can the driver resolve the issue transparently or do the clients need to know about this failure?
* and so on.

I think it would be helpful to identify different failures and how they should be handled in a doc to ensure consistency and to avoid spend time on things that are already done. It would also be very helpful, at least for me, to have a clear guideline on how to decide if a failure is a security issue.

**Comment by alphan** [comment]
> You could have a look at dependabot, which can do Cargo.lock updates.

Thanks for mentioning this @imphil. It looks like it is free to use (was acquired by github and will be integrated to it) and [can update both Cargo.toml and Cargo.lock](https://dependabot.com/rust/) so we don't need any CI changes to update tock.

**Comment by alphan** [comment]
> Generate bindings for mmio.

Since we have DIF libraries, do we really need this?

**Comment by alphan** [comment]
Thanks for writing this @silvestrst!

**Comment by silvestrst** [comment]
In response to @alphan comments:

**Comment by silvestrst** [comment]
We will also have to generate bindings for `hw/top_earlgrey/sw/autogen/top_earlgrey.{c,h}` which will be used outside of DIFs (in the drivers).

**Comment by silvestrst** [comment]
It seems that the `OT_SPLASH` is working again, does anyone know what PR could have fixed it?

**Comment by silvestrst** [comment]
Redundant, DIFs are not production code.
