### ISSUE TITLE
[rom] update ROM to use secure boot in OTP

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#21551]
Recently, #21270 added OTP partitions for ROM secure boot keys and key policies.
The ROM must be updated to use these secure boot keys, instead of those baked into the ROM, which must be removed.

# Tasks
- [x] Update the default OTP images to emulate fake (fixed) RSA and SPX+ pubkeys being provisioned.
- [x] Remove existing RSA/SPX+ keys from the ROM.
- [ ] Update sigverify stack to use the ROM keys / policies from OTP. 
  - [x] https://github.com/lowRISC/opentitan/pull/23246
  - [ ] https://github.com/lowRISC/opentitan/pull/23266
