### ISSUE TITLE
[entropy_src] Backpressure handling follow-up work

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#21855]
### Description

What is left from #21799 for after M2:

- [x] Adding an SVA to ensure the FIFOs are indeed emptied before the conditioner runs, see #23877.
- [x] Documentation, see #22324.
- [x] Adjusting @pamaury 's observe mode TLT/SiVal test to check the new alert bit, see #23875.
- [ ] Ironing out remaining test failures, see #23893.

**Comment by vogelpi** [comment]
We should do this for M5. Discussed with @h-filali that this one of the next things to investigate after coverage closure.

IIRC, I've only noted test failures due to backpressure in the rng_max_rate test.
