### ISSUE TITLE
[top_earlgrey] Area optimizations for production

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#22025]
### Description

This is a tracker for area optimizations that are in flight for Earlgrey PROD.

Planned for RC1:
- [x] *kmac*: Switch PRNG from Trivium to Bivium #22021 
- [x] *entropy_src*: reduce depth of esfinal FIFO #22041
- [x] *uart*: reduce TX buffer size from 128B to 32B #22026
- [x] *uart*: reduce RX buffer size from 128B to 64B #22046
- [x] *rv_core_ibex*: remove 8 performance counters #22047
- [x] *csrng*: more fine-grained parametrization of AES to remove unneeded datapaths #22056
- [x] *csrng*: remove redundant state copies in state database #22064

Planned for RC2:
- [x] *flash_ctrl*: Share the scrambling module between two banks #22045
- [x] *entropy_src*: reduce depth of observe FIFO #22087 

Planned for RC3:6000
- [x] #22159

Deferred:
~- [ ] Reverting of #22045 due to problems found in #22089; deferred because likely not a bug, see #22191~ It turned out to be an RTL bug but this got fixed by #22276 

The list only contains optimizations that have been approved. More ideas are captured in [this document](https://docs.google.com/spreadsheets/d/1uZ79DLd08nX7gYJlmsNF_QhiHITyCkgwTxe4lKnuGsg/edit).

**Comment by msfschaffner** [comment]
FYI @zi-v @arnonsha @msfschaffner @OTshimeon 
This is where we tracked approved optimizations.

**Comment by andreaskurth** [comment]
Closing as completed (at least for now).
