### ISSUE TITLE
[crypto] Outstanding test failures in ECDSA and RSA

### ISSUE THREAD

**Issue by RyanTorok** [lowRISC/opentitan#22322]
### Description

Several outstanding test failures exist for RSA and ECDSA in the cryptotest framework.

RSA:

- [ ] `wycheproof RSA-2048 pss verify sha-384 #64`
- [ ] `wycheproof RSA-3072 pss verify sha-256 #94` 
- [ ] `wycheproof RSA-4096 pss verify sha-256 #31`
- [ ] `wycheproof RSA-4096 pss verify sha-384 #9`
- [ ] `wycheproof RSA-4096 pss verify sha-384 #33`
- [ ] `wycheproof RSA-4096 pss verify sha-512 #164`
- [ ] `NIST CAVP RSA-3072 Verify PSS SHA-{256, 384, 512}` unconditionally returns "fail"

ECDSA: 

- [ ] `wycheproof p256 verify sha-256 #350` 
- [ ] `wycheproof p256 verify sha-512 #420` 
- [ ] `wycheproof p256 verify sha3-256 #358` 
- [ ] `wycheproof p256 verify sha3-512 #424`

**Comment by vsukhoml** [comment]
I requested NIST ACVP tests for many of the combinations and got sample test vectors. I can add those in addition to wycheproof if this helps.

**Comment by RyanTorok** [comment]
ECDSA test failures resolved by #22393

**Comment by moidx** [comment]
Removing the `ROM` label as we are no longer using RSA for secure boot.

**Comment by johannheyszl** [comment]
@andrea-caforio to PTAL

**Comment by nasahlpa** [comment]
Closing as the ECDSA tests are passing and the remaining failing RSA verify tests are documented in https://github.com/lowRISC/opentitan/issues/28656.
