### ISSUE TITLE
[pinmux] Remove AST_MISC pad, add IE bit for all pads

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#22990]
### Description

As per email by @meisnere , we should make the following two changes:
- [x] Remove the AST_MISC pad (will be replaced by a VSS supply pad) --> #22995
- [x] Add an IE control bit for each pad for leakage control --> #23042
  - [x] including also some manual pads (see email) --> #23107

**Comment by andreaskurth** [comment]
Closing as completed in #22995, #23042, and #23107.
