### ISSUE TITLE
[i2c] V2(S) checklist items

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#23077]
### Unimplemented Testpoints
- [x] target_fifo_watermark #23142
- [x] host_mode_config_perf #23543 
- [x] host_mode_clock_stretching #23543 
- [x] target_mode_tx_stretch_ctrl #23186
- [x] target_mode_nack_generation #23192 
- [x] host_mode_halt_on_nak #23940

### Regression
https://reports.opentitan.org/hw/ip/i2c/dv/2024.05.10_04.25.29/report.html 
- [x] https://github.com/lowRISC/opentitan/pull/23987
- A sampling of testpoints with low passrates. This is no-longer accurate for master, as it was observed on 10/05/24, but the same thresholds for V2 signoff still apply. The above PR should bring everything back up to the requisite level.
  - i2c_target_perf 0%
  - i2c_target_unexp_stop 8%
  - i2c_target_stress_all 12%

### Cov
- [ ] FSM 83.3%

### Open Issues (effort tracked against each issue)
Also see [#21755](https://github.com/lowRISC/opentitan/issues/21755) for previous discussion.
- [x] #23078
- [ ] ~~#17822~~ -> M7 
- [x] #23078 This issue was split out from the following:
  - [ ] ~~#21887~~ -> M7
- [x] #22347 

### Signoff Process (effort tracked against this issue)
#22108
