### ISSUE TITLE
[sensor_ctrl,OTP] Implement AST alert reset configuration and post-reset behavior

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#23149]
As described in [this implementation recommendation](https://docs.google.com/document/d/1KTAkLexrTPsEyJrMc6Auxiuxdv161GdEnyTbjLDY6Fw/edit): At reset we want all alerts in sensor_ctrl to be enabled and set to recoverable. During ROM boot and _before_ alert_handler is configured, we want ROM to read OTP values (from the `OWNER_SW_CFG` OTP partition) to disable specific alerts in sensor_ctrl or set them to fatal.

## TODOs
- [x] Change the reset value of sensor_ctrl’s ALERT_EN CSRs to `MuBiTrue`.
  --> #23152
- [x] Mention this design in sensor_ctrl’s documentation.
  --> #23152
- [x] Add a section in the `OWNER_SW_CFG` OTP partition to store the sensor_ctrl alert configuration as well as one section to store its digest (one for all LC states should be sufficient).
  --> #23155

Note that this issue is about changes to sensor_ctrl RTL and OTP partitions. See #23150 for the changes to ROM.
