### ISSUE TITLE
[test-triage] `sram_ctrl/{main,ret}:sram_ctrl_access_during_key_req`

### ISSUE THREAD

**Issue by HU90m** [lowRISC/opentitan#23445]
### Hierarchy of regression failure

Block level

### Failure Description

UVM_ERROR @ 2643137251 ps: (sram_ctrl_scoreboard.sv:422) [uvm_test_top.env.scoreboard] Check failed cfg.in_key_req == 0 (1 [0x1] vs 0 [0x0]) No item is accepted during key req

### Steps to Reproduce

GitHub Revision: [8cb25a6867](https://github.com/lowrisc/opentitan/tree/8cb25a6867a60d63e35fdb9be5a1846ffce52665)

```sh
./util/dvsim/dvsim.py hw/ip/sram_ctrl/dv/sram_ctrl_main_sim_cfg.hjson -i sram_ctrl_access_during_key_req \
    --build-seed 26638040090898561482658723926798947801831709189350919955228328310045202344042 \
    --fixed-seed 21722448729744331598640260736581014511925356750467183438647933604033204189065
```

The two changes made to this block between it passing and failing are https://github.com/lowRISC/opentitan/pull/23212 and https://github.com/lowRISC/opentitan/pull/23292 .

### Tests with similar or related failures

*The following also broke at the same time.*
- [ ] [`sram_ctrl/main:sram_ctrl_stress_all`](https://github.com/lowRISC/opentitan/issues/23444)
- [ ] [`sram_ctrl/ret:sram_ctrl_stress_all`](https://github.com/lowRISC/opentitan/issues/23444)
- [ ] [`sram_ctrl/ret:sram_ctrl_stress_all_with_rand_reset`](https://github.com/lowRISC/opentitan/issues/23444)
- [ ] [`sram_ctrl/ret:sram_ctrl_stress_all_with_rand_reset`](https://github.com/lowRISC/opentitan/issues/23444)
