### ISSUE TITLE
[bazel] Migrating to Bzlmod

### ISSUE THREAD

**Issue by jwnrt** [lowRISC/opentitan#24365]
Full RFC document: https://docs.google.com/document/d/1KQWdo7jeh9JmKn3OgNA-xFYLfR2hyMyJXlL_Rqadnjc/edit?usp=sharing

## Summary

Recent versions of Bazel support a feature called ["Bzlmod"](https://bazel.build/external/overview) which changes how external dependencies are managed. This is opt-in in Bazel 6 (our current version), opt-out in Bazel 7, and required in future versions.

We will eventually need to move to Bzlmod to keep up with Bazel and the ecosystem. It will also likely be required for multitop so that we can use things from old versions of the repo without conflicts.

## Bzlmod overview

* Currently, we have a `WORKSPACE` file which downloads all external dependencies as tarballs and extracts them into a global namespace.
* This is fragile and difficult to maintain. All dependencies (including transitive) must be accounted for by our `WORKSPACE`.
* The global namespace causes conflicts and increases the chance of breakage.
* With Bzlmod, our repository becomes a "module" depending on other modules.
* Modules are namespaced and transitive dependencies are handled automatically.
* Extra features become available due to this uniformity.

## Roadmap

The steps for adopting bzlmod are roughly:

- [x] Ensure all our dependencies support bzlmod.
    - [x] ~~https://github.com/lowRISC/crt still WIP.~~ removing CRT instead.
- [x] Update to dependencies compatible with bzlmod.
  - [x] #24361 - most dependencies
  - [x] #24587 - `rules_rust`.
- [x] #24393
- [x] Enable bzlmod in "hybrid" mode where we use both `WORKSPACE.bzlmod` and `MODULE.bazel`.
  - See #24781  
- [x] Gradually move dependencies from `WORKSPACE.bzlmod` to `MODULE.bazel`.
  - [x] `rules_rust`: #25578 
  - [x] `rules_python`: #25650 
  - [x] Buildifier: #25679 
  - [x] Google rule dependencies: #25680 
  - [x] Plain (non-Bazel) repositories: #25714
  - [x] Manufacturing hooks: #25772 
  - [x] lowRISC C toolchain: https://github.com/lowRISC/opentitan/pull/25810
- [x] Disable hybrid mode #25847 
- [x] Ensure OpenTitan can be used as a dependency
      * Deferred to new issue: #25849 

Most of this work is being experimented with in https://github.com/lowRISC/opentitan/pull/24216.

**Comment by andreaskurth** [comment]
RFC approved by TC on 2024-11-14

@jwnrt are the open tasks above still up-to-date, or can this issue be closed as completed?

**Comment by jwnrt** [comment]
I’ve updated the list with the current progress and next steps. I’ll keep this open until they’re all completed.
