### ISSUE TITLE
[dif/hmac] Outstanding to-do items

### ISSUE THREAD

**Issue by jon-flatley** [lowRISC/opentitan#2920]
This is a list of outstanding items from #1320 that were not included with the first push of the HMAC DIF.

- [ ] `_Static_assert`s for `HMAC_KEY[0-7]_REG_OFFSET` and `HMAC_DIGEST[0-7]_REG_OFFSET` register layouts. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r456941186)
- [ ] Refactoring the result end of a transaction to use `dif_hmac_finish()`. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r458096835).
- [x] Replace doxygen comments with `/** ... */` style. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r458097544)
- [ ] Add `DIF_WARN_UNUSED_RESULT` annotations. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r458183320)
- [ ] Use `bitfield.h` utilities to replace manual bit manipulation. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r458183793)
- [ ] Fix duplicate `CHECK`s. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r458192625)
- [ ] `while {}` not `do {} while`. [link](https://github.com/lowRISC/opentitan/pull/1320#discussion_r458194106)
- [ ] Remove unused enums (hmac mode enum)

**Comment by moidx** [comment]
@timothytrippel Closing as obsolete.
