### ISSUE TITLE
[Tracking][sw] Coverage support

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#3155]
This issue captures remaining tasks for coverage support. Please see also #3080.
* [ ] Tooling for generating coverage reports.
* [ ] Meson coverage support?
* [ ] CI support.
* [ ] While transferring the profile buffer over UART is reasonable for FPGA, it is probably not the best way for DV. We need to understand its overhead and how we can transfer the profile buffer more efficiently.
* [ ] Coverage for tests that run on host, i.e. DIF unittests.

**Comment by imphil** [comment]
For coverage in CI (on FPGAs), the main work item is producing two software builds, one with coverage and one without. We can then run the ones with coverage through the systemtest machinery and fetch the coverage data afterwards. Not hard, just a bit of work.
