### ISSUE TITLE
[flash_ctrl] TODO list for open source portion of flash controller

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3353]
**Functional Portion**
- [x] Add OTP read / write controls to seed info pages
- [x] Add ECC into open source wrapper
- [x] Add memory scrambling address filter
- [x] Add additional types of information partitions
- [x] Add the concept of "write-repair"
- [x] Hookup prng function
- [x] Connect scrambling key and add any req/ack interface if required - may change based on EDN
- [x] Add state in pwrmgr to enable flash controller - flash controller should not initialize until otp is ready
- [x] Update flash parameters to production sizes
- [x] Add support for non-power-of-2 number of pages in both data and information partitions.
- [x] Template flash controller (mainly need to tempalte `flash_ctrl_pkg.sv` and `flash_ctrl.hjson`)
- [x] ~~Change num_words to be EXACTLY the number of words being processed, instead of -1, because this causes endless confusion~~.
- [x] Tweak flash design to use both ack / done when interfacing with flash.  The ack will be used to accept the transaction, and the done will be used to indicate when the transaction is finished.
- [x] Tweak the flash generic model to match above assumption
- [x] Add a program resolution check in program control.  If the resolution check fails, immediately error out the program and do not allow it to go downstream. 
- [x] Add cover points especially in `flash_phy_rd` to make sure we create enough cases to really hit the read pipeline.  Especially back to back reads, reads separated by a few cycles, reads to non-consecutive addresses back to back, etc. (Not for M2.5, should be done afterwards). (#21158)
- [x] Add option to disable read buffering to force initial seed verification to always go through to the real flash.   
- [x] Add an isolated flash partition that can be written during test modes but not read.  This flash partition is only readable once we are in production state. 
- [x] ~For mfg security, define an extra state or otp bit that limits flash test access.~ This is handled directly through nvm_debug_en now. 
- [x] share flash scramble module between banks (Not for M2.5, consider for Future Release) #22045
- [x] Use remaining flash bits for truncated plaintext ECC that can be used 
- [x] split scramble enable / ecc enable for regions.  This will be helpful in storing 3-state metadata for flash memory. 
- [x] ECC for high endurance (3 states -> all 1's, intermediate value, all 0's)
- [x] Add another tlul interface to the prim_flash wrapper used for proprietary configuration.
- [x] Add high endurance indication
- [x] Change generic interface to wrap the flashes in one hierarchy 
- [x] Add a control bit for phy initialization (default this to ON)
- [x] Add support for erase suspend (interface TBD)
- [x] Update rma handling
- [x] ~Add otp connections for redundancy information~ (Handle in flash wrappers directly)
- [x] Move some of the parameters to hjson instead of hardcoding them in the package file. 
- [x] Update connections to life cycle controller, remove stubs (rma request, provision_wr_en/provision_rd_en).
- [x] Update documentation for isolated flash partition
- [x] Create documentation for prim_flash interface

**Hardening Portion**
- [x] pay attention to single points of failure in `flash_mp`. Specifically areas on which ruleset is chosen between hardware requests and software requests.  What is the best way to harden this against glitches? 
- [x] Harden RMA interface and make sure multi-bit inputs are used differently to prevent single points of failures. 

@sriyerg 
@cdgori 

> estimate 8

**Comment by jdonjdon** [comment]
> The shared scramble should be deferred. The cover point on the read pipeline...maybe? I just really wanted to make sure we have hit all kinds of bus access patterns on the flash. Is there any way to review that?

I can create coverpoints at  flash_phy_rd interface as we did for eviction.

**Comment by GregAC** [comment]
Ditching https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease label as we need to check if appropriate coverpoints have been created.

**Comment by GregAC** [comment]
estimate range: 4 - 8

**Comment by jdonjdon** [comment]
#21158 is created to cover flash_phy_rd

**Comment by msfschaffner** [comment]
Thanks @jdonjdon - I am moving this to the backlog for future enhancements.
