### ISSUE TITLE
[OTBN] Get design into V1 stage

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3362]
**With respect to the current version of the OTBN spec**, we need to get the design to D1 stage. See https://docs.opentitan.org/doc/project/development_stages/#hardware-verification-stages for a detailed description of the design stages.

* Documentation:
  * [x] DV plan available #3171 
  * [x] testplan completed and reviewed #3170 
  * [x] Finish DV plan: https://github.com/lowRISC/opentitan/issues/4961
* Testbench (tracked as #3369):
  * [x] DUT instantiated with major interfaces hooked up
  * [x] All available interface assertion monitors hooked up
  * [x] X / unknown checks on DUT outputs added
  * [x] Skeleton environment created with UVCs
  * [x] TLM connections made from interface monitors to the scoreboard 
* Tests (written and passing):
  * [x] Sanity test accessing basic functionality (also part of #3369)
  * [x] CSR / mem test suite 
* Regressions: 
  * [x] Sanity and nightly regression set up

(Estimate doesn't include all the dependent issues linked above.)
> estimate 3

**Comment by imphil** [comment]
The nightly regression is now running. The checklist still contains a couple more items for V1, most of which are documentation/discussion items.

**Comment by rswarbrick** [comment]
We've had a testplan review meeting and PR #5840 adds the extra tests that we agreed on. Once that's merged, all that remains is the signoff commit.

**Comment by rswarbrick** [comment]
I've just gone down the checklist again. There are a couple of items that probably need discussion:
- [**DESIGN_SPEC_REVIEWED**](https://docs.opentitan.org/doc/project/checklist/#design_spec_reviewed): I think we can reasonably say that this has happened? (many times!)
- [**STD_TEST_CATEGORIES_PLANNED**](https://docs.opentitan.org/doc/project/checklist/#std_test_categories_planned): I'm not sure where these test categories should be captured. And I don't honestly believe we've thought seriously about most of the bullet points for any IP, so I'm not sure what this means.

@imphil, @GregAC: Comments?

**Comment by sriyerg** [comment]
> I've just gone down the checklist again. There are a couple of items that probably need discussion:
> 
> * [**DESIGN_SPEC_REVIEWED**](https://docs.opentitan.org/doc/project/checklist/#design_spec_reviewed): I think we can reasonably say that this has happened? (many times!)
> * [**STD_TEST_CATEGORIES_PLANNED**](https://docs.opentitan.org/doc/project/checklist/#std_test_categories_planned): I'm not sure where these test categories should be captured. And I don't honestly believe we've thought seriously about most of the bullet points for any IP, so I'm not sure what this means.
> 
> @imphil, @GregAC: Comments?

The second one is more of a reminder. In larger designs especially, some of those features are often subtle / small and tend to get overlooked (especially if an IP has performance / debug / DFT type features). They are to be captured in the tesplan as applicable. There is nothing mandating these tests to be present (or appropriately waived) - its more of a self-service.
