### ISSUE TITLE
[OTBN] Tracking: Implement big number instruction subset in RTL

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3365]
A tracking issue how we're doing on implementing the big number instruction subset of the OTBN spec. Please use the individual sub-issues to discuss implementation.

* [x] Arithmetic: #2953 
  * BN.ADD
  * BN.ADDC
  * BN.ADDI
  * BN.ADDM
  * BN.SUB
  * BN.SUBB
  * BN.SUBI
  * BN.SUBM
* [x] Logical: #2953 
  * BN.AND
  * BN.OR
  * BN.NOT
  * BN.XOR
  * BN.RSHI
* [x] Compare & Co.: #3366 
  * BN.SEL
  * BN.CMP
  * BN.CMPB
* [x] Load/store, data movement: #3367
  * BN.LID
  * BN.SID
  * BN.MOV
  * BN.MOVR
* [x] special-purpose register access: #3368
  * BN.WSRRS
  * BN.WSRRW
* [x] Multiplication: #3363. See also https://github.com/lowRISC/opentitan/issues/2979 for a potential spec change around flags.
  * BN.MULQACC
  * BN.MULQACC.WO
  * BN.MULQACC.SO
