### ISSUE TITLE
[keymgr] Hardening TODO

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3414]
- [x] remove single point of failure between data loading into key state vs software registers
- [x] increase hamming weight of operations command
- [x] increase hamming weight of state space
- [x] do more / better data sanity checks (seems like keymgr->kmac key/data checks are not there)
- [x] allocate more bits to version checks
- [x] check variable array indexing (for example cnt in keymgr_kmac_if).  If the cnt is switched to some large value, it could end up indexing nowhere and the behavior would be unpredictable.  Make these arrays all powers of 2 and zero out the portions that are not used. 
- [x] Make sure to hook-up to `edn`, and also hook-up to the random constants distribution
- [x] Move constants in `keymgr_pkg.sv` to `top_pkg.sv` so there is a single, convenient location to handle them per project.  Also make sure to populate these with the proper values (hopefully random for most of them)
- [x] make hw key select a mubi signal
