### ISSUE TITLE
[sw, dif_rstmgr] Follow-up changes required

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#3454]
# DIF Rstmgr is not complete

## Actions outstanding:

- [x] minor unresolved comments in #3093

- [ ] Revise the `reset` function, should probably check if any of the peripherals is locked and return an error in such case.

- [ ] Find out whether there are any HW timing constraints with asserting and de-asserting software resets.

- [x] Unittests required (#3514 covers only the initial merge APIs)

- [x] Hook-up sanity test to CI (#3996)

- [x] Sanity test required (#3996)

- [x] Add `.md` file

- [x] Any TODOs

- [x] Add API to handle new registers. HW changed (`RSTMGR.ALERT_INFO_CTRL`, `RSTMGR.ALERT_INFO_ATTR` and `RSTMGR.ALERT_INFO`) (#3867)

- [x] `RSTMGR.ALERT_INFO_CTRL`, `RSTMGR.ALERT_INFO_ATTR` and `RSTMGR.ALERT_INFO` unittests (#3867 )

- [ ] It seems that Reset Manager will have shadow registers as well, so need to look into how to handle those

- [ ] Shadow resets (not implemented in the HW yet)

- [ ] Last host state (not implemented in the HW yet)

- [ ] @tjaychen mentioned functionality migrated from Power Manager to Reset Manager (not implemented in HW yet)

- [x] Add clarification comment in the unittest that @mcy asked for (#3996)

- [ ] Add a getter for the alert crash dump size

- [ ] Add specific error code for the `read` not large enough buffer

## Other

- [ ] Refactor if necessary

**Comment by silvestrst** [comment]
@mundaym  do you know the status of this, can it be closed?

**Comment by mundaym** [comment]
Let's keep this open for now until we can review it.
