### ISSUE TITLE
[fpv] formal script issue tracking

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#3611]
improve the csr auto-gen script:
- [x] From PR: https://github.com/lowRISC/opentitan/pull/3583, the spi_device can use macro define to define its hier path in its DV TB.

- [x] Use internal stored value to verify hw read-only registers. (pr #5431) 

General script issue:
- [x] parameter in bind file, check if there is a better to use parameter instead of duplicate the code:
https://github.com/lowRISC/opentitan/pull/4950#discussion_r564086988

**Comment by msfschaffner** [comment]
@cindychip can you update / close this issue?

**Comment by cindychip** [comment]
I think we can close this issue.
