### ISSUE TITLE
[rstmgr] TODO

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4122]
- [x] Separate resets based on power domain
- [x] Optional Add support for shadow resets
- [x] Harden rstmgr to check for rst consistency (i.e., a reset should not assert if its sources are not invoked)
