### ISSUE TITLE
[sw, dif_aes] TODOs

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#4833]
Initial PR is #2413.

- [x] Add CFB mode (Alphan): See #8887
- [x] Add OFB mode (Alphan): See #8887
- [ ] Potentially implement suggestion by Pirmin, see [this](https://github.com/lowRISC/opentitan/pull/2413#pullrequestreview-564441107) thread (Alphan)
- [x] Unit tests (Alphan): See #8887
- [x] Smoke tests (Silvestrs: #4964)
- [x] OT use AES DIF only (refactor any code to use AES DIF instead of directly) (Alphan)
- [ ] keymgr sideload, see  #7835
- [x] Stop mixing up MODE, OPERATION and MANUAL_OPERATION fields of main control register: see #10487

**Comment by silvestrst** [comment]
@vogelpi @asb @gkelly FYI

**Comment by alphan** [comment]
Thanks @silvestrst!

**Comment by silvestrst** [comment]
#4848 seems relevant

**Comment by silvestrst** [comment]
#4781 also relevant (added bits in status register)

**Comment by vogelpi** [comment]
I've ticked some boxes and linked the corresponding PRs + added some new boxes, sorry :-/

@doreis-lowrisc since you have been working on the AES DIF and unit tests before.

**Comment by vogelpi** [comment]
Thinking about recent RTL changes, some more things come to my mind that should be supported by the DIF:
- [ ] Read out IV registers
- [ ] Configure PRNG reseed rate: CTRL_SHADOWED.PRNG_RESEED_RATE
- [ ] Enable/disable PRNG reseeding on key touch: CTRL_AUX_SHADOWED.KEY_TOUCH_FORCES_RESEED
- [ ] Locking the PRNG reseeding on key touch feature: CTRL_AUX_REGWEN
