### ISSUE TITLE
[pinmux] Tracker for various modifications and updates for Silver

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#5221]
This is a feature tracker for all the pinmux improvements and updates that need to go in for Silver.
For a more detailed overview, see also:
- [Pinmux Update Slides](https://docs.google.com/presentation/d/1rOlmQd3sFOfMUaOqlF5O8smUyxBMEpF_0Ehg478v7ck/edit#slide=id.p)
- [Pinmux Programming Model](https://docs.google.com/document/d/1RlB_07q_wVJtBVOjbH-ODKyqCVxIX3-jDm2wY8wGvhs/edit)

High Prio Tasks (for Silver):
- [x] Consolidate pinmux and padctrl, PR https://github.com/lowRISC/opentitan/pull/5128
- [x] Update sleep behavior, add sleep status bits, PR https://github.com/lowRISC/opentitan/pull/5128
- [x] Update wakeup detector connections and configuration, PR https://github.com/lowRISC/opentitan/pull/5128
- [x] Add fine grained CSR lock bits for all multiregs, PR https://github.com/lowRISC/opentitan/pull/5128
- [x] Add HW strap sampling support https://github.com/lowRISC/opentitan/pull/5301
- [x] Add DFT TAP hooks https://github.com/lowRISC/opentitan/pull/5301
- [x] implement JTAG mux (#5486)
- [x] Figure out how to keep the legacy JTAG muxing function for FPGA tops (#5486)
- [x] Rework Hjson datastructure and the associated parts in topgen and the templates (#5793)
- [x] Make padring more parametric such that topgen can propagate the pad configuration from the Hjson down into RTL (either via parameters or a template) (#5793)
- [x] General refactoring of padring and ASIC top-levels, try to share code and make these top-levels more uniform (#5793)
- [x] Bronze-pinout alignments (#5933)
- [x] Add hierarchy for physical instances to padring, connect power sequencing signals (#5793, #6017)
- [x] Add scanrole parameters (#6024)
- [x] Rework WARL behavior of pad attribute CSR (this needs topgen tooling support since the pad type will be defined in then top-level hjson) (#5793)
- [x] Remove some pinmux TODOs, update strap sampling behavior and use RMA instead of the DEV LC state in simulation and emulation such that all DFT and test logic is ungated (#6025)
- [x] Update SDC constraints (#5793)

Related issues: https://github.com/lowRISC/opentitan/issues/892, https://github.com/lowRISC/opentitan/issues/307, https://github.com/lowRISC/opentitan/issues/381, https://github.com/lowRISC/opentitan/issues/295

**Comment by msfschaffner** [comment]
CC: @GregAC @silvestrst @tjaychen @vogelpi

**Comment by msfschaffner** [comment]
I've split out the remaining low-prio tasks as separate issues, such that we can close this one down.
