### ISSUE TITLE
[tlul] transmission integrity todo list

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5450]
- [x] hook up full bus to expanded memories - requires updates to tlul adapter that assumes sram is always multiple of tlul
- [x] hook up integrity error to flash controller and eventually rom checker (latter handled in `rom_ctrl`)
- [x] adjust top level tlul_adapter_sram to pass through integrity where appropriate, flash will require special handling
- [x] hook up command integrity into flash scramble
- [x] hook up error condition from all the `chk` modules 
- [x] add feature to handle integrity passthrough in peripherals (otbn)
- [x] add handling for host integrity feedthrough on data

**Comment by tjaychen** [comment]
@tomroberts-lowrisc 
@GregAC 
@imphil 
@msfschaffner 
@eunchan
