### ISSUE TITLE
[spi_device] pending items to silver milestone

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#5749]
- [ ] support quad I/O addr checker in `readcmd` module
- [ ] double buffering in readcmd
- [ ] add CSRs : e.g) dummy cycle / addr mode / threshold
- [ ] Read STATUS
- [ ] Read SFDP
- [ ] Read JEDEC
- [ ] Upload commands
- [ ] Passthrough: Command filtering
