### ISSUE TITLE
[tracking] [OTBN.H.SEC_WIPE_*] State wiping

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6173]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

This issue tracks collective progress on the features OTBN.H.SEC_WIPE_FULL, OTBN.H.SEC_WIPE_DMEM, OTBN.H.SEC_WIPE_IMEM, and OTBN.H.SEC_WIPE_INTERNAL.

* [x] Document/specify feature in OTBN documentation: https://github.com/lowRISC/opentitan/issues/6955
* [x] Implementation: #7469 (internal wipe)
* [ ] Design Verification
* [ ] DIF/host SW

**Comment by GregAC** [comment]
Note that the PR that introduces scrambling already contains the RTL for requesting new scrambling key/nonce though it's untested (`otbn_scrambled_ctrl.sv` in https://github.com/lowRISC/opentitan/pull/7020). So for the secure wipe of IMEM/DMEM all that is left to do is create the register interface and hook it up to `otbn_scramble_ctrl` plus check it works!

**Comment by GregAC** [comment]
DV is underway for this, any remaining work there will be captured by tracking for V2
