### ISSUE TITLE
[tracking] [OTBN.H.INSTR_COUNT] Provide an instruction count to host software

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6176]
This is a tracking issue covering all aspects of specification and implementation for the feature. Please link to/comment in separate issues for subtasks.

* [x] Document/specify feature in OTBN documentation: Add a line to the list of security features
* [x] Implementation: #6687 
* [x] Design Verification: https://github.com/lowRISC/opentitan/issues/6567
* [x] DIF/host SW (if necessary): #6883

> estimate 8
> remaining 2021-05-17 4

**Comment by imphil** [comment]
@vrozic now only the documentation part is missing. The security features section is now part of the otbn spec as well, can you add a bullet point there to mention the instruction count? (Don't need to repeat the register docs, just to mention it.)

If that's done, you can close this issue.

**Comment by imphil** [comment]
Documentation done in #7239
