### ISSUE TITLE
[alert_handler] Meta Issue tracking alert handler opens

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#6675]
This is a meta bug that tracks alert handler opens.

Hardening:
- [x] Sparse FSM encoding (hardening against FI) https://github.com/lowRISC/opentitan/issues/6674
- [x] Counter duplication (hardening against FI) https://github.com/lowRISC/opentitan/issues/6839 
- [x] Reverse ping mechanism for escalation receivers (hardening against FI and FIB) https://github.com/lowRISC/opentitan/issues/2049
- [x] Introduce shadow registers for the alert handler https://github.com/lowRISC/opentitan/pull/7064
- [x] Further ideas for hardening https://github.com/lowRISC/opentitan/issues/7748

Low-power features:
- [x] In-band reset for alert senders that reside in AON #8174
- [x] Ping-pause feature for clock gated alert senders #8174

Other:
- [x] Make all alerts asynchronous on the top-level https://github.com/lowRISC/opentitan/pull/7063
- [x] Ensure that all escalation receivers are in the same clock/reset domain as the alert handler #8037
- [x] SDC constraints for alert signals (to constrain skew between asynchronous differential wires), spun out into this issue: https://github.com/lowRISC/opentitan/issues/13745

SW Usage:
- [x] Alert handler enablement and HW features for ROM https://github.com/lowRISC/opentitan/issues/6108
- [x] SW alert for Ibex https://github.com/lowRISC/opentitan/issues/5896
- [x] Capture crashdump when entering escalation https://github.com/lowRISC/opentitan/issues/7644
- [x] ~~Cause bit exposure to SW: tie to life cycle or not? https://github.com/lowRISC/opentitan/issues/4902 this issue has been deferred~~
- [ ] Software logging of alerts https://github.com/lowRISC/opentitan/issues/6547
- [x] DIF update #8011

**Comment by msfschaffner** [comment]
@cdgori @tjaychen 
Would it make sense to make the main alert handler config CSRs shadow registers in order to harden it more against glitch attacks?
Obviously that increases the size of the IP quite a bit, but I think the change should be relatively straightforward, given the tooling we already have in place for this.
The `err_update` and `err_storage` signals could then be wired to two new internal alerts in the alert handler (besides the ping and integrity failures).

Here is a prototype implementation that shows how this could look like (this is in a rough state and still needs cleanup):
https://github.com/msfschaffner/opentitan/tree/alert-handler-shadow-regs

**Comment by cdgori** [comment]
@msfschaffner - we spoke about this topic out-of-band and I think your approach (make the config CSRs into shadow regs) is a good one, since we want to (as much as is practical) try to eliminate single-point-of-failure in alert handler.

I don't have the tooling set up to look at your draft tree but when the PR lands I will definitely take a look :)

**Comment by mundaym** [comment]
@cindychip does this need to be added to M2.5?

**Comment by msfschaffner** [comment]
Closing since the hardware parts have all been addressed, and https://github.com/lowRISC/opentitan/issues/6547 can be tracked separately.
