### ISSUE TITLE
[fpga] ChipWhisperer CW310 follow-up tasks

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#6683]
#6614 adds initial support for the ChipWhisperer CW310 board with Xilinx Kintex 7 XC7K410T FPGA. When doing the PR and during the review process, a couple of follow-up items got identified:

Tooling:
- ~[ ] Investigate adding support for SPI Flashing over SAM3X/U to `sw/host/spiflash`, see https://github.com/lowRISC/opentitan/pull/6614#discussion_r637067566~ This could theoretically be done but we dropped support for NexysVideo and kept using `cw310_loader.py` for the ChipWhisperer boards. In the meantime, `opentitantool` is used for bootstrapping FPGA. Once `opentitantool` has the ability to also prep VMEM images for bootstrapping in DV sim, `spiflash` might get removed. See https://github.com/lowRISC/opentitan/pull/12821#issuecomment-1135453310
- ~[ ] Investigate adding support for bitstream flashing over SAM3X/U to `opentitan-pgm-fpga`~ This could theoretically be done by leveraging the FTDI MPSEE interface emulation of the SAM3X/U. However, there are some restrictions on what FPGA pins can be made available to the FTDI MPSEE interface by default. Some of them can be dynamically switched through Python. See https://github.com/lowRISC/opentitan/pull/12633#discussion_r879539230 for details. In the end, we didn't have a strong need for this so far and kept using `cw310_loader.py` instead. In the meantime, we dropped support for NexysVideo and `opentitan-pgm-fpga` got removed with #12821.
- [x] Investigate reducing additional Python dependencies such as `numpy`, `scipy` introduced through the ChipWhisperer Python API, see https://github.com/lowRISC/opentitan/pull/6614#issuecomment-844323063 , see #12832
- [x] Investigate installing the ChipWhisperer Python API not in editable mode
- [x] #8739

Hardware:
- [x] Enable SCA support: need to feed target clock, high-precision trigger signal and UART to the scope board via 20-pin ChipWhisperer connector, see #7513 
- [x] Disable the use of `hw/top_earlgrey/util/top_earlgrey_reduce.py`. See lowRISC/OpenTitan#7369
- [x] Decide on the future of NexysVideo support.
- ~[ ] Enable support for the smaller ChipWhisperer CW310 board with Xilinx Kintex 7 XC7K160T FPGA?~ We are not going to do this for now as it's not clear whether supporting yet another, non-complete FPGA configuration is really worth the effort. We keep supporting the CW305 as we already have quite a few boards of that sort and there is a benefit in terms of noise for power SCA.

**Comment by colinoflynn** [comment]
On reducing `numpy` and `scipy`:

I think `numpy` gets used for some binary list conversion in the CW310 board interface would be the only hit. SciPy should be avoidable. It's listed as a dependency for ChipWhisperer as it will break some of the SCA algorithms, which for most users is important. Longer-term we could add a separate 'chipwhisperer-api' or similar module release which is built from the same code-base but removes the dependency, or if the CW310 API is stable the relevant files could be moved to OT (we have the copyright so this can be done cleanly w/o messing up the copyright notices).

**Comment by a-will** [comment]
Closing, as all tasks have been completed.
