### ISSUE TITLE
 RFC: [sw/testing] OpenTitan Test Framework (OTTF)

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#8015]
## Current On-Device Chip-level Test Framework

![opentitan-test-framework-current](https://user-images.githubusercontent.com/5633066/131586364-864334ab-76d6-482a-b1b7-a0a547d949cd.jpg)

Currently, chip-level tests are executed on-device across three targets (DV, Verilator, and FPGA), using host-side test initiation tools, and a rudimentary on-device test framework, shown in light purple in the figure above. On the host side, two main tools are used to initiate tests on the device. For the DV simulation target, the dvsim.py tool is used, while for Verilator and FPGA targets, the systemtest (pytest) tool is used. Focusing on the device side, for all three targets, the [test_main.{h,c} test framework](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_main.c) (light purple) is used to provide a uniform execution environment for chip-level tests. The [test_main.{h,c} test framework](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/lib/testing/test_main.c) provides boilerplate setup code that configures the UART for communicating messages and test results back to the host.

**Note**: For DV and Verilator simulations,  test statues (i.e. pass/fail) are currently reported through a dedicated RAM segment that the testbench can read directly, which eliminates the need to communicate over (the slow) UART. However for Verilator simulations, logging over UART is also supported. 

## Issues with the Current Chip-level Test Framework

1. It does not support concurrency testing since it lacks a thin operating system layer to switch between concurrent test tasks.

2. It does not provide a mechanism for the test running on the device to communicate with the host to instruct it send stimulation signals, e.g., a I2C test may need to configure the I2C peripheral (via DIFs) then wait for an incoming I2C transaction, by issuing a WFI instruction, from the host, or eventually, the HyperDebug board.
 
3. It is specific to the Earlgrey toplevel, since it makes use of Earlgrey-specific auto-generated header files, which will not scale to future OpenTitan toplevel configurations.

## Proposal

Design a new unified framework for executing OpenTitan chip-level tests (including smoke, IP integration, and system-level tests) across all pre-silicon verification targets (DV simulation, Verilator simulation, FGPA) and post-silicon for bringup. The name of this framework will be the: **OpenTitan Test Framework** (or **OTTF**). This will overcome pitfalls of the Current On-Device Chip-level Test Framework, and will serve as a single endpoint for testing OpenTitan hardware from software, using DIFs, both **_sequentially_** and **_concurrently_**. It will sit on-device, and communicate with host-side test initiation tools, as shown in the System Architecture diagram below.

## System Architecture
![opentitan-test-framework-wott](https://user-images.githubusercontent.com/5633066/131586454-faa289f4-7705-420c-b8fb-1b9077934fe0.jpg)

## Design 
The OTTF will be comprised of the following components, as shown in the System Architecture diagram  below:
- a **lightweight OS** ([FreeRTOS](https://www.freertos.org/index.html)) for executing both sequential or concurrent tests,
- a test server, that:
    - initializes the test infrastructure on the device, including the lightweight OS,
    - opens and maintains a communication channel with the test initiator on the host,
    - launches a single or set-of tests using well-defined commands from the host,
    - communicates external stimuli requests to the host, and synchronizes this stimuli to running tests,
    - aggregates and reports test results to the host, and
    - tears down all on-device test infrastructure upon test completion, and
- a dedicated UART communication channel that interfaces to opentitantool, the host-side test initiation tool that is currently under development.

**Comment by tjaychen** [comment]
this looks pretty good overall, my main concern is that i'm not sure if `OTTF` will be too heavy for the DV environment ( we won't know until we try).   But usually DV directed test cases are VERY baremetal, so if there's a layer of software coordination on top (especially it's an OS), it could potentially slow things down dramatically.

**Comment by tjaychen** [comment]
for this part specifically 

```
It does not provide a mechanism for the test running on the device to communicate with the host to instruct it send stimulation signals, e.g., a I2C test may need to configure the I2C peripheral (via DIFs) then wait for an incoming I2C transaction, by issuing a WFI instruction, from the host, or eventually, the HyperDebug board.
```
I know @sriyerg had planned a lightweight mechanism for DV.  The main thing that's different between DV and FPGA is that DV has a lot of backdoor capabilities that can really reduce the "software" burden on the system.  So if there's any way we can leverage OTTF to take advantage of that, i think it would be best.  As an example, DV has a "fake" ram it can use to communicate with the "host".  So this saves us from having to actually go through a peripheral interface, and the host can simply magically reach into this virtual memory and get information.   I think it would be good to have that kind of function.  This might already be part of your plans and it's just not clear to me at the moment.

**Comment by timothytrippel** [comment]
> this looks pretty good overall, my main concern is that i'm not sure if `OTTF` will be too heavy for the DV environment ( we won't know until we try). But usually DV directed test cases are VERY baremetal, so if there's a layer of software coordination on top (especially it's an OS), it could potentially slow things down dramatically.

Great point to bring up, and its something we are considering in the full design doc/RFC. There are some performance measurements  planned in the near future. Also, for non-current tests, we can disable the timer-interrupt driven scheduler tick of the OS so the only overhead is about the same initialization used by the current test_main.c. (Obviously this needs to be measured, but I expect it to be about the same).

**Comment by timothytrippel** [comment]
> for this part specifically
> 
> ```
> It does not provide a mechanism for the test running on the device to communicate with the host to instruct it send stimulation signals, e.g., a I2C test may need to configure the I2C peripheral (via DIFs) then wait for an incoming I2C transaction, by issuing a WFI instruction, from the host, or eventually, the HyperDebug board.
> ```
> 
> I know @sriyerg had planned a lightweight mechanism for DV. The main thing that's different between DV and FPGA / ASIC is that DV has a lot of backdoor capabilities that can really reduce the "software" burden on the system. So if there's any way we can leverage OTTF to take advantage of that, i think it would be best. As an example, DV has a "fake" ram it can use to communicate with the "host". So this saves us from having to actually go through a peripheral interface, and the host can simply magically reach into this virtual memory and get information. I think it would be good to have that kind of function. This might already be part of your plans (since I see the UART connection is not used for DV / verilator) and it's just not clear to me at the moment.

Yes, I was aware of the current DV communication mechanism, and the goal is to keep this in place. This bit of "fake ram" is put in place by the linker script I believe, and since I use the same linker script to build the OS image (with the test server and test(s) baked in) this is still in place. That was why the UART connection was not used for DV/Verilator, b/c I figured we would probably use the same mechanism already place. I could label the DV/Verilator connection "shared memory" or something like that? Sorry I should have made that more clear.

**Comment by tjaychen** [comment]
o it's not a problem. I like how clean the diagram is, I wouldn't clutter
it.
But it would be good to have a small piece of text discussing the deltas
between DV / Verilator and FPGA / ASIC

**Comment by sriyerg** [comment]
> for this part specifically
> 
> ```
> It does not provide a mechanism for the test running on the device to communicate with the host to instruct it send stimulation signals, e.g., a I2C test may need to configure the I2C peripheral (via DIFs) then wait for an incoming I2C transaction, by issuing a WFI instruction, from the host, or eventually, the HyperDebug board.
> ```
> 
> I know @sriyerg had planned a lightweight mechanism for DV. The main thing that's different between DV and FPGA / ASIC is that DV has a lot of backdoor capabilities that can really reduce the "software" burden on the system. So if there's any way we can leverage OTTF to take advantage of that, i think it would be best. As an example, DV has a "fake" ram it can use to communicate with the "host". So this saves us from having to actually go through a peripheral interface, and the host can simply magically reach into this virtual memory and get information. I think it would be good to have that kind of function. This might already be part of your plans (since I see the UART connection is not used for DV / verilator) and it's just not clear to me at the moment.

Completely replacing the existing test framework (`test_main`) with OTTF especially for the DV simulations would be the right way to go ONLY if it does not worsen the sim runtime by over 10%. Do we all agree here? We ought to be doing the performance measurements now rather than later. I agree with @tjaychen - it will be good to clearly document what's works differently across the testing platforms. 

Also note that the Verilator uses the fake mem only to signal whether the test passed or failed. It uses the on-device UART for logging.

**Comment by timothytrippel** [comment]
> > for this part specifically
> > ```
> > It does not provide a mechanism for the test running on the device to communicate with the host to instruct it send stimulation signals, e.g., a I2C test may need to configure the I2C peripheral (via DIFs) then wait for an incoming I2C transaction, by issuing a WFI instruction, from the host, or eventually, the HyperDebug board.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know @sriyerg had planned a lightweight mechanism for DV. The main thing that's different between DV and FPGA / ASIC is that DV has a lot of backdoor capabilities that can really reduce the "software" burden on the system. So if there's any way we can leverage OTTF to take advantage of that, i think it would be best. As an example, DV has a "fake" ram it can use to communicate with the "host". So this saves us from having to actually go through a peripheral interface, and the host can simply magically reach into this virtual memory and get information. I think it would be good to have that kind of function. This might already be part of your plans (since I see the UART connection is not used for DV / verilator) and it's just not clear to me at the moment.
> 
> Completely replacing the existing test framework (`test_main`) with OTTF especially for the DV simulations would be the right way to go ONLY if it does not worsen the sim runtime by over 10%. Do we all agree here? We ought to be doing the performance measurements now rather than later. I agree with @tjaychen - it will be good to clearly document what's works differently across the testing platforms.
> 

Agreed. The next priority task with the OTTF (once approval has been granted to check-in the prototype code) is a performance measurement. So this will become clear very soon.

> Also note that the Verilator uses the fake mem only to signal whether the test passed or failed. It uses the on-device UART for logging.

 I have documented this above and in the design doc.

**Comment by timothytrippel** [comment]
# Task Burndown

_Addressed in: #7877_
- [x] Vendor in FreeRTOS kernel


_Addressed in: #7938_
- [x] Setup OTTF meson build target to x-compile FreeRTOS to RV32I
- [x] Setup main OTTF entry point that inits UART (similar to existing test framework)
- [x] Implement FreeRTOS RISC-V port layers
    - [x] C -- implement start/end scheduler functions to init RV timer
    - [x] asm -- setup/load initial task stack(s)
- [x] add example test that runs as a FreeRTOS task 


_Address in: #8190_
- [x] implement default OTTF ISRs that can be overridden by tests (#8190)
- [x] implement asm ISR entry/exit subroutines


_Address in: #8910_
- [x] organize/minimize required features in `FreeRTOSConfig.h`
- [x] configure FreeRTOS to default to non-preemptive scheduling mode


_Address in: see below_
- [x] configure OTTF to automatically report test status and tear down the test infrastructure upon test completion (#9051)
- [ ] run performance analysis vs. current on-device test framework infrastructure
- [ ] submit above for approval to TC
- [ ] Restructure meson build targets to so OTTF tests are link time dependencies
- [ ] Add support for context switching between test (FreeRTOS) tasks
    - [ ] non-preemptive mode --> in ecall exception handler
    - [ ] preemptive mode --> in timer ISR
- [ ] with TC approval, migrate existing on-device tests to use the OTTF (instead of the existing on-device test framework)
- [ ] deprecate existing on-device test framework
- [ ] add support for additional communication transports to opentitantool (besides just UART)

**Comment by timothytrippel** [comment]
![ottf_perf_eval](https://user-images.githubusercontent.com/5633066/141230094-d2c70b0a-2bde-4144-9d42-7ef3abc8d41e.jpg)

Above is the performance evaluation of the OTTF vs. the current on-device (bare-metal) test framework. The evaluation was completed across 4 tests, including 3 smoke tests and an empty test that simply executes `return true;`. Runtimes were computed relative to the current on-device test framework. Across all tests there is a small (constant) runtime overhead of approximately 10k cycles due to the zeroing of the `.bss` section performed by `flash_crt.S`, which is larger for tests using the OTTF since this is where FreeRTOS statically allocates space for the heap. A final optimization can be made to eliminate this overhead completely, but is orthogonal to the OTTF, as described in #9163.

**Comment by alphan** [comment]
The Technical Committee (TC) has decided to **approve** this proposal. Please continue working closely with @sriyerg and other SW contributors and keep a close eye on performance.

**Comment by msfschaffner** [comment]
@timothytrippel is there anything left to do here for M2? If not, can we close or defer into M3?

**Comment by timothytrippel** [comment]
nothing major left here for M2, just some final cleanups for M3. Moving to M3.
