### ISSUE TITLE
[sw/dif] Integrate parameterized IP params into autogenerated IP context struct

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#8409]
Taking `alert_handler` as an example, it seems like it should be possible to bake the parameters right into the autogenerated context:

```c
// In dif_alert_handler_autogen.h:
typedef struct dif_alert_handler {
  /**
   * The base address for the alert_handler hardware registers.
   */
  mmio_region_t base_addr;
  /**
   * The configured number of alerts.
   *
   * This value is fixed by the hardware, but not known to this library.
   */
  uint32_t alert_count;
  /**
   * The configured number of escalation signals.
   *
   * This value is fixed by the hardware, but not known to this library.
   */
  // It's actually fixed at 4 right now but this is likely to become
  // configurable too.
  uint32_t escalation_signal_count;
} dif_alert_handler_t;
```

The bottom two are added to a separate hand-written struct called `dif_alert_handler_params_t`. It should be reasonably straightforward to extract these params from the IP HJson instead and make them a part of the context, so that the DIFs will not longer need an extra params arg.

Filing an issue to see if this is feasible.

**Comment by sriyerg** [comment]
After having a discussion with @tjaychen offline, IPs have an arrtibute called `templated`. The autogenerated portion of DIFs could use that information to know what parameters are to be set in the context. 

It should also add a 'default' context const symbol that represents the parameter values that are already extracted and set in the generated `*_regs.h` header, which is a top-level specific. For example:
```c
  // in dif_alert_handler_autogen.h:
  extern const dif_alert_handler_t kDefaultAlertHandler;

  // in dif_alert_handler_autogen.c:
  const dif_alert_handler_t kDefaultAlertHandler - {
      .base_addr = 0x0,
      .alert_count = ALERT_HANDLER_PARAM_N_ALERTS,
      .escalation_signal_count = ALERT_HANDLER_PARAM_N_ESC_SEV
  };
```

This will allow the end user to initialize the IP instance context with the default set of parameters and just update the `base_addr` as needed. The rest of the parameters are looked up from the generated `*_regs.h` which is top-level specific.

**Comment by timothytrippel** [comment]
I was thinking about this last week actually when implementing autogen'd IRQ DIFs. Definitely makes sense. I can add this to the to-do list after autogen'ing IRQ and Alert DIFs.

**Comment by sriyerg** [comment]
In the autogenerated IRQ test, I make the assumption that the templated IPs will always have parameterized DIFs:
https://github.com/lowRISC/opentitan/pull/8224/files#r718084941

We may want to discuss standardizing this. 
@timothytrippel @tjaychen

**Comment by timothytrippel** [comment]
So I _was_ standardizing this, or at least making all IP DIFs consistent, as apart of implementing the autogen'd IRQ DIFs (see #8142). The way I was doing this was separating the IP's context struct---which I autogenerate and place in `sw/device/lib/dif/autogen/dif_<ip>_autogen.h`---from its *_params_t struct---which is currently manually defined in `sw/device/lib/dif/dif_<ip>.h`. 

**Note**: with this setup, only IP's that are templated [will] have a *_params_t struct defined, since  _params_ w.r.t. to DIFs are just bits of information about the IP that are only known once the IP is auto-generated for a specific toplevel.

Specifically if you take a look at the alert handler DIFs, you will find the IP's _auto-generated_ context defined  in `sw/device/lib/dif/autogen/dif_alert_handler_autogen.h` as:

```
/**
 * A handle to alert_handler.
 *
 * This type should be treated as opaque by users.
 */
typedef struct dif_alert_handler {
   /**
   * The base address for the alert_handler hardware registers.
   */
   mmio_region_t base_addr;
} dif_alert_handler_t;
```
Since the alert handler is a templated IP, you will also find the IP's *_params_t struct _manually_ defined `sw/device/lib/dif/autogen/dif_alert_handler_autogen.h` as:
```
* Hardware instantiation parameters for the alert handler.
*
* This struct describes information about the underlying hardware that is
* not determined until the hardware design is used as part of a top-level
 * design.
 */
typedef struct dif_alert_handler_params {
   /**
    * The configured number of alerts.
    *
    * This value is fixed by the hardware, but not known to this library.
    */
   uint32_t alert_count;
   /**
    * The configured number of escalation signals.
    *
    * This value is fixed by the hardware, but not known to this library.
    */
   // It's actually fixed at 4 right now but this is likely to become
   // configurable too.
  uint32_t escalation_signal_count;
} dif_alert_handler_params_t;
```

That said, I like the idea of completely auto-generating the params too, and placing them in the IP's (already) auto-generated context, as you describe above, with some defaults that correspond to the Earlgrey toplevel. This should be only require a minor tweak to the autogen DIF templates, and updating those IPs whose autogen'd DIFs have already been merged (as is being tracked in #8142).

**Comment by timothytrippel** [comment]
@sriyerg (to summarize what we briefly discussed offline)
First, I want to say it is correct that only templated IPs (which as you point out have the `templated` attribute in the `<toplevel>.hjson` file) should have DIFs that **_may_** use extra bits of information related to the specific toplevel instantiation of said IP that is encapsulated in a `dif_<ip>_params_t` struct (as shown above in the case of the alert handler).

Back when DIFs were **_all_** manually implemented, the base address for the IP was also encapsulated into this `dif_<ip>_params_t` struct as well, and the params struct was encapsulated in an IP's context struct. So the alert handler's context (labeled "_handle_" below) and params structs originally looked like:

```c
 /**
  * Hardware instantiation parameters for the alert handler.
  *
  * This struct describes information about the underlying hardware that is
  * not determined until the hardware design is used as part of a top-level
  * design.
  */
typedef struct dif_alert_handler_params {
  /**
   * The base address for the alert_handler hardware registers.
   */
   mmio_region_t base_addr;
   /**
    * The configured number of alerts.
    *
    * This value is fixed by the hardware, but not known to this library.
    */
   uint32_t alert_count;
   /**
    * The configured number of escalation signals.
    *
    * This value is fixed by the hardware, but not known to this library.
    */
  uint32_t escalation_signal_count;
} dif_alert_handler_params_t;

/**
 * A handle to alert_handler.
 *
 * This type should be treated as opaque by users.
 */
typedef struct dif_alert_handler {
   /**
    * ...
    */
   dif_alert_handler_params_t params;
} dif_alert_handler_t;

```

In order to make auto-generation of the IRQ DIFs feasible (#8142), I had to decouple these structs and keep the base address in the IP's context (handle) struct---which I template and autogenerate with the IRQ DIFs---and have a separate manually-defined params struct (if necessary, that is if an IP is templated and its DIFs need extra top-level specific bits of information). In the case of the alert handler, the decoupled structs looks exactly as shown in my comment above (this change was implemented in #8286). What this meant was that any alert handler DIF which required these bits of "params" information, required altering the specific DIF prototype to require the DIF user to pass not only the context (handle) struct in, but the params struct as well (see [here](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/dif_alert_handler.h#L351) and [here](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/dif_alert_handler.h#L412) for examples).

After further investigation (that has naturally occurred over the course me completing the tasks in #8142), I have noticed that some IPs, e.g., the pinmux, are templated but had no additional params bits of information (besides the base address that was moved to the context struct, as you pointed out in #8463). Similarly, I also noticed that these  extra bits of information related to the specific toplevel instantiation of said IP that are encapsulated in the  `dif_<ip>_params_t`  struct, are only used for checking if a DIF user passes valid args, they never seem to be required to make the DIF perform its intended function.

Therefore, since DIFs are primarily consumed by DV, we could get rid of these extra bits of information, and therefore remove the  `dif_<ip>_params_t`  struct all together. Moreover, as we recently discussed, in the case where a DIF user passes invalid args, it will most likely lead to an exception which will be caught by the test framework anyway.

As I finish the tasks in #8142, I plan to continue staying consistent with how the alert handler is implemented right now---i.e., decouple the context and params structs where needed---but, in the near future, we can make changes to this setup in a future, orthogonal PR that either:

1. Keeps these extra bits of param information but autogenerates them and includes them in the main context (handle) struct for a given IP's DIFs (as you originally described above),

-or-

2. removes this information altogether.

**Comment by timothytrippel** [comment]
So I spent some time to really dig into this, and have come up with a third solution that will hopefully satisfy both @matutem and @sriyerg.

## Background
There are only two IPs---alert_handler and clkmgr---that currently define a `dif_<ip>_params_t` struct that is instantiated by the user of the DIFs, and passed in as an argument to a _subset_ of DIFs for said IPs. The DIFs that use information in the `dif_<ip>_params_t` struct do so only for arg checking purposes.

For example, with the alert_handler, the `dif_alert_handler_param_t` struct looks like (also shown above):
```c
typedef struct dif_alert_handler_params {
  /**
   * The configured number of alerts.
   *
   * This value is fixed by the hardware, but not known to this library.
   */
  uint32_t alert_count;
  /**
   * The configured number of escalation signals.
   *
   * This value is fixed by the hardware, but not known to this library.
   */
  // It's actually fixed at 4 right now but this is likely to become
  // configurable too.
  uint32_t escalation_signal_count;
} dif_alert_handler_params_t;
```
and an alert_handler DIF that uses this information looks like:
```c
dif_result_t dif_alert_handler_alert_is_cause(
    const dif_alert_handler_t *alert_handler, dif_alert_handler_params_t params,
    dif_alert_handler_alert_t alert, bool *is_cause) {
  if (alert_handler == NULL || is_cause == NULL ||
      alert >= params.alert_count) {
    return kDifBadArg;
  }
  ...
}
```

## Problem
Requiring DIF users to instantiate a `dif_<ip>_params_t` with information that is solely used to validate other DIF arguments undermines these validation checks to begin with, especially when no default values are provided for `dif_<ip>_params_t` struct members. Moreover, requiring the `dif_<ip>_params_t` struct as an arg to a subset of DIFs degrades usability.

## Proposed Solution
My proposed solution is two fold:
1. remove the need for DIF users to have to pass a `dif_<ip>_params_t` to some DIFs and remove the definition of the `dif_<ip>_params_t` struct from the remaining two IPs that use it (alert_handler and clkmgr),
1. keep the DIF argument validation by using the information that would other wise be embedded in the `dif_<ip>_params_t` directly from the `<ip>_regs.h` header file that defines it.

### Alert Handler
The alert handler is simple, the `alert_count` and `escalation_signal_count` fields of the `dif_alert_handler_params_t` are already populated by values defined in `alert_handler_regs.h`, which is already included by the alert_handler's DIFs. Therefore, this information can be used directly within the DIFs that require it and the `dif_alert_handler_params_t` struct can be removed completely.

#### Task Burndown
- [x] (#8660) deprecate the `dif_alert_handler_params_t` struct and validate alert_handler DIF args with the same params defined in `alert_handler_regs.h` 

### Clock Manager
The clkmgr is a little more challenging, but the same approach will be taken as the alert_handler. Specifically, the clkmgr has two fields, `last_gateable_clock` and `last_hintable_clock` embedded in its `dif_clkmgr_params_t` struct,  however these values are missing from the autogenerated `clkmgr_regs.h`, even though they are parameters of the IP (see #3932). To standardize the clkmgr with alert_handler, I propose adding these parameter defines to the `clkmgr_regs.h` by adding them to the clkmgr's HJSON file. Then, use them directly within the DIFs that require them for argument validation.

#### Task Burndown
- [x] (#8661) add two local parameters to clkmgr HJSON template: `NumSwGateableClocks` and `NumHintableClocks` to address #3932
- [x] (same as above) deprecate the `dif_clkmgr_params_t` struct and validate clkmgr DIF args with the same params defined in `clkmgr_regs.h`

### Cleanup Tasks
With this solution, there are several DIF cleanups I can make, detailed in the burndown below.

#### Cleanup Task Burndown
- [ ] deprecate `dif_<ip>_params_t` struct from the  `util/make_new_dif/dif_template.h.tpl`
- [ ] update the [DIF website documentation](https://docs.opentitan.org/sw/device/lib/dif/README/index.html#base-types) to reflect the above
- [ ] autogen the `dif_<ip>_init_()` DIF since it will be the same across all IPs after the above changes are made.

## Conclusion
I have gone ahead and submitted two draft PRs to implement the above fixes for both the alert_handler and clkmgr DIFs. If everyone is satisfied with this approach, then we can merge them, and I will submit a final PR to implement the cleanup tasks listed above.
