### ISSUE TITLE
[tracking] Use ipgen to produce templated IPs

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#8440]
The following IP blocks are actually templates at the moment and need to be converted to be using ipgen ([slides discussing motivation and general approach](https://docs.google.com/presentation/d/1x6YRgxdP1w9T-i0oApwelb782H4B5Pbyo4HnR6_Ei4s/edit?usp=sharing)).

- [x] alert_handler: https://github.com/lowRISC/opentitan/pull/8513
- [x] clkmgr
  - [x] Create ipgen files: https://github.com/lowRISC/opentitan/pull/21202
  - [x] Transition to ipgen files and remove old files: https://github.com/lowRISC/opentitan/pull/21321
- [x] flash_ctrl
  - [x] Create ipgen files: https://github.com/lowRISC/opentitan/pull/21170
  - [x] Transition to ipgen files and remove old files: https://github.com/lowRISC/opentitan/pull/22518
- [x] pinmux: https://github.com/lowRISC/opentitan/pull/24808
- [x] pwrmgr: https://github.com/lowRISC/opentitan/pull/19801
- [x] rstmgr: https://github.com/lowRISC/opentitan/pull/21041
- [x] rv_plic: #8431

When the list above is done
- [x] Remove topgen support for "templated" module "attr" attribute: https://github.com/lowRISC/opentitan/pull/25129
- [x] Remove topgen quirks due to templated path searches, as for countermeasures: https://github.com/lowRISC/opentitan/pull/25129

Blocks which were unclear, and their resolution:
- [x] ast: doesn't need generation
- [x] xbar: xbars have their own dedicated generation
- [x] xbar_main: xbars have their own dedicated generation
- [x] xbar_peri: xbars have their own dedicated generation

**Comment by msfschaffner** [comment]
CC @alphan

**Comment by GregAC** [comment]
Triaging for `flash_ctrl`. This is a significant chunk of work and not required for M2.5, however it is likely useful for integrated.

**Comment by andreaskurth** [comment]
Triaged for `pwrmgr` - agree

**Comment by GregAC** [comment]
Triaged for 'rstmgr'

**Comment by GregAC** [comment]
Triaged for `pinmux` - Same conclusion as above

**Comment by GregAC** [comment]
Triaged for `sensor_ctrl` - Same conclusion as above

**Comment by a-will** [comment]
Should templated DIFs also accompany templated IPs? Or do we feel that the current mechanisms with C preprocessor macros is enough?

The alert_handler DIFs notably have static_assert() on the exact values of template parameters.

**Comment by msfschaffner** [comment]
That is a very good question. I have the feeling that some level of customization could be useful and convenient. See also this related discussion regarding documentation: https://github.com/lowRISC/opentitan/pull/19149#discussion_r1266874045

**Comment by matutem** [comment]
Regarding difs, we had to develop templated difs for otp_ctrl.

I have also seen is asked what are the specific points of customization for some top-specific IPs. This is handled in topgen, but it is not black magic, meaning it could be extracted and documented.

**Comment by matutem** [comment]
Changing the milestone past M4.

**Comment by andreaskurth** [comment]
M5 is okay if there are zero Earlgrey RTL changes coming from the open items (which should be the case anyway when the templating is done correctly, right?)

**Comment by andreaskurth** [comment]
As just discussed with @matutem and @vogelpi, we are moving this to the Multi-Top milestone because it's not strictly needed for Earlgrey-PROD.

**Comment by matutem** [comment]
Closing this since the work on otp_ctrl is tracked in a separate issue: https://github.com/lowRISC/opentitan/pull/25129
