### ISSUE TITLE
[sw/sram_ctrl] Chip level tests tracking

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#8546]
https://docs.opentitan.org/hw/top_earlgrey/doc/dv/

- chip_sw_sram_scrambled_access
   - [x] Retention RAM (#8547 )
   - [x] Run in DV
   - [x] Write larger chunks of data (for example, 128bytes instead of a single word)
   - [x] Add randomization via backdoor
   - [x] Introduce repetition (single retry)
   - [x] Main RAM
   - [x] Consider a variable buffer size as per [comment](https://github.com/lowRISC/opentitan/pull/9138#discussion_r748653342)
   - [x]  Reading from scrambled but not initialized SRAM may trigger ECC errors. One solution could be initialising the SRAM before we trigger scrambling.

   Please see the [comment](https://github.com/lowRISC/opentitan/pull/8547#issuecomment-942937209) 

- chip_sw_sram_execution
   - [x] Consider using a naked function instead of a buffer as per [comment](https://github.com/lowRISC/opentitan/pull/9203#discussion_r749537431)
   - [x] Retention RAM
   - [x] Main RAM
   - [x] `dif_sram_ctrl_exec_set_enabled` change `state` to take `uint32_t`
   - [x] Consider making the test buffer variable size, see [comment](https://github.com/lowRISC/opentitan/pull/9138#discussion_r748653342)
   - [x] Consider passing buffer via value instead of the reference [comment](https://github.com/lowRISC/opentitan/pull/9138#discussion_r746639014)
   - [x] Change the test file names to end with `*_test.c`
- chip_sw_sram_lc_escalation
   - [x] Retention RAM
   - [x] Main RAM

Testuitils:
- [x] Consider a common routine to check the ranges as per [comment](https://github.com/lowRISC/opentitan/pull/9204#discussion_r748655398)

**Comment by silvestrst** [comment]
Hi @davebwil , as you are in charge of the SRAM tests. Would you be able to take over this issue for me please?

Some of the items on the list might be redundant, but I think you are in a better position to judge it.

Thanks you!

**Comment by davebwil** [comment]
@silvestrst, Ok

**Comment by weicaiyang** [comment]
checked these 2 items as they're verified in a connectivity test. 
> chip_sw_sram_lc_escalation
> 
> -  Retention RAM
> -  Main RAM

https://github.com/lowRISC/opentitan/blob/9591e1f25d02e10673e259d9c29b42bf0686bfcc/hw/top_earlgrey/formal/conn_csvs/lc_escalate_en.csv#L13-L14

**Comment by johngt** [comment]
@weicaiyang - we are reviewing top-level tests and think that this one slipped through the net for closing out. We believe it may already be addressed. Can you comment on if this still needs testing?

**Comment by weicaiyang** [comment]
> @weicaiyang - we are reviewing top-level tests and think that this one slipped through the net for closing out. We believe it may already be addressed. Can you comment on if this still needs testing?

The tests have been added. Some of the items may be already addressed (like the item - Run in DV, I just checked it).
It will be nice if someone can trace down the original comments and confirm if those are addressed or not. The person who takes this can consider taking https://github.com/lowRISC/opentitan/issues/13543 as well, which are likely not addressed yet.

**Comment by msfschaffner** [comment]
@weicaiyang @msfschaffner to take a look at https://github.com/lowRISC/opentitan/issues/13543 and this issue and close if possible.

**Comment by engdoreis** [comment]
Hi @weicaiyang, I've been working on this issue and I manage to do all the missing items besides this:
 - Add randomization via backdoor
Do you know what would that be exactly?

**Comment by weicaiyang** [comment]
> Hi @weicaiyang, I've been working on this issue and I manage to do all the missing items besides this:
> 
> * Add randomization via backdoor
> 
> Do you know what would that be exactly?

This item is from @sriyerg's [comment](https://github.com/lowRISC/opentitan/pull/8547#issuecomment-942937209) to improve 2 things
- randomize the address
- run multiple iteration, iteration count is random

For randomization via backdoor, you can refer to this [doc](https://docs.google.com/document/d/1Rgeqx0PX8O7906NE-1j8kJ9vPbY50BZQVr5McJTVnxQ/edit#heading=h.bf1ex6xl59ka).

Since this test doesn't need to SV drive anything, perhaps it's easier to do randomization in the C test via using `rand_testutils_gen32_range(min, max)`. Here are some [examples](https://cs.opensource.google/search?q=rand_testutils_gen32_range). Before, we didn't have a good way to do randomization on C side, randomization was usually done on SV side. Now we probably don't need to create a SV test to just pass a few random values.
