### ISSUE TITLE
[dif] Alert force test DIFs should be autogenerated.

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#8879]
Like IRQ DIFs in #8142, the `dif_<ip>_alert_t` DIFs across all IPs can (and should) be autogenerated to both:
1. provide an alert test DIF for all IPs (most IPs are currently missing this functionality), and
2. to make the above consistent across all IPs to facilitate auto-generating an alert chip-level test.

# Tasks
To implement this, the following tasks must be completed:

(Addressed in #8880)
- [x] add functionality to `util/make_new_dif.py` to parse alert information from an IP's HJSON

(Addressed in #8881)
- [x] update the DIF autogen templates
- [x] re-auto-generate all auto-generated DIFs
- [x] deprecate existing (manually-implemented)  `dif_<ip>_alert_t` DIFs across all IPs that currently implement this (which are very few)
