### ISSUE TITLE
[spi_device] Pending tasks for D2

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#8928]
## Pending

- [x] Change Upload Command Interrupt #11871 
- [ ] ~~Change CMD_INFO #10009~~ (Future Release)
- [ ] CG on SCK to control the sys reset release (discussed in #9344 ) (Not Yet Implemented)
- [x] Adding CSRs 
  - [x]  Interrupts
  - [ ] ~~Read address update by SW (next_addr)~~ (Future Release)
- [ ] ~~Direct tests~~ (lower priority now)
  - [x] Upload
  - [x] Read SFDP
  - [x] EN4B/ EX4B
  - [x] WREN/ WRDI
  - [x] Read Cmd
  - [x] Mailbox
  - [ ] Passthrough
    - [x] Command Filtering
    - [ ] Addr Manipulation
    - [x] Payload direction (In/ Out/ Dummy)
    - [ ] Write status manipulation
    - [ ] Mailbox hi-jack
    - [x] Read Status hi-jack

## Done

- [x] Read Buffer Management
  - [x] Last Read Addr from ReadCmd
  - [x] Interrupt : Buffer Threshold.
       #9344 addresses watermark
       #9354 addresses flip
- [x] Passthrough timing violation on `addr_swap_en` / `payload_swap_en` #9741
  - Addressed in #9936 
- [x] JEDEC ID return : #9609 
  - [x] Change CSR to have Continuous Code (1B) + Count (repeating Continous Code) + JEDEC ID (1B) + Additional bytes (2B? or more?)
  - [x]  Connect CSR to JEDEC module
  - [x] Implement counter and continous code logic
- [x] [Flash/ Passthrough Technical Specification](https://docs.google.com/document/d/1VkSKz0egXQoBwwfI9vaHjIzzECHNn9GK1uI3tkGVIsw/edit#)
  - [x] Address Manipulation
  - [x] Data Manipulation
  - [x] Updated CMD_INFO
  - [x] BUSY control
  - [x] Output Enable control
  - [x] Add pointer to TPM_ACCESS_x.activeLocality (Table 39 in TPM PC Client spec)
  - [x] CMD_INFO fixed index table (0-2 for Read Status, 3 for Read JEDEC, 4 for Read SFDP). Add desc that the sub fields won't affect in Flash mode (only in Passthrough mode)
- [x] upload interrupts #9300
- [x] Write Status Data filtering (Manipulation)
  - [x] Adding CSR #9054 
  - [x] Passthrough port change (data_swap_mask & data_swap_data) #9060
  - [x] Adding first byte detection logic #9071 
  - [x] Adding data swap logic (similar with addr_swap) #9071 
  - [x] Adding control of data_swap in FSM #9071 
- [x] Addr 4B forced in CMD_INFO #9157
  - [x] Revise address mode fields in CMD_INFO multireg
    - [x] Change `addr_4b_affected` and `addr_en` to `addr_mode`
      - 00: addr field does not exist
      - 01: addr size is affected by `cfg_addr_4b_en_i`
      - 10: addr size is 3 bytes regardless of `cfg_addr_4b_en_i`
      - 11: addr size is 4 bytes regardless of `cfg_addr_4b_en_i`
  - [x] Tie unused_ in cmdparse, readcmd, upload  modules
  - [x] Add condition in passthrough to enable 4B regardless of `cfg_addr_4b_en_i`
- [x] Passthrough Intercept
    With SW configurations, one of SPID Flash modules (Read Status, Read JEDEC, Read Cmd) is able to intercept SPI Passthrough and processes the command (returning data).
  - [x] Add CSR: INTERCEPT_EN {status, jedec, mailbox, sfdp} #9226
  - [x] Revise Flash modules to check spi_mode
      When spi_mode is Passthrough, the submodule shall stop returning data if INTERCEPT_EN bit is not set. #9258
  - [x] Passthrough logic to cancel the ongoing  transaction by de-asserting CSb. No need of gating SCK #9177
  - [x] Revise SPID top to shift from Passthrough to internal flash for SPI towards the host system. #9258 #9260

**Comment by eunchan** [comment]
Created a PR #9054 for the Data swap feature CSR

**Comment by eunchan** [comment]
Created a PR #9060 for the port change in the passthrough module.

**Comment by eunchan** [comment]
Added forced 4B address mode

**Comment by eunchan** [comment]
Created a PR #9157 to support forced 4B address

**Comment by eunchan** [comment]
Created a PR #9177 to revise passthrough datapath to observe the intercept event then drop the transaction.

**Comment by eunchan** [comment]
Issue #9741 is added. Need to resolve

**Comment by eunchan** [comment]
Updated to the latest status.

**Comment by tjaychen** [comment]
@eunchan just a gentle ping, i think all the items for `passthrough` are already done, can we close this issue?

**Comment by eunchan** [comment]
> @eunchan just a gentle ping, i think all the items for `passthrough` are already done, can we close this issue?

Not yet. Have a couple of items are pending.
