### ISSUE TITLE
[util] Add support to autogenerate ISR testutils functions.

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#9038]
# Overview

Many chip-level tests will need to service IRQs (the `[plic_all_irqs_test](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/autogen/plic_all_irqs_test.c)` is one example). This requires invoking several IRQ related DIFs, all of which are auto-generated (see #8142). The DV team has indicated that it would be useful if we could also auto-generate a higher-level testutils function for each IP that can service IRQs across a specific IP by invoking the right set of DIFs for said IP, and performing the right set of checks at the RV PLIC, see this [past review comment](https://github.com/lowRISC/opentitan/pull/8847#discussion_r735035464).

To support this, I propose the following:

- implementing a Python script `util/autogen_testutils.py` that can auto-generate a subset of `testutils` libraries (for which templates exist); note while some code will reused from the `util/make_new_dif` package this script is intentionally isolated from the `util/make_new_dif.py` script to reduce technical debt
- checking-in all auto-generated `testutils` libraries (similar to what is done with auto-generated DIFs) to `sw/device/lib/testing/autogen/`
- place all `testutils` templates (`.h` and `.c` files) in `util/autogen_testutils/`

To demonstrate how this will be done, I implemented a draft PR to auto-generate a `isr_testutils` library that will satisfy this [prior feature request](https://github.com/lowRISC/opentitan/pull/8847#discussion_r735035464). For similar high-level tasks across IPs, e.g. responding to alerts, other auto-generated test utils may also be added in the future.

**If this is something we would like to proceed with, task list is included below.**

# Task Burndown

(Addressed in #9039)
- [x] implement a Python script `util/autogen_testutils.py` that renders any testutils templates that live in `util/autogen_testutils/`
- [x] implement an `isr_testutils.h.tpl` header template

(Addressed in #11028)
- [x] implement an `isr_testutils.c.tpl` C template
- [x] implement an `meson.build.tpl` build file template

(Addressed in #11029)
- [x] refactor `util/autogen_testutils.py` to enable invoking template rendering logic from `util/make_new_dif.py`, therefore, enabling CI checks on autogenerated testutils code
- [x] autogenerate the above `testutils` library and check-in to repo
- [x] update `util/make_new_dif.py` to invoke the testutils autogen script to keep testutils updated in the event that autogenerated DIFs are updated

(Addressed in #11462)
- [x] add Bazel support for building testutils libs

**Comment by msfschaffner** [comment]
@timothytrippel can you update the status of this issue?

**Comment by moidx** [comment]
@timothytrippel can you triage this issue and determine if can be closed or moved to the Backlog milestone? Thanks
