### ISSUE TITLE
[kmac] Countermeasure and hardening

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#9041]
- [x] Adding FSM sparse encoding for missing submodules
  - [x] Add local alerts for the invalid state encoding
- [x] Add global alert escalation input port
- [x] Add logic to stop operation and enter to dormant state when local alert or global escalation alert occurs.
- [x] Add logic to securely wipe the SW programmed secret key shares #1920 
- [x] counter protection (key index & round count) #7747  
- [x] Shadow register for the configuration #8982  PR #7439 (should change the scheme to follow more generic way not `hwext`)

related #8982 
related #6544

**Comment by cdgori** [comment]
here, I would say "securely wipe" rather than "wipe out"

for the dormant state, should we think about resetting the keccak state?  (@tjaychen  should we ask some other folks to see if they have opinions?  We believe that the hamming weight leakage of something that wide is not problematic, and I feel like zeroing anything potentially sensitive and based on early-terminated operation isn't a bad idea.  But maybe I am going overboard here.)

**Comment by tjaychen** [comment]
i also filed #8982 a few days ago, but I believe most of the points are already covered here.
@eunchan would you mind having a look and just closing the other issue if it's the case?

**Comment by eunchan** [comment]
> i also filed #8982 a few days ago, but I believe most of the points are already covered here. @eunchan would you mind having a look and just closing the other issue if it's the case?

Thanks Tim, I didn't notice it. Looks like I missed the shadow register item here. Just added :) Thanks!

**Comment by eunchan** [comment]
> here (4th item), I would say "securely wipe" rather than "wipe out" just to be really precise.
> 
Revised. :) thanks !

**Comment by eunchan** [comment]
@m-temp Here's more combined items for KMAC hardening. (forgot I created this :) )

**Comment by m-temp** [comment]
@eunchan We can update the tasks here as well.
