### ISSUE TITLE
[otbn][tracking] Sign off D2

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#9220]
This issue tracks outstanding work for reaching D2, when an item is checked it has been signed off on OTBN D2 checklist

Estimate for this only includes things not covered by linked issues.

> estimate 16

- [x] NEW_FEATURES (spec)
  - [x] PRNG Lockup fatal alert #9011 
  - [x] Secure Wipe for CSRs #8287 
- [x] BLOCK_DIAGRAM
  - [x] Review for anything missing 
  - [x] Add prefetch stage 
- [x] DOC_INTERFACE
  - Ready needs sign off
- [x] MISSING_FUNC 
  - No missing functionality
- [x] FEATURE_FROZEN
  - No outstanding new features, ready for freeze
- [x] FEATURE_COMPLETE
  - [x] Prefetch stage #8994
  - [x] Key sideload #7279 
  - [x] IMem Checksum #6175
  - [x] DMem scratchpad #6233
  - [x] Connect up software alerts #8242
  - See NEW_FEATURES
 - [x] AREA_CHECK
   - Area numbers available in synthesis report
 - [x] PORT_FROZEN
   - Ports are final
 - [x] ARCHITECTURE_FROZEN
   -  [x] IMem Checksum #8503 
   -  [x] PRNG Lockup fatal alert #9223
 - [x] REVIEW_TODO
   - [x] Review them
 - [x] STYLE_X
   - [x] Review X usage and check it confirms to style guide
 - [x] LINT_PASS
   - Lint is clean
   - Single reported ascent lint failure is from prim_generic_ram_1p module, outside block scope
 - [x] CDC_SETUP
   - [x] Determine what is required for a CDC checking run setup (if one is required)
 - [x] FPGA_TIMING
   - OTBN synthesized for FPGA in CI
 - [x] CDC_SYNCMACRO
   - OT primitives used for all CDC  
 - [x] SEC_CM_DOCUMENTED
   - Blanking not yet documented, suggest postpone to D3 (or D2S?)
   - Note loop stack hardening unimplemented / unspecified
      - Any other things missing? 
 - [x] SEC_RND_CNST
   - All secure random constants dealt with appropriately
