### ISSUE TITLE
[sw/silicon_creator] Tracking issue for separating mask ROM crypto

### ISSUE THREAD

**Issue by jadephilipoom** [lowRISC/opentitan#9303]
Currently, all crypto code is in `silicon_creator/lib/crypto`. Based on recent discussions, we want to reorganize a bit, keeping only the mask ROM or ROM_EXT specific code there and moving everything else outside of `silicon_creator` into the place where the OS-visible crypto library will eventually live. We also want to remove the duplication of OTBN assembly files, instead importing them from `sw/otbn/crypto`, which will hold the shared, canonical version of OTBN crypto algorithms.

Broken down into steps, this will look something like:
- [x] Separate out the mask ROM/ROM_EXT code from the more general code within `silicon_creator/lib/crypto` (without moving anything yet)
- [x] Move OTBN crypto assembly files for ECDSA-P256 and RSA-3072 to a new directory `sw/otbn/crypto`
- [x] Remove duplicate OTBN assembly files from `silicon_creator/lib/crypto` and import the `sw/otbn/crypto` versions instead
- [ ] Move everything that's not ROM/ROM_EXT specific out of `silicon_creator` and change it to use the runtime drivers instead of the `silicon_creator` ones
