### ISSUE TITLE
[otbn] Define coverage points for all the "peripheral" DV work we've done

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#9668]
We've added DV coverage for several OTBN features other than just executing code, but it doesn't have any functional coverage associated with it. Fix that!

Stuff that needs tracking properly:
- [x] External CSRs (#10025)
- [x] Key sideload interface (#10027)
- [x] Fatal software errors(#10048)
- [x] Scratchpad memory (#10054)
- [x] Timing between RND reads, prefetches and the EDN (#10086)
- [x] The lifecycle escalation signal (#10087)
- [x] Internal integrity (probably tracked in testplan, rather than functional coverage) (#10026)
